// Copyright Chad Engler

#include "he/core/assert.h"
#include "he/core/hash.h"
#include "he/core/memory_ops.h"
#include "he/core/path.h"
#include "he/core/string.h"
#include "he/core/type_traits.h"
#include "he/core/vector.h"
#include "he/schema/codegen.h"
#include "he/schema/schema.h"

#include "fmt/format.h"

namespace he::schema
{
    class CodeGenCpp
    {
    public:
        CodeGenCpp(const SchemaDef& schema, const CodeGenOptions& options, CodeWriter& writer)
            : m_schema(schema)
            , m_options(options)
            , m_writer(writer)
        {}

        bool Generate()
        {
            m_writer.Reserve(2048);

            // Header
            m_writer.Write("// Generated by the Harvest Schema compiler\n\n");
            m_writer.Write("#pragma once\n\n");

            // TODO: Reduce includes to only those necessary

            // Includes
            m_writer.Write("#include \"he/core/string.h\"\n");
            m_writer.Write("#include \"he/core/types.h\"\n");
            m_writer.Write("#include \"he/core/vector.h\"\n");
            m_writer.Write('\n');

            GenIncludes();

            m_writer.Write("#include <array>\n");
            m_writer.Write("#include <list>\n");
            m_writer.Write("#include <unordered_map>\n");
            m_writer.Write("#include <unordered_set>\n");
            m_writer.Write('\n');

            // Open the file namespace
            if (!m_schema.namespaceName.IsEmpty())
            {
                HashNamespace();
                m_writer.WriteIndent();
                m_writer.Write("namespace ");
                WriteWithReplace(m_schema.namespaceName, '.', "::");
                m_writer.Write('\n');
                m_writer.WriteIndent();
                m_writer.Write("{\n");
                m_writer.IncreaseIndent();
            }

            // Forward struct declarations
            for (uint32_t i = 0; i < m_schema.structs.Size(); ++i)
            {
                GenForward(m_schema.structs[i], "struct");
            }

            // Forward interface declarations
            for (uint32_t i = 0; i < m_schema.interfaces.Size(); ++i)
            {
                GenForward(m_schema.interfaces[i], "class");
            }

            // Constant definitions
            for (uint32_t i = 0; i < m_schema.consts.Size(); ++i)
            {
                GenConst(m_schema.consts[i]);
            }

            // Enum definitions
            for (uint32_t i = 0; i < m_schema.enums.Size(); ++i)
            {
                GenEnum(m_schema.enums[i]);
            }

            // Alias definitions
            for (uint32_t i = 0; i < m_schema.aliases.Size(); ++i)
            {
                GenAlias(m_schema.aliases[i]);
            }

            // Struct definitions
            for (uint32_t i = 0; i < m_schema.structs.Size(); ++i)
            {
                GenStruct(m_schema.structs[i], m_namespaceHash);
            }

            // Interface declarations
            for (uint32_t i = 0; i < m_schema.interfaces.Size(); ++i)
            {
                GenInterface(m_schema.interfaces[i], m_namespaceHash);
            }

            // Close the namespace
            if (!m_schema.namespaceName.IsEmpty())
            {
                m_writer.DecreaseIndent();
                m_writer.WriteIndent();
                m_writer.Write('}');
            }

            m_writer.Write('\n');

            return true;
        }

        void GenIncludes()
        {
            bool hasInclude = false;
            for (uint32_t i = 0; i < m_schema.imports.Size(); ++i)
            {
                const String& import = m_schema.imports[i];
                if (import.IsEmpty())
                    continue;

                hasInclude = true;

                const StringView ext = GetExtension(import);
                const StringView path(import.Begin(), ext.IsEmpty() ? import.End() : ext.Begin());

                m_writer.Write("#include \"");
                m_writer.Write(path);
                m_writer.Write(".h\"\n");
            }

            if (hasInclude)
                m_writer.Write('\n');
        }

        void GenGenericDecl(const Vector<String>& typeParams)
        {
            if (typeParams.IsEmpty())
                return;

            m_writer.WriteIndent();
            m_writer.Write("template <");
            for (uint32_t i = 0; i < typeParams.Size(); ++i)
            {
                m_writer.Write("typename ");
                m_writer.Write(typeParams[i]);
                if (i < (typeParams.Size() - 1))
                    m_writer.Write(", ");
            }
            m_writer.Write(">\n");
        }

        template <typename T>
        void GenForward(const T& def, const char* prefix)
        {
            GenGenericDecl(def.typeParams);
            m_writer.WriteIndent();
            m_writer.Write(prefix);
            m_writer.Write(' ');
            m_writer.Write(def.name);
            m_writer.Write(";\n");
        }

        void GenConst(const ConstDef& def)
        {
            m_writer.WriteIndent();
            m_writer.Write("constexpr ");
            if (def.base == BaseType::String)
            {
                m_writer.Write("char ");
            }
            else
            {
                WriteSimpleType(def.base);
                m_writer.Write(' ');
            }
            m_writer.Write(def.name);
            if (def.base == BaseType::String)
            {
                m_writer.Write("[] ");
            }
            m_writer.Write(" = ");
            WriteValue(def.base, def.value);
            m_writer.Write(";\n");
        }

        void GenAlias(const AliasDef& def)
        {
            GenGenericDecl(def.typeParams);
            m_writer.WriteIndent();
            m_writer.Write("using ");
            m_writer.Write(def.name);
            m_writer.Write(" = ");
            WriteType(def.type);
            m_writer.Write(";\n");
        }

        void GenEnum(const EnumDef& def)
        {
            m_writer.WriteIndent();
            m_writer.Write("enum class ");
            m_writer.Write(def.name);
            m_writer.Write(" : ");
            WriteSimpleType(def.base);
            m_writer.Write('\n');
            m_writer.WriteIndent();
            m_writer.Write("{\n");
            m_writer.IncreaseIndent();

            for (uint32_t i = 0; i < def.values.Size(); ++i)
            {
                const EnumValueDef& val = def.values[i];
                m_writer.WriteIndent();
                m_writer.Write(val.name);
                m_writer.Write(" = ");
                m_writer.Write("{}", val.value);
                m_writer.Write(",\n");
            }
            m_writer.DecreaseIndent();
            m_writer.WriteIndent();
            m_writer.Write("};\n");

            m_writer.WriteIndent();
            m_writer.Write("inline const char* AsString(");
            m_writer.Write(def.name);
            m_writer.Write(" value)\n");
            m_writer.WriteIndent();
            m_writer.Write("{\n");
            m_writer.IncreaseIndent();

            m_writer.WriteIndent();
            m_writer.Write("switch (value)\n");

            m_writer.WriteIndent();
            m_writer.Write("{\n");
            m_writer.IncreaseIndent();

            for (uint32_t i = 0; i < def.values.Size(); ++i)
            {
                const EnumValueDef& val = def.values[i];
                m_writer.WriteIndent();
                m_writer.Write("case ");
                m_writer.Write(def.name);
                m_writer.Write("::");
                m_writer.Write(val.name);
                m_writer.Write(": return \"");
                m_writer.Write(val.name);
                m_writer.Write("\";\n");
            }
            m_writer.WriteIndent();
            m_writer.Write("}\n");
            m_writer.DecreaseIndent();

            m_writer.WriteIndent();
            m_writer.Write("return \"\";");

            m_writer.WriteIndent();
            m_writer.Write("}\n");
            m_writer.DecreaseIndent();
        }

        void GenStruct(const StructDef& def, uint32_t parentTypeId)
        {
            uint32_t typeId = GetTypeId(def.name, parentTypeId);

            GenGenericDecl(def.typeParams);
            m_writer.WriteIndent();
            m_writer.Write("struct ");
            m_writer.Write(def.name);
            if (def.extends.base != BaseType::Unknown || !def.extends.name.IsEmpty())
            {
                m_writer.Write(" : ");
                WriteType(def.extends);
            }
            m_writer.Write('\n');
            m_writer.WriteIndent();
            m_writer.Write("{\n");
            m_writer.IncreaseIndent();

            m_writer.WriteIndent();
            m_writer.Write("static constexpr uint32_t TypeId = ");
            WriteAsHex(typeId);
            m_writer.Write(";\n");

            for (uint32_t i = 0; i < def.fields.Size(); ++i)
            {
                const FieldDef& field = def.fields[i];
                uint32_t fieldId = GetTypeId(field.name, typeId);
                m_writer.WriteIndent();
                m_writer.Write("static constexpr uint32_t FieldId_");
                m_writer.Write(field.name);
                m_writer.Write(" = ");
                WriteAsHex(fieldId);
                m_writer.Write(";\n");
            }
            m_writer.Write('\n');

            for (uint32_t i = 0; i < def.consts.Size(); ++i)
            {
                GenConst(def.consts[i]);
            }

            for (uint32_t i = 0; i < def.enums.Size(); ++i)
            {
                GenEnum(def.enums[i]);
            }

            for (uint32_t i = 0; i < def.aliases.Size(); ++i)
            {
                GenAlias(def.aliases[i]);
            }

            for (uint32_t i = 0; i < def.structs.Size(); ++i)
            {
                GenStruct(def.structs[i], typeId);
            }

            for (uint32_t i = 0; i < def.fields.Size(); ++i)
            {
                const FieldDef& field = def.fields[i];
                m_writer.WriteIndent();
                WriteType(field.type);
                m_writer.Write(' ');
                m_writer.Write(field.name);
                m_writer.Write("{ ");
                WriteValue(field.type.base, field.defaultValue);
                m_writer.Write(" };\n");
            }

            m_writer.DecreaseIndent();
            m_writer.WriteIndent();
            m_writer.Write("};\n");
        }

        void GenInterface(const InterfaceDef& def, uint32_t parentTypeId)
        {
            uint32_t typeId = GetTypeId(def.name, parentTypeId);

            GenGenericDecl(def.typeParams);
            m_writer.WriteIndent();
            m_writer.Write("class ");
            m_writer.Write(def.name);
            if (!def.implements.IsEmpty())
            {
                m_writer.Write(" : ");
                for (uint32_t i = 0; i < def.implements.Size(); ++i)
                {
                    m_writer.Write("public ");
                    WriteType(def.implements[i]);
                    if (i < (def.implements.Size() - 1))
                        m_writer.Write(", ");
                }
            }
            m_writer.Write('\n');
            m_writer.WriteIndent();
            m_writer.Write("{\n");
            m_writer.WriteIndent();
            m_writer.Write("public:\n");
            m_writer.IncreaseIndent();

            m_writer.WriteIndent();
            m_writer.Write("static constexpr uint32_t TypeId = ");
            WriteAsHex(typeId);
            m_writer.Write(";\n");

            for (uint32_t i = 0; i < def.consts.Size(); ++i)
            {
                GenConst(def.consts[i]);
            }

            for (uint32_t i = 0; i < def.enums.Size(); ++i)
            {
                GenEnum(def.enums[i]);
            }

            for (uint32_t i = 0; i < def.aliases.Size(); ++i)
            {
                GenAlias(def.aliases[i]);
            }

            for (uint32_t i = 0; i < def.structs.Size(); ++i)
            {
                GenStruct(def.structs[i], typeId);
            }

            for (uint32_t i = 0; i < def.methods.Size(); ++i)
            {
                GenMethod(def.methods[i]);
            }

            m_writer.DecreaseIndent();
            m_writer.WriteIndent();
            m_writer.Write("};\n");
        }

        void GenMethod(const MethodDef& def)
        {
            m_writer.WriteIndent();
            m_writer.Write("virtual ");
            WriteType(def.returnType);
            m_writer.Write(' ');
            m_writer.Write(def.name);
            m_writer.Write('(');

            for (uint32_t i = 0; i < def.parameters.Size(); ++i)
            {
                const MethodParamDef& param = def.parameters[i];
                WriteParamType(param.type);
                m_writer.Write(' ');
                m_writer.Write(param.name);
                if (i < (def.parameters.Size() - 1))
                    m_writer.Write(", ");
            }
            m_writer.Write(") = 0;\n");
        }

    private:
        void WriteWithReplace(const StringView& input, char what, const StringView& with)
        {
            for (char ch : input)
            {
                if (ch == what)
                {
                    m_writer.Write(with);
                }
                else
                {
                    m_writer.Write(ch);
                }
            }
        }

        void WriteEscaped(const StringView& input)
        {
            for (char ch : input)
            {
                switch (ch)
                {
                    case '\'': // single quote
                        m_writer.Write("\\\'");
                        break;
                    case '\"': // double quote
                        m_writer.Write("\\\"");
                        break;
                    case '\\': // backslash
                        m_writer.Write("\\\\");
                        break;
                    case '\b': // backspace
                        m_writer.Write("\\b");
                        break;
                    case '\f': // form feed - new page
                        m_writer.Write("\\f");
                        break;
                    case '\n': // line feed - new line
                        m_writer.Write("\\n");
                        break;
                    case '\r': // carriage return
                        m_writer.Write("\\r");
                        break;
                    case '\t': // horizontal tab
                        m_writer.Write("\\t");
                        break;
                    case '\v': // vertical tab
                        m_writer.Write("\\v");
                        break;
                    default:
                        // TODO: Hex sequence, Unicode sequence
                        m_writer.Write(ch);
                }
            }
        }

        template <typename T, HE_REQUIRES(std::is_integral_v<T>)>
        void WriteAsHex(T value)
        {
            m_writer.Write("{:#0{}x}", value, 2 + (sizeof(T) * 2));
        }

        void HashNamespace()
        {
            FNV32 hash;
            hash.String(m_schema.namespaceName.Data());
            hash.String(".");
            m_namespaceHash = hash.Done();
        }

        uint32_t GetTypeId(const String& name, uint32_t parentTypeId)
        {
            return FNV32::HashString(name.Data(), parentTypeId);
        }

        void WriteParamType(const Type& t)
        {
            switch (t.base)
            {
                case BaseType::Bool:
                case BaseType::Int8:
                case BaseType::Int16:
                case BaseType::Int32:
                case BaseType::Int64:
                case BaseType::Uint8:
                case BaseType::Uint16:
                case BaseType::Uint32:
                case BaseType::Uint64:
                case BaseType::Float32:
                case BaseType::Float64:
                case BaseType::Enum:
                    return WriteType(t);
                case BaseType::String:
                case BaseType::Array:
                case BaseType::List:
                case BaseType::Map:
                case BaseType::Set:
                case BaseType::Interface:
                case BaseType::Struct:
                    m_writer.Write("const ");
                    WriteType(t);
                    m_writer.Write('&');
                    break;
                case BaseType::Unknown:
                    HE_ASSERT(false, "Encountered an unknown type!");
                    break;
            }
        }

        void WriteSimpleType(BaseType t)
        {
            switch (t)
            {
                case BaseType::Bool: m_writer.Write("bool"); break;
                case BaseType::Int8: m_writer.Write("int8_t"); break;
                case BaseType::Int16: m_writer.Write("int16_t"); break;
                case BaseType::Int32: m_writer.Write("int32_t"); break;
                case BaseType::Int64: m_writer.Write("int64_t"); break;
                case BaseType::Uint8: m_writer.Write("uint8_t"); break;
                case BaseType::Uint16: m_writer.Write("uint16_t"); break;
                case BaseType::Uint32: m_writer.Write("uint32_t"); break;
                case BaseType::Uint64: m_writer.Write("uint64_t"); break;
                case BaseType::Float32: m_writer.Write("float"); break;
                case BaseType::Float64: m_writer.Write("double"); break;
                case BaseType::String: m_writer.Write("he::String"); break;
                default:
                    HE_ASSERT(false, "Invalid base type encountered in WriteSimpleType!");
                    break;
            }
        }

        void WriteType(const Type& t)
        {
            switch (t.base)
            {
                case BaseType::Bool:
                case BaseType::Int8:
                case BaseType::Int16:
                case BaseType::Int32:
                case BaseType::Int64:
                case BaseType::Uint8:
                case BaseType::Uint16:
                case BaseType::Uint32:
                case BaseType::Uint64:
                case BaseType::Float32:
                case BaseType::Float64:
                case BaseType::String:
                    WriteSimpleType(t.base);
                    break;
                case BaseType::Array:
                {
                    HE_ASSERT(t.element);
                    if (t.fixedSize == 0 && t.name.IsEmpty())
                    {
                        m_writer.Write("Vector<");
                        WriteType(*t.element);
                        m_writer.Write('>');
                    }
                    else
                    {
                        m_writer.Write("std::array<");
                        WriteType(*t.element);
                        m_writer.Write(", ");


                        if (t.fixedSize != 0)
                            m_writer.Write("{}", t.fixedSize);
                        else
                            m_writer.Write(t.name);
                        m_writer.Write('>');
                    }
                    break;
                }
                case BaseType::List:
                {
                    HE_ASSERT(t.element);
                    m_writer.Write("std::list<");
                    WriteType(*t.element);
                    m_writer.Write('>');
                    break;
                }
                case BaseType::Map:
                {
                    HE_ASSERT(t.key && t.element);
                    m_writer.Write("std::unordered_map<");
                    WriteType(*t.key);
                    m_writer.Write(", ");
                    WriteType(*t.element);
                    m_writer.Write('>');
                    break;
                }
                case BaseType::Set:
                {
                    HE_ASSERT(t.element);
                    m_writer.Write("std::unordered_set<");
                    WriteType(*t.element);
                    m_writer.Write('>');
                    break;
                }
                case BaseType::Enum:
                    m_writer.Write(t.name);
                    break;
                case BaseType::Interface:
                case BaseType::Struct:
                    m_writer.Write(t.name);
                    if (!t.typeParams.IsEmpty())
                    {
                        m_writer.Write('<');
                        for (uint32_t i = 0; i < t.typeParams.Size(); ++i)
                        {
                            WriteType(t.typeParams[i]);
                            if (i < (t.typeParams.Size() - 1))
                                m_writer.Write(", ");
                        }
                        m_writer.Write('>');
                    }
                    break;
                case BaseType::Unknown:
                    HE_ASSERT(false, "Encountered an unknown type!");
                    break;
            }
        }

        void WriteValue(BaseType t, const Value& v)
        {
            switch (t)
            {
                case BaseType::Bool: m_writer.Write("{}", v.basic.b); break;
                case BaseType::Int8: m_writer.Write("{}", v.basic.i8); break;
                case BaseType::Int16: m_writer.Write("{}", v.basic.i16); break;
                case BaseType::Int32: m_writer.Write("{}", v.basic.i32); break;
                case BaseType::Int64: m_writer.Write("{}", v.basic.i64); break;
                case BaseType::Uint8: m_writer.Write("{}", v.basic.u8); break;
                case BaseType::Uint16: m_writer.Write("{}", v.basic.u16); break;
                case BaseType::Uint32: m_writer.Write("{}", v.basic.u32); break;
                case BaseType::Uint64: m_writer.Write("{}", v.basic.u64); break;
                case BaseType::Float32: m_writer.Write("{}", v.basic.f32); break;
                case BaseType::Float64: m_writer.Write("{}", v.basic.f64); break;
                case BaseType::String:
                    m_writer.Write('"');
                    WriteEscaped(v.str);
                    m_writer.Write('"');
                    break;
                case BaseType::Array:
                case BaseType::List:
                case BaseType::Map:
                case BaseType::Set:
                case BaseType::Interface:
                case BaseType::Struct: m_writer.Write(v.str); break;
                case BaseType::Enum: WriteWithReplace(v.str, '.', "::"); break;
                case BaseType::Unknown:
                    HE_ASSERT(false, "Encountered an unknown type!");
                    break;
            }
        }

    private:
        const SchemaDef& m_schema;
        const CodeGenOptions& m_options;
        CodeWriter& m_writer;

        uint32_t m_namespaceHash{ FNV32::Seed };
    };

    bool GenerateCpp(const SchemaDef& def, const CodeGenOptions& options, CodeWriter& writer)
    {
        CodeGenCpp generator(def, options, writer);
        return generator.Generate();
    }
}
