# Copyright Chad Engler

id = "doxygen.doxygen"
name = "Doxygen"
description = "Generate documentation from source code."
version = "1.9.5"
authors = ["Dimitri van Heesch"]
license = "GPL-2.0"
homepage = "https://doxygen.nl/index.html"

[install]
    index_archive_by_host = true

    [install.archive]
        linux = "https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz"
        windows = "https://www.doxygen.nl/files/doxygen-1.9.5.windows.x64.bin.zip"
