// Copyright Chad Engler

// This file is based on the implementation in tuplet
// https://github.com/codeinred/tuplet/
//
// License:
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#pragma once

#include "he/core/compiler.h"
#include "he/core/concepts.h"
#include "he/core/type_traits.h"
#include "he/core/types.h"
#include "he/core/utils.h"

namespace he
{
    // --------------------------------------------------------------------------------------------
    // Internal implementation details

    /// \internal
    template <typename T, typename U>
    constexpr bool _TuplePartialCompare(const T& a, const U& b, bool& isLess)
    {
        if (a < b)
        {
            isLess = true;
            return false;
        }
        return a == b;
    }

    template <typename T1, typename T2, typename... B1, typename... B2>
    constexpr bool _TupleEqual(const T1& t1, const T2& t2, TypeList<B1...>, TypeList<B2...>)
    {
    #if HE_COMPILER_MSVC
        return [&](auto&... v1) -> bool
        {
            return [&](auto&... v2) -> bool
            {
                return ((v1 == v2) && ...);
            }(t2.IdentityType<B2>::value...);
        }(t1.IdentityType<B1>::value...);
    #else
        return ((t1.IdentityType<B1>::value == t2.IdentityType<B2>::value) && ...);
    #endif
    }

    template <typename T1, typename T2, typename... B1, typename... B2>
    constexpr bool _TupleLess(const T1& t1, const T2& t2, TypeList<B1...>, TypeList<B2...>)
    {
        bool isLess = false;
    #if HE_COMPILER_MSVC
        [&](auto&... v1) -> bool
        {
            return [&](auto&... v2) -> bool
            {
                return (_TuplePartialCompare(v1, v2, isLess) && ...);
            }(t2.IdentityType<B2>::value...);
        }(t1.IdentityType<B1>::value...);
    #else
        ((_TuplePartialCompare(t1.IdentityType<B1>::value, t2.IdentityType<B2>::value, isLess) && ...);
    #endif
        return isLess;
    }

    template <typename T1, typename T2, typename... B1, typename... B2>
    constexpr bool _TupleLessEqual(const T1& t1, const T2& t2, TypeList<B1...>, TypeList<B2...>)
    {
        bool isLess = false;
    #if HE_COMPILER_MSVC
        const bool isEqual = [&](auto&... v1) -> bool
        {
            return [&](auto&... v2) -> bool
            {
                return (_TuplePartialCompare(v1, v2, isLess) && ...);
            }(t2.IdentityType<B2>::value...);
        }(t1.IdentityType<B1>::value...);
    #else
        const bool isEqual = ((_TuplePartialCompare(t1.IdentityType<B1>::value, t2.IdentityType<B2>::value, isLess) && ...);
    #endif
        return isLess || isEqual;
    }

    template <uint32_t I>
    using _TupleTag = IntegralConstant<uint32_t, I>;

    template <uint32_t I, typename T>
    struct _TupleStorage
    {
        static T DeclElement(_TupleTag<I>);
        using Type = T;
        [[no_unique_address]] T value;

        constexpr decltype(auto) operator[](_TupleTag<I>) const& { return (value); }
        constexpr decltype(auto) operator[](_TupleTag<I>) & { return (value); }
        constexpr decltype(auto) operator[](_TupleTag<I>) && { return (Move(*this).value); }

        constexpr bool operator==(const _TupleStorage& x) const noexcept { return value == x.value; }
        constexpr bool operator!=(const _TupleStorage& x) const noexcept { return value != x.value; }
        constexpr bool operator<(const _TupleStorage& x) const noexcept { return value < x.value; }
        constexpr bool operator<=(const _TupleStorage& x) const noexcept { return value <= x.value; }
        constexpr bool operator>(const _TupleStorage& x) const noexcept { return value > x.value; }
        constexpr bool operator>=(const _TupleStorage& x) const noexcept { return value >= x.value; }
    };

    template <typename... Bases>
    struct _TupleMap : Bases...
    {
        using BaseList = TypeList<Bases...>;
        using Bases::operator[]...;
        using Bases::DeclElement...;

        constexpr bool operator==(const _TupleMap& x) const noexcept { return _TupleEqual(*this, x, BaseList{}, BaseList{}); }
        constexpr bool operator!=(const _TupleMap& x) const noexcept { return !(*this == x); }
        constexpr bool operator<(const _TupleMap& x) const noexcept { return _TupleLess(*this, x, BaseList{}, BaseList{}); }
        constexpr bool operator<=(const _TupleMap& x) const noexcept { return _TupleLessEqual(*this, x, BaseList{}, BaseList{}); }
        constexpr bool operator>(const _TupleMap& x) const noexcept { return _TupleLess(x, *this, BaseList{}, BaseList{}); }
        constexpr bool operator>=(const _TupleMap& x) const noexcept { return _TupleLessEqual(x, *this, BaseList{}, BaseList{}); }
    };

    template <typename I, typename... T>
    struct _TupleBaseHelper;

    template <uint32_t... I, typename... T>
    struct _TupleBaseHelper<IndexSequence<I...>, T...>
    {
        using Type = _TupleMap<_TupleStorage<I, T>...>;
    };

    template <typename... T>
    using _TupleBase = typename _TupleBaseHelper<IndexSequenceFor<T...>, T...>::Type;

    template <typename T>
    concept _HasBaseList = requires { typename Decay<T>::BaseList; };

    template <typename T, typename F, typename... B>
    constexpr bool _TupleAny(T&& tuple, F&& func, TypeList<B...>)
    {
    #if HE_COMPILER_MSVC
        return [&](auto&&... v1) -> bool
        {
            return (bool(func(Forward<decltype(v1)>(v1))) || ...);
        }(Forward<T>(tuple).IdentityType<B>::value...);
    #else
        return (bool(func(Forward<T>(tuple).IdentityType<B>::value)) || ...);
    #endif
    }

    template <typename T, typename F, typename... B>
    constexpr bool _TupleAll(T&& tuple, F&& func, TypeList<B...>)
    {
    #if HE_COMPILER_MSVC
        return [&](auto&&... v1) -> bool
        {
            return (bool(func(Forward<decltype(v1)>(v1))) && ...);
        }(Forward<T>(tuple).IdentityType<B>::value...);
    #else
        return (bool(func(Forward<T>(tuple).IdentityType<B>::value)) && ...);
    #endif
    }

    template <typename T, typename F, typename... B>
    constexpr decltype(auto) _TupleApply(T&& tuple, F&& func, TypeList<B...>)
    {
        return func(Forward<T>(tuple).IdentityType<B>::value...);
    }

    template <typename T, typename F, typename... B>
    constexpr void _TupleForEach(T&& tuple, F&& func, TypeList<B...>)
    {
    #if HE_COMPILER_MSVC
        [&](auto&&... v1)
        {
            (void(func(Forward<decltype(v1)>(v1))), ...);
        }(Forward<T>(tuple).IdentityType<B>::value...);
    #else
        (void(func(Forward<T>(tuple).IdentityType<B>::value)), ...);
    #endif
    }
    /// \endinternal

    // --------------------------------------------------------------------------------------------
    // Tuple definition

    template <typename... T>
    class Tuple : public _TupleBase<T...>
    {
    public:
        static constexpr uint32_t Size = sizeof...(T);
        using Super = _TupleBase<T...>;
        using Super::operator[];
        using Super::DeclElement;

        using BaseList = typename Super::BaseList;
        using ElementList = TypeList<T...>;

        constexpr bool operator==(const Tuple& x) const noexcept { return _TupleEqual(*this, x, BaseList{}, BaseList{}); }
        constexpr bool operator!=(const Tuple& x) const noexcept { return !(*this == x); }
        constexpr bool operator<(const Tuple& x) const noexcept { return _TupleLess(*this, x, BaseList{}, BaseList{}); }
        constexpr bool operator<=(const Tuple& x) const noexcept { return _TupleLessEqual(*this, x, BaseList{}, BaseList{}); }
        constexpr bool operator>(const Tuple& x) const noexcept { return _TupleLess(x, *this, BaseList{}, BaseList{}); }
        constexpr bool operator>=(const Tuple& x) const noexcept { return _TupleLessEqual(x, *this, BaseList{}, BaseList{}); }

        template <typename U> requires(IsSpecialization<Decay<U>, Tuple>)
        constexpr Tuple& operator=(U&& u)
        {
            using T2 = Decay<U>;
            AssignInternal(Forward<U>(u), BaseList{}, typename T2::BaseList{});
            return *this;
        }

        template <typename... U>
        constexpr bool operator==(const Tuple<U...>& x) const requires(EqualityComparableWith<T, U> && ...)
        {
            using OtherBaseList = typename Tuple<U...>::BaseList;
            return _TupleEqual(*this, x, BaseList{}, OtherBaseList{});
        }

        template <typename... U>
        constexpr bool operator!=(const Tuple<U...>& x) const requires(EqualityComparableWith<T, U> && ...)
        {
            using OtherBaseList = typename Tuple<U...>::BaseList;
            return !(*this == x);
        }

        template <typename... U>
        constexpr bool operator<(const Tuple<U...>& x) const requires(EqualityComparableWith<T, U> && ...)
        {
            using OtherBaseList = typename Tuple<U...>::BaseList;
            return _TupleLess(*this, x, BaseList{}, OtherBaseList{});
        }

        template <typename... U>
        constexpr bool operator<=(const Tuple<U...>& x) const requires(EqualityComparableWith<T, U> && ...)
        {
            using OtherBaseList = typename Tuple<U...>::BaseList;
            return _TupleLessEqual(*this, x, BaseList{}, OtherBaseList{});
        }

        template <typename... U>
        constexpr bool operator>(const Tuple<U...>& x) const requires(EqualityComparableWith<T, U> && ...)
        {
            using OtherBaseList = typename Tuple<U...>::BaseList;
            return _TupleLess(x, *this, OtherBaseList{}, BaseList{});
        }

        template <typename... U>
        constexpr bool operator>=(const Tuple<U...>& x) const requires(EqualityComparableWith<T, U> && ...)
        {
            using OtherBaseList = typename Tuple<U...>::BaseList;
            return _TupleLessEqual(x, *this, OtherBaseList{}, BaseList{});
        }

    private:
        template <typename U, typename... B1, typename... B2>
        constexpr void AssignInternal(U&& u, TypeList<B1...>, TypeList<B2...>)
        {
            // Working around an MSVC bug where assignment silently does nothing when using IdentityType<> here.
            // See: https://github.com/codeinred/tuplet/issues/29
            // See: https://developercommunity.visualstudio.com/t/fold-expressions-unreliable-in-171-with-c20/1676476
        #if HE_COMPILER_MSVC
            (void(B1::value = Forward<U>(u).B2::value), ...);
        #else
            (void(B1::value = Forward<U>(u).IdentityType<B2>::value), ...);
        #endif
        }
    };

    template <>
    struct Tuple<> : _TupleBase<>
    {
        static constexpr uint32_t Size = 0;
        using Super = _TupleBase<>;
        using BaseList = TypeList<>;
        using ElementList = TypeList<>;

        constexpr bool operator==(const Tuple&) const noexcept { return true; }
        constexpr bool operator<=(const Tuple&) const noexcept { return true; }
        constexpr bool operator>=(const Tuple&) const noexcept { return true; }
        constexpr bool operator!=(const Tuple&) const noexcept { return false; }
        constexpr bool operator<(const Tuple&) const noexcept { return false; }
        constexpr bool operator>(const Tuple&) const noexcept { return false; }
    };

    // Deduction guide
    template <typename... T>
    Tuple(T...) -> Tuple<Decay<T>...>;

    // --------------------------------------------------------------------------------------------
    // Utilities

    template <uint32_t I, typename T> requires(IsSpecialization<Decay<T>, Tuple>)
    using TupleElement = decltype(T::DeclElement(_TupleTag<I>{}));

    template <uint32_t I, typename T> requires(IsSpecialization<Decay<T>, Tuple> && I < Decay<T>::Size)
    [[nodiscard]] constexpr decltype(auto) TupleGet(T&& t) { return Forward<T>(t)[_TupleTag<I>{}]; }

    template <typename... T>
    [[nodiscard]] constexpr Tuple<T&...> Tie(T&... t) { return { t... }; }

    template <typename... Args>
    [[nodiscard]] constexpr auto MakeTuple(Args&&... args)
    {
        return Tuple<Decay<Args>...>{ Forward<Args>(args)... };
    }

    template <typename... Args>
    [[nodiscard]] constexpr auto ForwardAsTuple(Args&&... args) noexcept
    {
        return Tuple<Args&&...>{ Forward<Args>(args)... };
    }

    // Applies a function to every element of the tuple. The order is the
    // declaration order, so first the function will be applied to element
    // 0, then element 1, then element 2, and so on, where element N is
    // identified by get<N>
    template <typename T, typename F>
    constexpr void TupleForEach(T&& tuple, F&& func) noexcept
    {
        using BaseList = typename Decay<T>::BaseList;
        _TupleForEach(Forward<T>(tuple), Forward<F>(func), BaseList{});
    }

    // Applies a function to each element successively, until one returns a
    // truthy value. Returns true if any application returned a truthy
    // value, and false otherwise
    template <typename T, typename F>
    constexpr bool TupleAny(T&& tuple, F&&  func) noexcept
    {
        using BaseList = typename Decay<T>::BaseList;
        return _TupleAny(Forward<T>(tuple), Forward<F>(func), BaseList{});
    }

    // Applies a function to each element successively, until one returns a
    // falsy value. Returns true if every application returned a truthy
    // value, and false otherwise
    template <typename T, typename F>
    constexpr bool TupleAll(T&& tuple, F&&  func) noexcept
    {
        using BaseList = typename Decay<T>::BaseList;
        return _TupleAll(Forward<T>(tuple), Forward<F>(func), BaseList{});
    }

    // Invokes `func` with the tuple elements as arguments
    template <typename T, typename F>
    constexpr decltype(auto) TupleApply(T&& tuple, F&& func) noexcept
    {
        using BaseList = typename Decay<T>::BaseList;
        return _TupleApply(Forward<T>(tuple), Forward<F>(func), BaseList{});
    }
}
