# Copyright Chad Engler

id = "sqlite3"
name = "SQLite"
description = "SQLite is a C-language library that implements a small, fast, self-contained, high-reliability, full-featured, SQL database engine."
version = "3.36.0"
author = "Dwayne Hipp"
license = "blessing"
homepage = "https://www.sqlite.org/index.html"

[install]
    archive = "https://www.sqlite.org/2021/sqlite-amalgamation-3360000.zip"
    basepath = "sqlite-amalgamation-3360000"

[[modules]]
    name = "sqlite3"
    type = "static"
    group = "engine/contrib"
    warnings = "Off"
    files = ["sqlite3.c"]
    public_includedirs = ["."]
    public_defines = ["SQLITE_OMIT_DEPRECATED"]
    private_defines = [
        "SQLITE_DQS=0",
        "SQLITE_THREADSAFE=2",
        "SQLITE_DEFAULT_MEMSTATUS=0",
        "SQLITE_DEFAULT_WAL_SYNCHRONOUS=1",
        "SQLITE_LIKE_DOESNT_MATCH_BLOBS=1",
        "SQLITE_MAX_EXPR_DEPTH=0",
        "SQLITE_OMIT_DECLTYPE",
        "SQLITE_OMIT_PROGRESS_CALLBACK",
        "SQLITE_OMIT_SHARED_CACHE",
        "SQLITE_USE_ALLOCA",
    ]

    [[modules.variants]]
        conditions = ["system:linux"]
        public_dependson = ["sys:pthread", "sys:dl"]

    [[modules.variants]]
        conditions = ["tags:debug"]
        private_defines = ["SQLITE_DEBUG"]
