id = "sqlite3"
name = "SQLite"
description = "SQLite is a C-language library that implements a small, fast, self-contained, high-reliability, full-featured, SQL database engine."
version = "3.36.0"
author = "Dwayne Hipp"
license = "blessing"

[install]
    archive = "https://www.sqlite.org/2021/sqlite-amalgamation-3360000.zip"
    basepath = "sqlite-amalgamation-3360000"

[[modules]]
    name = "sqlite3"
    type = "static"
    group = "engine/contrib"
    warnings = "Off"
    files = ["sqlite3.c"]
    public_includedirs = ["."]

    [[modules.variants]]
        conditions = ["system:linux"]
        public_dependson = ["sys:pthread", "sys:dl"]
