// Copyright Chad Engler

#pragma once

#include "he/core/types.h"

namespace he::window
{
    using PointerId = uint32_t;

    constexpr PointerId PointerId_Mouse = 1;

    /// Enumeration of the types of supported pointer devices.
    enum class PointerKind : uint8_t
    {
        Mouse,  ///< The event was generated by a mouse device.
        Pen,    ///< The event was generated by a pen or stylus device.
        Touch,  ///< The event was generated by a touch, such as a finger.

        _Count,
    };

    /// Enumeration of the supported pointer buttons.
    enum class PointerButton : uint8_t
    {
        None,       ///< Special value representing no button
        Primary,    ///< Primary action: left mouse, pen contact with no buttons, touch contact
        Secondary,  ///< Secondary action: right mouse, pen contact with barrel button
        Auxiliary,  ///< Auxiliary action: middle mouse (wheel depresed)
        Extra1,     ///< Extra mouse button, usually the back button
        Extra2,     ///< Extra mouse button, usually the forward button
        Eraser,     ///< Pen Eraser button

        _Count,
    };

    /// Enumeration of the various supported cursor display modes.
    enum class PointerCursor : int32_t
    {
        None = -1,          ///< Special value representing no mouse cursor. This hides the cursor from display.
        Arrow = 0,          ///< The default "arrow" cursor
        Hand,               ///< Indicates something can be grabbed.
        NotAllowed,         ///< Indicates that an action is not available.
        TextInput,          ///< Indicates clicking here enabled text input.
        ResizeAll,          ///< Indicates the target can be resized in all directions.
        ResizeTopLeft,      ///< Indicates the target can be grown in the North-West direction.
        ResizeTopRight,     ///< Indicates the target can be grown in the North-East direction.
        ResizeBottomLeft,   ///< Indicates the target can be grown in the South-West direction.
        ResizeBottomRight,  ///< Indicates the target can be grown in the South-East direction.
        ResizeHorizontal,   ///< Indicates the target can be grown in West or East directions.
        ResizeVertical,     ///< Indicates the target can be grown in North or South directions.
        Wait,               ///< Indicates that work is happening and the user should wait.

        _Count,
    };
}
