# Copyright Chad Engler

id = "madler.zlib"
name = "Zlib Data Compression Library"
description = "Zlib is a general purpose data compression library."
version = "1.2.13"
authors = ["Mark Adler <madler@alumni.caltech.edu>"]
license = "Zlib"
homepage = "https://zlib.net/"

[install]
    github = "madler/zlib#v1.2.13"

[[modules]]
    name = "zlib"
    type = "static"
    group = "engine/contrib"
    warnings = "Off"
    files = ["*.h", "*.c"]
    private_defines = ["N_FSEEKO"]
    public_includedirs = ["."]

    [[modules.variants]]
        conditions = ["tags:debug"]
        public_defines = ["ZLIB_DEBUG"]

    [[modules.variants]]
        conditions = ["system:windows"]
        private_defines = ["_WINDOWS"]
