# Copyright Chad Engler

id = "jk-jeon.dragonbox"
name = "Dragonbox"
description = "Reference implementation of Dragonbox in C++"
version = "ccf48795c941e4e4d4d20168f8326ff2cd8fd424"
authors = ["Junekey Jeon"]
license = "BSL-1.0"
homepage = "https://github.com/jk-jeon/dragonbox"

[install]
    github = "jk-jeon/dragonbox#ccf48795c941e4e4d4d20168f8326ff2cd8fd424"

[[modules]]
    name = "dragonbox"
    type = "header"
    group = "engine/contrib"
    warnings = "Off"
    files = ["include/dragonbox/dragonbox.h"]
    public_includedirs = ["include"]
