# Copyright Chad Engler

id = "cameron314.concurrentqueue"
name = "moodycamel::ConcurrentQueue"
description = "A fast multi-producer, multi-consumer lock-free concurrent queue for C++11"
version = "d49fa2b0bd1c6185d93509f48c8987f9759d7238"
author = "Cameron <cameron@moodycamel.com>"
license = "BSD-2-Clause"
homepage = "https://github.com/cameron314/concurrentqueue"

[install]
    github = "cameron314/concurrentqueue#d49fa2b0bd1c6185d93509f48c8987f9759d7238" # after v1.0.3 to catch a warning fix

[[modules]]
    name = "concurrentqueue"
    type = "header"
    group = "engine/contrib"
    warnings = "Off"
    files = ["*.h"]
    public_includedirs = ["."]
