# Copyright Chad Engler

id = "WinPixEventRuntime"
name = "WinPixEventRuntime"
description = "Allows applications to be instrumented with marker events, for use with Microsoft PIX."
version = "1.0.230302001"
author = "Microsoft"
license = "SEE LICENSE IN license.txt"
homepage = "https://devblogs.microsoft.com/pix/winpixeventruntime/"

[install]
    nuget = "WinPixEventRuntime#1.0.230302001"
    valid_targets = ["windows"]

[[modules]]
    name = "WinPixEventRuntime"
    type = "shared"
    group = "engine/contrib"
    public_includedirs = ["Include/WinPixEventRuntime"]

    [[modules.variants]]
        conditions = ["system:windows", "architecture:x86_64"]
        public_dependson = [
            "file:bin/x64/WinPixEventRuntime.lib"
        ]
        copy_files = [
            "bin/x64/WinPixEventRuntime.dll",
        ]

    [[modules.variants]]
        conditions = ["system:windows", "architecture:ARM64"]
        public_dependson = [
            "file:bin/ARM64/WinPixEventRuntime.lib"
        ]
        copy_files = [
            "bin/ARM64/WinPixEventRuntime.dll",
        ]
