// Copyright Chad Engler

#include "he/schema/codegen.h"

#include "he/core/allocator.h"
#include "he/core/string_view.h"
#include "he/core/string_view_fmt.h"
#include "he/core/test.h"

using namespace he;
using namespace he::schema;

// ------------------------------------------------------------------------------------------------
HE_TEST(schema, GenerateCpp, test)
{
    Allocator& a = CrtAllocator::Get();
    CodeGenOptions options;
    CodeWriter writer(a);

    SchemaDef def(a);
    def.namespaceName = "testing";
    def.enums.EmplaceBack(a);
    def.enums[0].name = "Values";
    def.enums[0].base = BaseType::Int32;
    def.enums[0].values.EmplaceBack(a);
    def.enums[0].values[0].name = "Foo";
    def.structs.EmplaceBack(a);
    def.structs[0].name = "Test";
    def.structs[0].fields.EmplaceBack(a);
    def.structs[0].fields.EmplaceBack(a);
    def.structs[0].fields[0].name = "test";
    def.structs[0].fields[0].type.base = BaseType::Bool;
    def.structs[0].fields[0].defaultValue.basic.b = false;
    def.structs[0].fields[1].name = "test2";
    def.structs[0].fields[1].type.base = BaseType::Int16;
    def.structs[0].fields[1].defaultValue.basic.i16 = 6;

    const bool result = GenerateCpp(def, options, writer);
    HE_EXPECT(result);

    constexpr StringView Expected = R"(// Generated by the Harvest Schema compiler

#pragma once

#include "he/core/types.h"

namespace testing
{
    struct Test;

    enum class Values : int32_t
    {
        Foo = 0,
    };

    inline const char* AsString(Values value)
    {
        switch (value)
        {
            case Values::Foo: return "Foo";
        }
        return "<unknown>";
    }

    struct Test
    {
        static constexpr uint32_t TypeId = 0x652d741b;
        static constexpr uint32_t FieldId_test = 0x8432444f;
        static constexpr uint32_t FieldId_test2 = 0x9821d0c7;

        bool test{ false };
        int16_t test2{ 6 };
    };
}
)";

    HE_EXPECT_EQ(writer.Str(), Expected);
}
