# Copyright Chad Engler

id = "WebAssembly.binaryen"
name = "binaryen"
description = "Optimizer and compiler/toolchain library for WebAssembly"
version = "116"
authors = ["See: AUTHORS"]
license = "Apache-2.0"
homepage = "https://github.com/WebAssembly/binaryen"

[install]
    exec = "binaryen.lua"
    base_path = "binaryen-version_116"
    index_archive_by_host = true

    [install.archive]
        linux = "https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz"
        windows = "https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-windows.tar.gz"
