// Copyright Chad Engler

#include "codegen_cpp.h"

#include "he/core/file.h"
#include "he/core/path.h"
#include "he/core/enum_fmt.h"
#include "he/core/span_fmt.h"
#include "he/core/string.h"
#include "he/core/string_fmt.h"
#include "he/core/string_view.h"
#include "he/core/string_view_fmt.h"

namespace he::schema
{
    #define HE_ID_FMT "{:#018x}"

    constexpr const char ReaderSuffix[] = "::Reader";
    constexpr const char BuilderSuffix[] = "::Builder";

    CodeGenCpp::CodeGenCpp(const CodeGenRequest& request)
        : m_request(request)
        , m_root(m_request.schemaFile.Root())
    {
        for (char ch : m_root.Name())
        {
            if (ch == '.')
                m_namespaceName += "::";
            else
                m_namespaceName += ch;
        }
    }

    bool CodeGenCpp::Generate()
    {
        m_writer.Reserve(16384); // 16 KB

        GenHeader();
        if (!FlushToFile(".hsc.h"))
            return false;

        m_writer.Clear();

        GenSource();
        if (!FlushToFile(".hsc.cpp"))
            return false;

        m_writer.Clear();

        return true;
    }

    void CodeGenCpp::GenHeader()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");
        m_writer.WriteLine("#pragma once\n");
        m_writer.WriteLine("#include \"he/core/assert.h\"");
        m_writer.WriteLine("#include \"he/core/string_view.h\"");
        m_writer.WriteLine("#include \"he/core/types.h\"");
        m_writer.WriteLine("#include \"he/schema/layout.h\"");
        m_writer.WriteLine("#include \"he/schema/types.h\"\n");

        bool hasUserInclude = false;
        for (String::Reader importStr : m_root.Data().File().Imports())
        {
            if (importStr.IsEmpty())
                continue;

            hasUserInclude = true;
            m_writer.WriteLine("#include \"{}.h\"", importStr.AsView());
        }

        if (hasUserInclude)
            m_writer.Write('\n');

        WriteDeclInfo(m_root);
        m_writer.Write('\n');

        if (!m_namespaceName.IsEmpty())
        {
            m_writer.WriteLine("namespace {}", m_namespaceName);
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
        }

        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Type Declarations\n");
        for (Declaration::Reader decl : m_root.Children())
        {
            WriteDecl(decl, m_root);
        }

        m_writer.Write('\n');
        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Reader & Builder Declarations\n");
        for (Declaration::Reader decl : m_root.Children())
        {
            WriteImpl(decl, m_root);
        }

        m_writer.Write('\n');
        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Reader & Builder Field Definitions");
        for (Declaration::Reader decl : m_root.Children())
        {
            WriteFieldImpl(decl, m_root);
        }

        // Close the namespace
        if (!m_namespaceName.IsEmpty())
        {
            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        m_writer.Write('\n');
    }

    void CodeGenCpp::WriteDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        switch (decl.Data().Tag())
        {
            case Declaration::Data::Tag::File:
                break;
            case Declaration::Data::Tag::Attribute:
                WriteAttributeDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Constant:
                WriteConstDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Enum:
                WriteEnumDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Interface:
                WriteInterfaceDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Struct:
                WriteStructDecl(decl, scope);
                break;
        }
    }

    void CodeGenCpp::WriteAttributeDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsAttribute());
        m_writer.WriteLine("struct {} {{ using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">; }};", decl.Name().AsView(), decl.Id());
    }

    void CodeGenCpp::WriteConstDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsConstant());
        Declaration::Data::Constant::Reader constDecl = decl.Data().Constant();

        m_writer.WriteIndent();
        if (decl.ParentId() != m_root.Id())
            m_writer.Write("static ");

        Type::Reader type = constDecl.Type();
        Type::Data::Reader typeData = type.Data();
        const bool isInline = typeData.IsBool() || typeData.IsEnum() || typeData.IsString() || IsArithmetic(typeData.Tag());

        if (isInline)
            m_writer.Write("inline constexpr ");
        else
            m_writer.Write("extern const ");

        if (typeData.IsString())
            m_writer.Write("char");
        else
            WriteType(type, scope, ReaderSuffix);

        m_writer.Write(' ');
        m_writer.Write(decl.Name().AsView());

        if (typeData.IsArray())
            m_writer.Write("[{}]", typeData.Array().Size());
        else if (typeData.IsString())
            m_writer.Write("[]");

        if (isInline)
        {
            m_writer.Write(" = ");
            WriteDataValue(type, scope, constDecl.Value());
        }

        m_writer.Write(";\n");
    }

    void CodeGenCpp::WriteEnumDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsEnum());
        Declaration::Data::Enum::Reader enumDecl = decl.Data().Enum();

        m_writer.WriteLine("enum class {} : uint16_t", decl.Name().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (Enumerator::Reader e : enumDecl.Enumerators())
        {
            m_writer.WriteLine("{} = {},", e.Name().AsView(), e.Ordinal());
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteInterfaceDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsInterface());

        m_writer.WriteLine("class {};", decl.Name().AsView());
    }

    void CodeGenCpp::WriteStructDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        WriteTemplate(decl);
        m_writer.WriteLine("struct {} final", decl.Name().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{}() = delete;", decl.Name().AsView());
        m_writer.WriteLine("using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">;\n", decl.Id());

        m_writer.WriteLine("class Reader;");
        m_writer.WriteLine("class Builder;");

        for (Declaration::Reader child : decl.Children())
        {
            m_writer.Write('\n');
            WriteDecl(child, decl);
        }

        if (structDecl.IsUnion())
        {
            m_writer.WriteLine("enum class Tag : uint16_t");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            he::String upperCamelName(Allocator::GetTemp());
            for (Field::Reader field : structDecl.Fields())
            {
                upperCamelName = field.Name();
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteLine("{} = {},", upperCamelName, field.UnionTag());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        switch (decl.Data().Tag())
        {
            case Declaration::Data::Tag::File:
            case Declaration::Data::Tag::Attribute:
            case Declaration::Data::Tag::Constant:
            case Declaration::Data::Tag::Enum:
                break;
            case Declaration::Data::Tag::Interface:
                WriteInterfaceImpl(decl, scope);
                break;
            case Declaration::Data::Tag::Struct:
                WriteStructImpl(decl, scope);
                break;
        }
    }

    void CodeGenCpp::WriteInterfaceImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsInterface());
        Declaration::Data::Interface::Reader interfaceDecl = decl.Data().Interface();

        for (Declaration::Reader child : decl.Children())
        {
            WriteImpl(child, scope);
        }

        WriteTemplate(decl);
        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);

        Type::Data::Reader superTypeData = interfaceDecl.Super().Data();
        Type::Data::Interface::Reader superInterface = superTypeData.IsInterface() ? superTypeData.Interface() : Type::Data::Interface::Reader{};

        if (superInterface.IsValid())
        {
            Declaration::Reader super = m_request.GetDecl(superInterface.Id());
            m_writer.Write(" : public ");
            WriteName(super, scope, superInterface.Brand(), ReaderSuffix);
        }
        m_writer.Write('\n');
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("virtual ~{}() {{}}", decl.Name().AsView());
        m_writer.WriteLine("using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">;", decl.Id());
        if (superInterface.IsValid())
        {
            Declaration::Reader super = m_request.GetDecl(superInterface.Id());
            m_writer.WriteIndent();
            m_writer.Write("using SuperType = ");
            WriteName(super, scope, superInterface.Brand(), ReaderSuffix);
            m_writer.Write(";\n");
        }
        m_writer.Write('\n');

        for (Declaration::Reader child : decl.Children())
        {
            WriteDecl(child, decl);
        }

        for (Method::Reader method : interfaceDecl.Methods())
        {
            Declaration::Reader params = m_request.GetDecl(method.ParamStruct());
            Declaration::Reader result = m_request.GetDecl(method.ResultStruct());
            m_writer.WriteLine("virtual {}::Reader {}({}::Reader) = 0;", result.Name().AsView(), method.Name().AsView(), params.Name().AsView());
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteStructImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        for (Declaration::Reader child : decl.Children())
        {
            WriteImpl(child, scope);
        }

        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write("::Reader final : public ::he::schema::StructReader\n");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteIndent();
        m_writer.Write("using StructType = ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write(";\n");
        m_writer.WriteLine("using SuperType = ::he::schema::StructReader;\n");

        if (structDecl.IsUnion())
        {
            m_writer.WriteLine("Tag Tag() const {{ return SuperType::GetDataField<enum Tag>({}); }}\n", structDecl.UnionTagOffset());
        }

        for (Field::Reader field : structDecl.Fields())
        {
            WriteFieldGetDecl(field, decl, true);
            m_writer.Write('\n');
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");

        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write("::Builder final : public ::he::schema::StructBuilder\n");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteIndent();
        m_writer.Write("using StructType = ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write(";\n");

        m_writer.WriteLine("using SuperType = ::he::schema::StructBuilder;\n");
        m_writer.WriteLine("StructType::Reader AsReader() const { return StructType::Reader(SuperType::AsReader()); }");
        m_writer.WriteLine("operator StructType::Reader() const { return AsReader(); }");

        if (structDecl.IsUnion())
        {
            m_writer.Write('\n');
            m_writer.WriteLine("Tag Tag() const {{ return SuperType::GetDataField<enum Tag>({}); }}\n", structDecl.UnionTagOffset());
            m_writer.WriteLine("void SetTag(enum Tag t) {{ return SuperType::SetDataField({}, t); }}", structDecl.UnionTagOffset());
        }

        for (Field::Reader field : structDecl.Fields())
        {
            m_writer.Write('\n');
            WriteFieldGetDecl(field, decl, false);
            WriteFieldSetDecl(field, decl);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteFieldImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        for (Declaration::Reader child : decl.Children())
        {
            WriteFieldImpl(child, scope);
        }

        if (!decl.Data().IsStruct())
            return;

        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        for (Field::Reader field : structDecl.Fields())
        {
            m_writer.Write('\n');
            WriteFieldGetImpl(field, decl, scope, true);
        }

        for (Field::Reader field : structDecl.Fields())
        {
            m_writer.Write('\n');
            WriteFieldGetImpl(field, decl, scope, false);
            WriteFieldSetImpl(field, decl, scope);
        }
    }

    void CodeGenCpp::WriteFieldGetDecl(Field::Reader field, Declaration::Reader decl, bool isReader)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        const char* suffix = isReader ? ReaderSuffix : BuilderSuffix;

        if (structDecl.IsUnion())
        {
            m_writer.WriteLine("bool Is{}() const;", upperCamelName);
        }

        if (field.Meta().IsUnion() || field.Meta().IsGroup())
        {
            m_writer.WriteLine("{0}{1} {0}() const;", upperCamelName, suffix);
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();

        if (fieldTypeData.IsVoid())
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName, field.Meta().Normal().Index());
            m_writer.WriteLine("::he::schema::Void {}() const;", upperCamelName);
        }
        else if (IsPointer(fieldType))
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName);

            m_writer.WriteIndent();
            WriteType(fieldType, decl, suffix);
            m_writer.Write(" {}() const;\n", upperCamelName);
        }
        else
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName);

            const bool isArray = fieldTypeData.IsArray();

            m_writer.WriteIndent();
            if (isArray)
            {
                m_writer.Write("::he::Span<");
                if (isReader)
                    m_writer.Write("const ");
                WriteType(fieldTypeData.Array().ElementType(), decl, nullptr);
                m_writer.Write(">");
            }
            else
            {
                WriteType(fieldType, decl, nullptr);
            }
            m_writer.Write(" {}() const;\n", upperCamelName);
        }
    }

    void CodeGenCpp::WriteFieldGetImpl(Field::Reader field, Declaration::Reader decl, Declaration::Reader scope, bool isReader)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        const char* suffix = isReader ? ReaderSuffix : BuilderSuffix;

        if (structDecl.IsUnion())
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, m_root, {}, suffix);
            m_writer.Write("{0}::Is{1}() const {{ return Tag() == Tag::{1}; }}\n", suffix, upperCamelName);
        }

        if (field.Meta().IsGroup() || field.Meta().IsUnion())
        {
            TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
            Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteName(groupType, scope, {}, suffix);
            m_writer.Write(suffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);
            m_writer.Write("return {}{}(*this); }}\n", upperCamelName, suffix);
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();

        if (fieldTypeData.IsVoid())
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return false; }}\n", suffix, upperCamelName);

            m_writer.WriteIndent();
            m_writer.Write("inline ::he::schema::Void ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);
            m_writer.Write("return {}; }\n");
        }
        else if (IsPointer(fieldType))
        {

            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("Is{0}() && ", upperCamelName);
            m_writer.Write("SuperType::HasPointerField({}); }}\n", norm.Index());

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteType(fieldType, scope, suffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);

            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            const bool isArray = fieldTypeData.IsArray();
            const bool hasDefault = isReader && norm.HasDefaultValue();

            if (isArray)
            {
                m_writer.Write("return SuperType::TryGetPointerArrayField<");
                WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
                m_writer.Write(">({}, {}", norm.Index(), fieldTypeData.Array().Size());
                if (hasDefault)
                    m_writer.Write(", ");
            }
            else
            {
                const Type::Data::Tag getterKind = fieldTypeData.IsBlob() ? Type::Data::Tag::List : fieldTypeData.Tag();
                m_writer.Write("return SuperType::GetPointerField({}).TryGet{}", norm.Index(), getterKind);
                if (fieldTypeData.IsBlob())
                {
                    m_writer.Write("<uint8_t>");
                }
                else if (!fieldTypeData.IsString())
                {
                    Type::Reader t = fieldTypeData.IsList() ? fieldTypeData.List().ElementType() : norm.Type();
                    if (IsPointer(t))
                        m_writer.Write("<struct ");
                    else
                        m_writer.Write("<");
                    WriteType(t, scope, nullptr);
                    m_writer.Write('>');
                }
                m_writer.Write('(');
            }
            if (hasDefault)
            {
                const ptrdiff_t offset = GetDefaultValueOffset(norm.DefaultValue());
                if (offset > 0)
                {
                    m_writer.Write("::he::schema::DeclInfo<" HE_ID_FMT ">::RawSchema + {}", m_root.Id(), offset);
                }
            }
            m_writer.Write("); }\n");
        }
        else
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("Is{0}() && ", upperCamelName);
            m_writer.Write("SuperType::HasDataField({}); }}\n", norm.Index());

            const bool isArray = fieldTypeData.IsArray();
            const bool hasDefault = (isReader || !isArray) && norm.HasDefaultValue();

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            if (isArray)
            {
                m_writer.Write("::he::Span<");
                if (isReader)
                    m_writer.Write("const ");
                WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
                m_writer.Write("> ");
            }
            else
            {
                WriteType(fieldType, scope, nullptr);
                m_writer.Write(' ');
            }
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);

            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            if (isArray)
            {
                if (hasDefault)
                {
                    m_writer.Write("static const ");
                    WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
                    m_writer.Write(" DefaultValue_{}[]", upperCamelName);
                    WriteDataValue(fieldType, decl, norm.DefaultValue());
                    m_writer.Write("; ");
                }
                m_writer.Write("return SuperType::TryGetDataArrayField<");
                WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
            }
            else
            {
                m_writer.Write("return SuperType::TryGetDataField<{}", fieldTypeData.IsEnum() ? "enum " : "");
                WriteType(fieldType, scope, nullptr);
            }
            m_writer.Write(">({}, {}", norm.Index(), norm.DataOffset());
            if (isArray)
            {
                m_writer.Write(", {}", fieldTypeData.Array().Size());
                if (hasDefault)
                {
                    m_writer.Write(", DefaultValue_{}", upperCamelName);
                }
            }
            else if (hasDefault)
            {
                m_writer.Write(", ");
                WriteDataValue(norm.Type(), decl, norm.DefaultValue());
            }
            m_writer.Write("); }\n");
        }
    }

    void CodeGenCpp::WriteFieldSetDecl(Field::Reader field, Declaration::Reader decl)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        if (field.Meta().IsGroup() || field.Meta().IsUnion())
        {
            if (structDecl.IsUnion())
            {
                TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                m_writer.WriteIndent();
                WriteName(groupType, decl, {}, BuilderSuffix);
                m_writer.Write(BuilderSuffix);
                m_writer.Write(' ');
                m_writer.Write("Init{}();\n", upperCamelName);
            }
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();
        const bool fieldIsPointer = IsPointer(fieldType);

        m_writer.WriteIndent();
        m_writer.Write("void Set{}(", upperCamelName);
        if (!fieldTypeData.IsVoid())
        {
            WriteType(fieldType, decl, ReaderSuffix);
            m_writer.Write(" value");
        }
        m_writer.Write(");\n");

        if (fieldIsPointer)
        {
            const bool fieldIsString = fieldTypeData.IsString();
            const bool fieldIsList = fieldTypeData.IsList() || fieldTypeData.IsBlob();

            m_writer.WriteIndent();
            WriteType(fieldType, decl, BuilderSuffix);
            m_writer.Write(" Init{}(", upperCamelName);
            if (fieldIsList)
                m_writer.Write("uint32_t size");
            else if (fieldIsString)
                m_writer.Write("::he::StringView str");
            m_writer.Write(");\n");
        }
    }

    void CodeGenCpp::WriteFieldSetImpl(Field::Reader field, Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        if (field.Meta().IsGroup() || field.Meta().IsUnion())
        {
            if (structDecl.IsUnion())
            {
                TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                m_writer.WriteIndent();
                m_writer.Write("inline ");
                WriteName(groupType, scope, {}, BuilderSuffix);
                m_writer.Write(BuilderSuffix);
                m_writer.Write(' ');
                WriteName(decl, scope, {}, BuilderSuffix);
                m_writer.Write("::Builder::Init{0}() {{ SetTag(Tag::{0}); ", upperCamelName);
                if (field.Meta().IsGroup())
                {
                    WriteGroupFieldClear(groupType, decl);
                }
                m_writer.Write("return {}{}(*this); }}\n", upperCamelName, BuilderSuffix);
            }
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();
        const bool fieldIsPointer = IsPointer(fieldType);

        m_writer.WriteIndent();
        m_writer.Write("inline void ");
        WriteName(decl, scope, {}, BuilderSuffix);
        m_writer.Write("::Builder::Set{}(", upperCamelName);
        if (!fieldTypeData.IsVoid())
        {
            WriteType(fieldType, scope, ReaderSuffix);
            m_writer.Write(" value");
        }
        m_writer.Write(") { ");
        if (structDecl.IsUnion())
            m_writer.Write("SetTag(Tag::{}); ", upperCamelName);
        if (fieldIsPointer)
        {
            m_writer.Write("SuperType::GetPointerField({}).Set(value); ", norm.Index());
        }
        else if (!fieldTypeData.IsVoid())
        {
            m_writer.Write("SuperType::SetDataField<{}", fieldTypeData.IsEnum() ? "enum " : "");
            WriteType(fieldType, scope, nullptr);
            m_writer.Write(">({}, {}, value); ", norm.Index(), norm.DataOffset());
        }
        m_writer.Write("}\n");

        if (fieldIsPointer)
        {
            const bool fieldIsString = fieldTypeData.IsString();
            const bool fieldIsList = fieldTypeData.IsList() || fieldTypeData.IsBlob();

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteType(fieldType, scope, BuilderSuffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, BuilderSuffix);
            m_writer.Write("::Builder::Init{}(", upperCamelName);
            if (fieldIsList)
                m_writer.Write("uint32_t size");
            else if (fieldIsString)
                m_writer.Write("::he::StringView str");
            m_writer.Write(") { ");
            if (structDecl.IsUnion())
                m_writer.Write("SetTag(Tag::{}); ", upperCamelName);

            const Type::Data::Tag getterKind = fieldTypeData.IsBlob() ? Type::Data::Tag::List : fieldTypeData.Tag();
            m_writer.Write("auto v = m_builder->Add{}", getterKind);
            if (fieldTypeData.IsBlob())
            {
                m_writer.Write("<uint8_t>");
            }
            else if (!fieldTypeData.IsString())
            {
                Type::Reader t = fieldTypeData.IsList() ? fieldTypeData.List().ElementType() : fieldType;
                if (IsPointer(t))
                    m_writer.Write("<struct ");
                else
                    m_writer.Write("<");
                WriteType(t, scope, nullptr);
                m_writer.Write('>');
            }
            m_writer.Write('(');
            if (fieldIsList)
                m_writer.Write("size");
            else if (fieldIsString)
                m_writer.Write("str");
            m_writer.Write("); SuperType::GetPointerField({}).Set(v); return v; }}\n", norm.Index());
        }
    }

    void CodeGenCpp::WriteGroupFieldClear(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        for (Field::Reader field : structDecl.Fields())
        {
            if (field.Meta().IsGroup() || field.Meta().IsUnion())
            {
                TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                WriteGroupFieldClear(groupType, scope);
                continue;
            }

            he::String upperCamelName(field.Name(), Allocator::GetTemp());
            upperCamelName[0] = ToUpper(upperCamelName[0]);

            Field::Meta::Normal::Reader norm = field.Meta().Normal();
            Type::Reader fieldType = norm.Type();
            Type::Data::Reader fieldTypeData = fieldType.Data();
            const bool fieldIsPointer = IsPointer(fieldType);

            if (fieldIsPointer)
            {
                m_writer.Write("SuperType::ClearPointerField({}); ", norm.Index());
            }
            else
            {
                m_writer.Write("SuperType::ClearDataField({}); ", norm.Index());
            }
        }
    }

    void CodeGenCpp::GenSource()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");

        // headers
        StringView baseName = GetPathWithoutExtension(m_request.fileName);
        m_writer.WriteLine("#include \"{}.hsc.h\"\n", baseName);
        m_writer.WriteLine("#include \"he/core/types.h\"\n", baseName);

        m_writer.WriteLine("namespace he::schema");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        WriteRawSchemaData();
        WriteDeclInfoSrc(m_root);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::WriteRawSchemaData()
    {
        m_writer.WriteLine("static const Word RawFileSchema[] =");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();
        m_writer.WriteIndent();
        const uint32_t size = m_request.schemaData.Size();
        for (uint32_t i = 0; i < size; ++i)
        {
            if (i > 0)
            {
                if ((i % 10) == 0)
                {
                    m_writer.Write('\n');
                    m_writer.WriteIndent();
                }
                else
                {
                    m_writer.Write(' ');
                }
            }
            m_writer.Write("{:#018x}ull,", m_request.schemaData[i]);
        }
        m_writer.Write('\n');
        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");
    }

    void CodeGenCpp::WriteDeclInfoSrc(Declaration::Reader decl)
    {
        const ptrdiff_t schemaOffset = static_cast<StructReader&>(decl).Data() - m_request.schemaData.Data();

        m_writer.WriteLine("const Word* DeclInfo<" HE_ID_FMT ">::RawSchema = RawFileSchema + {};", decl.Id(), schemaOffset);

        for (Declaration::Reader child : decl.Children())
        {
            WriteDeclInfoSrc(child);
        }
    }

    bool CodeGenCpp::FlushToFile(const char* suffix)
    {
        he::String filePath(m_request.outDir, Allocator::GetTemp());
        ConcatPath(filePath, m_request.fileName);
        RemoveExtension(filePath);
        filePath += suffix;

        const StringView code = m_writer.Str();

        File f;
        if (!f.Open(filePath.Data(), FileOpenMode::WriteTruncate))
            return false;

        if (!f.Write(code.Data(), code.Size()))
            return false;

        return true;
    }

    void CodeGenCpp::WriteDeclInfo(Declaration::Reader decl)
    {
        const bool isStruct = decl.Data().IsStruct();
        const uint16_t dataFieldCount = isStruct ? decl.Data().Struct().DataFieldCount() : 0;
        const uint16_t dataWordSize = isStruct ? decl.Data().Struct().DataWordSize() : 0;
        const uint16_t pointerCount = isStruct ? decl.Data().Struct().PointerCount() : 0;

        m_writer.WriteIndent();
        m_writer.Write("HE_SCHEMA_DECL_INFO(" HE_ID_FMT ", " HE_ID_FMT ", {}, {}, {}, {}); // ",
            decl.Id(), decl.ParentId(), decl.Data().Tag(), dataFieldCount, dataWordSize, pointerCount);
        if (decl.Data().IsFile())
            m_writer.Write("file");
        else
            WriteName(decl, m_root, {}, nullptr);
        m_writer.Write('\n');

        for (Declaration::Reader child : decl.Children())
        {
            WriteDeclInfo(child);
        }
    }

    void CodeGenCpp::WriteName(Declaration::Reader decl, Declaration::Reader scope, Brand::Reader brand, const char* pointerSuffix)
    {
        if (decl.ParentId() != scope.Id() && decl.ParentId() != scope.ParentId())
        {
            Declaration::Reader parent = m_request.GetDecl(decl.ParentId());
            if (!parent.Data().IsFile())
            {
                WriteName(parent, scope, brand, pointerSuffix);
                m_writer.Write("::");
            }
        }

        m_writer.Write(decl.Name());

        for (Brand::Scope::Reader brandScope : brand.Scopes())
        {
            if (brandScope.ScopeId() == decl.Id())
            {
                List<Type>::Reader params = brandScope.Params();

                m_writer.Write("<");
                for (uint32_t i = 0; i < params.Size(); ++i)
                {
                    Type::Reader t = params[i];
                    WriteType(t, scope, pointerSuffix);
                    if (i < (params.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(">");
                break;
            }
        }
    }

    void CodeGenCpp::WriteTemplate(Declaration::Reader decl)
    {
        List<String>::Reader typeParams = decl.TypeParams();

        if (typeParams.IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("template <");
        for (uint32_t i = 0; i < typeParams.Size(); ++i)
        {
            m_writer.Write("typename ");
            m_writer.Write(typeParams[i]);
            if (i < (typeParams.Size() - 1))
                m_writer.Write(", ");
        }
        m_writer.Write(">\n");
    }

    void CodeGenCpp::WriteType(Type::Reader type, Declaration::Reader scope, const char* pointerSuffix)
    {
        switch (type.Data().Tag())
        {
            case Type::Data::Tag::Void: m_writer.Write("::he::schema::Void"); break;
            case Type::Data::Tag::Bool: m_writer.Write("bool"); break;
            case Type::Data::Tag::Int8: m_writer.Write("int8_t"); break;
            case Type::Data::Tag::Int16: m_writer.Write("int16_t"); break;
            case Type::Data::Tag::Int32: m_writer.Write("int32_t"); break;
            case Type::Data::Tag::Int64: m_writer.Write("int64_t"); break;
            case Type::Data::Tag::Uint8: m_writer.Write("uint8_t"); break;
            case Type::Data::Tag::Uint16: m_writer.Write("uint16_t"); break;
            case Type::Data::Tag::Uint32: m_writer.Write("uint32_t"); break;
            case Type::Data::Tag::Uint64: m_writer.Write("uint64_t"); break;
            case Type::Data::Tag::Float32: m_writer.Write("float"); break;
            case Type::Data::Tag::Float64: m_writer.Write("double"); break;
            case Type::Data::Tag::Array:
            {
                Type::Data::Array::Reader arrayType = type.Data().Array();
                if (IsPointer(arrayType.ElementType()))
                {
                    m_writer.Write("::he::schema::List<");
                    WriteType(arrayType.ElementType(), scope, nullptr);
                    m_writer.Write(">");
                }
                else
                {
                    m_writer.Write("::he::Span<const ");
                    WriteType(arrayType.ElementType(), scope, nullptr);
                    m_writer.Write(">");
                }
                break;
            }
            case Type::Data::Tag::Blob:
                m_writer.Write("::he::schema::List<uint8_t>");
                break;
            case Type::Data::Tag::String:
                m_writer.Write("::he::schema::String");
                break;
            case Type::Data::Tag::List:
            {
                Type::Data::List::Reader listType = type.Data().List();
                m_writer.Write("::he::schema::List<");
                WriteType(listType.ElementType(), scope, nullptr);
                m_writer.Write(">");
                break;
            }
            case Type::Data::Tag::Enum:
            {
                Type::Data::Enum::Reader enumType = type.Data().Enum();
                Declaration::Reader decl = m_request.GetDecl(enumType.Id());
                HE_ASSERT(decl.Data().IsEnum());
                WriteName(decl, scope, enumType.Brand(), nullptr);
                break;
            }
            case Type::Data::Tag::Struct:
            {
                Type::Data::Struct::Reader structType = type.Data().Struct();
                Declaration::Reader decl = m_request.GetDecl(structType.Id());
                HE_ASSERT(decl.Data().IsStruct());
                WriteName(decl, scope, structType.Brand(), nullptr);
                break;
            }
            case Type::Data::Tag::Interface:
            {
                Type::Data::Interface::Reader interfaceType = type.Data().Interface();
                Declaration::Reader decl = m_request.GetDecl(interfaceType.Id());
                HE_ASSERT(decl.Data().IsInterface());
                WriteName(decl, scope, interfaceType.Brand(), nullptr);
                break;
            }
            case Type::Data::Tag::AnyPointer:
            {
                Type::Data::AnyPointer::Reader anyType = type.Data().AnyPointer();

                if (anyType.ParamScopeId() == 0)
                {
                    m_writer.Write("AnyPointer");
                }
                else
                {
                    Declaration::Reader decl = m_request.GetDecl(anyType.ParamScopeId());
                    m_writer.Write(decl.TypeParams()[anyType.ParamIndex()]);
                }
                break;
            }
        }

        if (pointerSuffix && IsPointer(type))
        {
            m_writer.Write(pointerSuffix);
        }
    }

    void CodeGenCpp::WriteDataValue(Type::Reader type, Declaration::Reader scope, Value::Reader value)
    {
        switch (value.Data().Tag())
        {
            case Value::Data::Tag::Void: m_writer.Write("{}"); break;
            case Value::Data::Tag::Bool: m_writer.Write("{}", value.Data().Bool()); break;
            case Value::Data::Tag::Int8: m_writer.Write("{}", value.Data().Int8()); break;
            case Value::Data::Tag::Int16: m_writer.Write("{}", value.Data().Int16()); break;
            case Value::Data::Tag::Int32: m_writer.Write("{}", value.Data().Int32()); break;
            case Value::Data::Tag::Int64: m_writer.Write("{}", value.Data().Int64()); break;
            case Value::Data::Tag::Uint8: m_writer.Write("{}", value.Data().Uint8()); break;
            case Value::Data::Tag::Uint16: m_writer.Write("{}", value.Data().Uint16()); break;
            case Value::Data::Tag::Uint32: m_writer.Write("{}", value.Data().Uint32()); break;
            case Value::Data::Tag::Uint64: m_writer.Write("{}", value.Data().Uint64()); break;
            case Value::Data::Tag::Float32: m_writer.Write("{}", value.Data().Float32()); break;
            case Value::Data::Tag::Float64: m_writer.Write("{}", value.Data().Float64()); break;
            case Value::Data::Tag::Array:
            {
                HE_ASSERT(type.Data().IsArray());
                Type::Reader elementType = type.Data().Array().ElementType();
                List<Value>::Reader arrayValues = value.Data().Array();

                m_writer.Write("{ ");
                for (uint32_t i = 0; i < arrayValues.Size(); ++i)
                {
                    WriteDataValue(elementType, scope, arrayValues[i]);
                    if (i < (arrayValues.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(" }");
                break;
            }
            case Value::Data::Tag::Enum:
            {
                HE_ASSERT(type.Data().IsEnum());
                Type::Data::Enum::Reader enumType = type.Data().Enum();
                Declaration::Reader decl = m_request.GetDecl(enumType.Id());

                HE_ASSERT(decl.Data().IsEnum());
                Declaration::Data::Enum::Reader enumDecl = decl.Data().Enum();

                WriteName(decl, scope, enumType.Brand(), nullptr);
                m_writer.Write("::");
                for (Enumerator::Reader e : enumDecl.Enumerators())
                {
                    if (e.Ordinal() == value.Data().Enum())
                    {
                        m_writer.Write(e.Name());
                        break;
                    }
                }
                break;
            }
            case Value::Data::Tag::String:
            {
                // Technically a pointer value, but sometimes we use it like a data value (like for constants).
                HE_ASSERT(type.Data().IsString());
                String::Reader str = value.Data().String();
                m_writer.Write("\"{}\"", str.AsView());
                break;
            }
            case Value::Data::Tag::Blob:
            case Value::Data::Tag::List:
            case Value::Data::Tag::Tuple:
            case Value::Data::Tag::Interface:
            case Value::Data::Tag::AnyPointer:
                HE_ASSERT(false, "Invalid value kind. Expected a non-pointer value.");
                break;
        }
    }

    void CodeGenCpp::WriteWithReplace(StringView input, char what, StringView with)
    {
        for (char ch : input)
        {
            if (ch == what)
            {
                m_writer.Write(with);
            }
            else
            {
                m_writer.Write(ch);
            }
        }
    }

    ptrdiff_t CodeGenCpp::GetDefaultValueOffset(Value::Reader value)
    {
        // Maybe: One builder per struct named Defaults_declId and output here is "Defaults_declId + OFFSET"
        Value::Data::Reader valueData = value.Data();
        const Word* rootPtr = static_cast<const StructReader&>(m_root).Data();

        switch (valueData.Tag())
        {
            case Value::Data::Tag::Blob:
            {
                ListReader list = valueData.Array();
                return list.Data() - rootPtr;
            }
            case Value::Data::Tag::String:
            {
                ListReader list = valueData.String();
                return list.Data() - rootPtr;
            }
            case Value::Data::Tag::Array:
            {
                ListReader list = valueData.Array();
                return list.Data() - rootPtr;
            }
            case Value::Data::Tag::List:
            {
                ListReader list = valueData.List();
                return list.Data() - rootPtr;
            }
            case Value::Data::Tag::Tuple:
            {
                // TODO: Create the struct here? Change compiler to remove Tuple and create real structs?
                break;
            }
            case Value::Data::Tag::Void:
            case Value::Data::Tag::Bool:
            case Value::Data::Tag::Int8:
            case Value::Data::Tag::Int16:
            case Value::Data::Tag::Int32:
            case Value::Data::Tag::Int64:
            case Value::Data::Tag::Uint8:
            case Value::Data::Tag::Uint16:
            case Value::Data::Tag::Uint32:
            case Value::Data::Tag::Uint64:
            case Value::Data::Tag::Float32:
            case Value::Data::Tag::Float64:
            case Value::Data::Tag::Enum:
                HE_ASSERT(false, "Invalid value kind. Expected a pointer value.");
                break;

            case Value::Data::Tag::Interface:
                HE_ASSERT(false, "Invalid value kind. Interface cannot have a default value.");
                break;

            case Value::Data::Tag::AnyPointer:
                HE_ASSERT(false, "Invalid value kind. AnyPointer cannot have a default value.");
                break;
        }

        return 0;
    }

    bool GenerateCpp(const CodeGenRequest& request)
    {
        CodeGenCpp generator(request);
        if (!generator.Generate())
            return false;

        return true;
    }
}
;
