// Copyright Chad Engler

#include "codegen_cpp.h"

#include "he/core/file.h"
#include "he/core/path.h"
#include "he/core/enum_fmt.h"
#include "he/core/span_fmt.h"
#include "he/core/string.h"
#include "he/core/string_fmt.h"
#include "he/core/string_view.h"
#include "he/core/string_view_fmt.h"

namespace he::schema
{
    #define HE_ID_FMT "{:#018x}"

    constexpr const char ReaderSuffix[] = "::Reader";
    constexpr const char BuilderSuffix[] = "::Builder";

    CodeGenCpp::CodeGenCpp(const CodeGenRequest& request)
        : m_request(request)
        , m_root(m_request.schemaFile.Root())
    {
        for (char ch : m_root.Name())
        {
            if (ch == '.')
                m_namespaceName += "::";
            else
                m_namespaceName += ch;
        }
    }

    bool CodeGenCpp::Generate()
    {
        m_writer.Reserve(16384); // 16 KB

        GenHeader();
        if (!FlushToFile(".hsc.h"))
            return false;

        m_writer.Clear();

        GenSource();
        if (!FlushToFile(".hsc.cpp"))
            return false;

        m_writer.Clear();

        return true;
    }

    void CodeGenCpp::GenHeader()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");
        m_writer.WriteLine("#pragma once\n");
        m_writer.WriteLine("#include \"he/core/assert.h\"");
        m_writer.WriteLine("#include \"he/core/string_view.h\"");
        m_writer.WriteLine("#include \"he/core/types.h\"");
        m_writer.WriteLine("#include \"he/schema/layout.h\"");
        m_writer.WriteLine("#include \"he/schema/types.h\"\n");

        bool hasUserInclude = false;
        for (String::Reader importStr : m_root.Data().File().Imports())
        {
            if (importStr.IsEmpty())
                continue;

            hasUserInclude = true;
            m_writer.WriteLine("#include \"{}.h\"", importStr.AsView());
        }

        if (hasUserInclude)
            m_writer.Write('\n');

        WriteDeclInfo(m_root);
        m_writer.Write('\n');

        if (!m_namespaceName.IsEmpty())
        {
            m_writer.WriteLine("namespace {}", m_namespaceName);
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
        }

        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Type Declarations\n");
        for (Declaration::Reader decl : m_root.Children())
        {
            WriteDecl(decl, m_root);
        }

        m_writer.Write('\n');
        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Reader & Builder Declarations\n");
        for (Declaration::Reader decl : m_root.Children())
        {
            WriteImpl(decl, m_root);
        }

        m_writer.Write('\n');
        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Reader & Builder Field Definitions");
        for (Declaration::Reader decl : m_root.Children())
        {
            WriteFieldImpl(decl, m_root);
        }

        // Close the namespace
        if (!m_namespaceName.IsEmpty())
        {
            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        m_writer.Write('\n');
    }

    void CodeGenCpp::WriteDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        switch (decl.Data().Tag())
        {
            case Declaration::Data::Tag::File:
                break;
            case Declaration::Data::Tag::Attribute:
                WriteAttributeDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Constant:
                WriteConstDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Enum:
                WriteEnumDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Interface:
                WriteInterfaceDecl(decl, scope);
                break;
            case Declaration::Data::Tag::Struct:
                WriteStructDecl(decl, scope);
                break;
        }
    }

    void CodeGenCpp::WriteAttributeDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsAttribute());
        m_writer.WriteLine("struct {}", decl.Name().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{}() = delete;", decl.Name().AsView());
        m_writer.WriteLine("using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">;", decl.Id());

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteConstDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsConstant());
        Declaration::Data::Constant::Reader constDecl = decl.Data().Constant();

        m_writer.WriteIndent();
        if (decl.ParentId() != m_root.Id())
            m_writer.Write("static ");

        Type::Reader type = constDecl.Type();
        Type::Data::Reader typeData = type.Data();
        const bool isInline = typeData.IsBool() || typeData.IsEnum() || typeData.IsString() || IsArithmetic(typeData.Tag());

        if (isInline)
            m_writer.Write("inline constexpr ");
        else
            m_writer.Write("extern const ");

        if (typeData.IsString())
            m_writer.Write("char");
        else
            WriteType(type, scope, ReaderSuffix);

        m_writer.Write(' ');
        m_writer.Write(decl.Name().AsView());

        if (typeData.IsArray())
            m_writer.Write("[{}]", typeData.Array().Size());
        else if (typeData.IsString())
            m_writer.Write("[]");

        if (isInline)
        {
            m_writer.Write(" = ");
            WriteDataValue(type, scope, constDecl.Value());
        }

        m_writer.Write(";\n");
    }

    void CodeGenCpp::WriteEnumDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsEnum());
        Declaration::Data::Enum::Reader enumDecl = decl.Data().Enum();

        m_writer.WriteLine("enum class {} : uint16_t", decl.Name().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (Enumerator::Reader e : enumDecl.Enumerators())
        {
            m_writer.WriteLine("{} = {},", e.Name().AsView(), e.Ordinal());
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteInterfaceDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsInterface());

        m_writer.WriteLine("class {};", decl.Name().AsView());
    }

    void CodeGenCpp::WriteStructDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        WriteTemplate(decl);
        m_writer.WriteLine("struct {} final", decl.Name().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{}() = delete;", decl.Name().AsView());
        m_writer.WriteLine("using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">;", decl.Id());

        if (!structDecl.Fields().IsEmpty())
        {
            m_writer.Write('\n');
            m_writer.WriteLine("class Reader;");
            m_writer.WriteLine("class Builder;");
        }

        for (Declaration::Reader child : decl.Children())
        {
            m_writer.Write('\n');
            WriteDecl(child, decl);
        }

        if (structDecl.IsUnion())
        {
            m_writer.WriteLine("enum class Tag : uint16_t");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            he::String upperCamelName(Allocator::GetTemp());
            for (Field::Reader field : structDecl.Fields())
            {
                upperCamelName = field.Name();
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteLine("{} = {},", upperCamelName, field.UnionTag());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        switch (decl.Data().Tag())
        {
            case Declaration::Data::Tag::File:
            case Declaration::Data::Tag::Attribute:
            case Declaration::Data::Tag::Constant:
            case Declaration::Data::Tag::Enum:
                break;
            case Declaration::Data::Tag::Interface:
                WriteInterfaceImpl(decl, scope);
                break;
            case Declaration::Data::Tag::Struct:
                WriteStructImpl(decl, scope);
                break;
        }
    }

    void CodeGenCpp::WriteInterfaceImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsInterface());
        Declaration::Data::Interface::Reader interfaceDecl = decl.Data().Interface();

        for (Declaration::Reader child : decl.Children())
        {
            WriteImpl(child, scope);
        }

        WriteTemplate(decl);
        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);

        Type::Data::Reader superTypeData = interfaceDecl.Super().Data();
        Type::Data::Interface::Reader superInterface = superTypeData.IsInterface() ? superTypeData.Interface() : Type::Data::Interface::Reader{};

        if (superInterface.IsValid())
        {
            Declaration::Reader super = m_request.GetDecl(superInterface.Id());
            m_writer.Write(" : public ");
            WriteName(super, scope, superInterface.Brand(), ReaderSuffix);
        }
        m_writer.Write('\n');
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("virtual ~{}() {{}}", decl.Name().AsView());
        m_writer.WriteLine("using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">;", decl.Id());
        if (superInterface.IsValid())
        {
            Declaration::Reader super = m_request.GetDecl(superInterface.Id());
            m_writer.WriteIndent();
            m_writer.Write("using SuperType = ");
            WriteName(super, scope, superInterface.Brand(), ReaderSuffix);
            m_writer.Write(";\n");
        }
        m_writer.Write('\n');

        for (Declaration::Reader child : decl.Children())
        {
            WriteDecl(child, decl);
        }

        for (Method::Reader method : interfaceDecl.Methods())
        {
            Declaration::Reader params = m_request.GetDecl(method.ParamStruct());
            Declaration::Reader result = m_request.GetDecl(method.ResultStruct());
            m_writer.WriteLine("virtual {}::Reader {}({}::Reader) = 0;", result.Name().AsView(), method.Name().AsView(), params.Name().AsView());
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteStructImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        for (Declaration::Reader child : decl.Children())
        {
            WriteImpl(child, scope);
        }

        if (structDecl.Fields().IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write("::Reader final : public ::he::schema::StructReader\n");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteIndent();
        m_writer.Write("using StructType = ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write(";\n");
        m_writer.WriteLine("using SuperType = ::he::schema::StructReader;\n");

        if (structDecl.IsUnion())
        {
            m_writer.WriteLine("Tag Tag() const {{ return SuperType::GetDataField<enum Tag>({}); }}\n", structDecl.UnionTagOffset());
        }

        for (Field::Reader field : structDecl.Fields())
        {
            WriteFieldGetDecl(field, decl, true);
            m_writer.Write('\n');
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");

        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write("::Builder final : public ::he::schema::StructBuilder\n");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteIndent();
        m_writer.Write("using StructType = ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write(";\n");

        m_writer.WriteLine("using SuperType = ::he::schema::StructBuilder;\n");
        m_writer.WriteLine("StructType::Reader AsReader() const { return StructType::Reader(SuperType::AsReader()); }");
        m_writer.WriteLine("operator StructType::Reader() const { return AsReader(); }");

        if (structDecl.IsUnion())
        {
            m_writer.Write('\n');
            m_writer.WriteLine("Tag Tag() const {{ return SuperType::GetDataField<enum Tag>({}); }}\n", structDecl.UnionTagOffset());
            m_writer.WriteLine("void SetTag(enum Tag t) {{ return SuperType::SetDataField({}, t); }}", structDecl.UnionTagOffset());
        }

        for (Field::Reader field : structDecl.Fields())
        {
            m_writer.Write('\n');
            WriteFieldGetDecl(field, decl, false);
            WriteFieldSetDecl(field, decl);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteFieldImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        for (Declaration::Reader child : decl.Children())
        {
            WriteFieldImpl(child, scope);
        }

        if (!decl.Data().IsStruct())
            return;

        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        for (Field::Reader field : structDecl.Fields())
        {
            m_writer.Write('\n');
            WriteFieldGetImpl(field, decl, scope, true);
        }

        for (Field::Reader field : structDecl.Fields())
        {
            m_writer.Write('\n');
            WriteFieldGetImpl(field, decl, scope, false);
            WriteFieldSetImpl(field, decl, scope);
        }
    }

    void CodeGenCpp::WriteFieldGetDecl(Field::Reader field, Declaration::Reader decl, bool isReader)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        const char* suffix = isReader ? ReaderSuffix : BuilderSuffix;

        if (structDecl.IsUnion())
        {
            m_writer.WriteLine("bool Is{}() const;", upperCamelName);
        }

        if (field.Meta().IsUnion() || field.Meta().IsGroup())
        {
            m_writer.WriteLine("{0}{1} {0}() const;", upperCamelName, suffix);
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();

        if (fieldTypeData.IsVoid())
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName, field.Meta().Normal().Index());
            m_writer.WriteLine("::he::schema::Void {}() const;", upperCamelName);
        }
        else if (IsPointer(fieldType))
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName);

            m_writer.WriteIndent();
            WriteType(fieldType, decl, suffix);
            m_writer.Write(" {}() const;\n", upperCamelName);
        }
        else
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName);

            const bool isArray = fieldTypeData.IsArray();

            m_writer.WriteIndent();
            if (isArray)
            {
                m_writer.Write("::he::Span<");
                if (isReader)
                    m_writer.Write("const ");
                WriteType(fieldTypeData.Array().ElementType(), decl, nullptr);
                m_writer.Write(">");
            }
            else
            {
                WriteType(fieldType, decl, nullptr);
            }
            m_writer.Write(" {}() const;\n", upperCamelName);
        }
    }

    void CodeGenCpp::WriteFieldGetImpl(Field::Reader field, Declaration::Reader decl, Declaration::Reader scope, bool isReader)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        const char* suffix = isReader ? ReaderSuffix : BuilderSuffix;

        if (structDecl.IsUnion())
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, m_root, {}, suffix);
            m_writer.Write("{0}::Is{1}() const {{ return Tag() == Tag::{1}; }}\n", suffix, upperCamelName);
        }

        if (field.Meta().IsGroup() || field.Meta().IsUnion())
        {
            TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
            Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteName(groupType, scope, {}, suffix);
            m_writer.Write(suffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);
            m_writer.Write("return {}{}(*this); }}\n", upperCamelName, suffix);
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();

        if (fieldTypeData.IsVoid())
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return false; }}\n", suffix, upperCamelName);

            m_writer.WriteIndent();
            m_writer.Write("inline ::he::schema::Void ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);
            m_writer.Write("return {}; }\n");
        }
        else if (IsPointer(fieldType))
        {

            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("Is{0}() && ", upperCamelName);
            m_writer.Write("SuperType::HasPointerField({}); }}\n", norm.Index());

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteType(fieldType, scope, suffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);

            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            const bool isArray = fieldTypeData.IsArray();
            const bool hasDefault = isReader && norm.HasDefaultValue();

            if (isArray)
            {
                m_writer.Write("return SuperType::TryGetPointerArrayField<");
                WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
                m_writer.Write(">({}, {}", norm.Index(), fieldTypeData.Array().Size());
                if (hasDefault)
                    m_writer.Write(", ");
            }
            else if (fieldTypeData.IsAnyPointer())
            {
                HE_ASSERT(!hasDefault);
                m_writer.Write("return SuperType::GetPointerField({}); }}\n", norm.Index());
            }
            else
            {
                const Type::Data::Tag getterKind = fieldTypeData.IsBlob() ? Type::Data::Tag::List : fieldTypeData.Tag();
                m_writer.Write("return SuperType::GetPointerField({}).TryGet{}", norm.Index(), getterKind);
                if (fieldTypeData.IsBlob())
                {
                    m_writer.Write("<uint8_t>");
                }
                else if (!fieldTypeData.IsString())
                {
                    Type::Reader t = fieldTypeData.IsList() ? fieldTypeData.List().ElementType() : norm.Type();
                    if (IsPointer(t))
                        m_writer.Write("<struct ");
                    else
                        m_writer.Write("<");
                    WriteType(t, scope, nullptr);
                    m_writer.Write('>');
                }
                m_writer.Write('(');
                if (hasDefault)
                {
                    const DefaultValueRef ref = GetOrMakeDefaultValue(fieldType, norm.DefaultValue(), decl);
                    if (ref.scopeId != 0)
                    {
                        m_writer.Write("::he::schema::DeclInfo<" HE_ID_FMT ">::{} + {}",
                            ref.scopeId, ref.inSchema ? "RawSchema" : "DefaultValues", ref.offset);
                    }
                }
                m_writer.Write("); }\n");
            }
        }
        else
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return ", suffix, upperCamelName);
            if (structDecl.IsUnion())
                m_writer.Write("Is{0}() && ", upperCamelName);
            m_writer.Write("SuperType::HasDataField({}); }}\n", norm.Index());

            const bool isArray = fieldTypeData.IsArray();
            const bool hasDefault = (isReader || !isArray) && norm.HasDefaultValue();

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            if (isArray)
            {
                m_writer.Write("::he::Span<");
                if (isReader)
                    m_writer.Write("const ");
                WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
                m_writer.Write("> ");
            }
            else
            {
                WriteType(fieldType, scope, nullptr);
                m_writer.Write(' ');
            }
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::{}() const {{ ", suffix, upperCamelName);

            if (structDecl.IsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            if (isArray)
            {
                if (hasDefault)
                {
                    m_writer.Write("static const ");
                    WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
                    m_writer.Write(" DefaultValue_{}[]", upperCamelName);
                    WriteDataValue(fieldType, decl, norm.DefaultValue());
                    m_writer.Write("; ");
                }
                m_writer.Write("return SuperType::TryGetDataArrayField<");
                WriteType(fieldTypeData.Array().ElementType(), scope, nullptr);
            }
            else
            {
                m_writer.Write("return SuperType::{}GetDataField<{}",
                    structDecl.IsUnion() ? "" : "Try",
                    fieldTypeData.IsEnum() ? "enum " : "");
                WriteType(fieldType, scope, nullptr);
            }
            if (structDecl.IsUnion() && !isArray) // TODO: Read directly for arrays too
                m_writer.Write(">({}", norm.DataOffset());
            else
                m_writer.Write(">({}, {}", norm.Index(), norm.DataOffset());
            if (isArray)
            {
                m_writer.Write(", {}", fieldTypeData.Array().Size());
                if (hasDefault)
                {
                    m_writer.Write(", DefaultValue_{}", upperCamelName);
                }
            }
            else if (hasDefault)
            {
                m_writer.Write(", ");
                WriteDataValue(norm.Type(), decl, norm.DefaultValue());
            }
            m_writer.Write("); }\n");
        }
    }

    void CodeGenCpp::WriteFieldSetDecl(Field::Reader field, Declaration::Reader decl)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        if (field.Meta().IsGroup() || field.Meta().IsUnion())
        {
            if (structDecl.IsUnion())
            {
                TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                m_writer.WriteIndent();
                WriteName(groupType, decl, {}, BuilderSuffix);
                m_writer.Write(BuilderSuffix);
                m_writer.Write(' ');
                m_writer.Write("Init{}();\n", upperCamelName);
            }
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();
        const bool fieldIsPointer = IsPointer(fieldType);

        m_writer.WriteIndent();
        m_writer.Write("void Set{}(", upperCamelName);
        if (!fieldTypeData.IsVoid())
        {
            WriteType(fieldType, decl, ReaderSuffix);
            m_writer.Write(" value");
        }
        m_writer.Write(");\n");

        if (fieldIsPointer)
        {
            const bool fieldIsString = fieldTypeData.IsString();
            const bool fieldIsList = fieldTypeData.IsList() || fieldTypeData.IsBlob();

            m_writer.WriteIndent();
            WriteType(fieldType, decl, BuilderSuffix);
            m_writer.Write(" Init{}(", upperCamelName);
            if (fieldIsList)
                m_writer.Write("uint32_t size");
            else if (fieldIsString)
                m_writer.Write("::he::StringView str");
            m_writer.Write(");\n");
        }
    }

    void CodeGenCpp::WriteFieldSetImpl(Field::Reader field, Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        he::String upperCamelName(field.Name(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        if (field.Meta().IsGroup() || field.Meta().IsUnion())
        {
            if (structDecl.IsUnion())
            {
                TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                m_writer.WriteIndent();
                m_writer.Write("inline ");
                WriteName(groupType, scope, {}, BuilderSuffix);
                m_writer.Write(BuilderSuffix);
                m_writer.Write(' ');
                WriteName(decl, scope, {}, BuilderSuffix);
                m_writer.Write("::Builder::Init{0}() {{ SetTag(Tag::{0}); ", upperCamelName);
                if (field.Meta().IsGroup())
                {
                    WriteGroupFieldClear(groupType, decl);
                }
                m_writer.Write("return {}{}(*this); }}\n", upperCamelName, BuilderSuffix);
            }
            return;
        }

        Field::Meta::Normal::Reader norm = field.Meta().Normal();
        Type::Reader fieldType = norm.Type();
        Type::Data::Reader fieldTypeData = fieldType.Data();
        const bool fieldIsPointer = IsPointer(fieldType);

        m_writer.WriteIndent();
        m_writer.Write("inline void ");
        WriteName(decl, scope, {}, BuilderSuffix);
        m_writer.Write("::Builder::Set{}(", upperCamelName);
        if (!fieldTypeData.IsVoid())
        {
            WriteType(fieldType, scope, ReaderSuffix);
            m_writer.Write(" value");
        }
        m_writer.Write(") { ");
        if (structDecl.IsUnion())
            m_writer.Write("SetTag(Tag::{}); ", upperCamelName);
        if (fieldIsPointer)
        {
            m_writer.Write("SuperType::GetPointerField({}).Set(value); ", norm.Index());
        }
        else if (!fieldTypeData.IsVoid())
        {
            m_writer.Write("SuperType::{}<{}",
                structDecl.IsUnion() ? "SetDataField" : "SetAndMarkDataField",
                fieldTypeData.IsEnum() ? "enum " : "");
            WriteType(fieldType, scope, nullptr);
            if (structDecl.IsUnion())
                m_writer.Write(">({}, value); ", norm.DataOffset());
            else
                m_writer.Write(">({}, {}, value); ", norm.Index(), norm.DataOffset());
        }
        m_writer.Write("}\n");

        if (fieldIsPointer)
        {
            const bool fieldIsString = fieldTypeData.IsString();
            const bool fieldIsList = fieldTypeData.IsList() || fieldTypeData.IsBlob();

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteType(fieldType, scope, BuilderSuffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, BuilderSuffix);
            m_writer.Write("::Builder::Init{}(", upperCamelName);
            if (fieldIsList)
                m_writer.Write("uint32_t size");
            else if (fieldIsString)
                m_writer.Write("::he::StringView str");
            m_writer.Write(") { ");
            if (structDecl.IsUnion())
                m_writer.Write("SetTag(Tag::{}); ", upperCamelName);

            const Type::Data::Tag getterKind = fieldTypeData.IsBlob() ? Type::Data::Tag::List : fieldTypeData.Tag();
            if (fieldTypeData.IsAnyPointer())
            {
                m_writer.Write("return SuperType::GetPointerField({}); }}\n", norm.Index());
            }
            else
            {
                m_writer.Write("auto v = m_builder->Add{}", getterKind);
                if (fieldTypeData.IsBlob())
                {
                    m_writer.Write("<uint8_t>");
                }
                else if (!fieldTypeData.IsString())
                {
                    Type::Reader t = fieldTypeData.IsList() ? fieldTypeData.List().ElementType() : fieldType;
                    if (IsPointer(t))
                        m_writer.Write("<struct ");
                    else
                        m_writer.Write("<");
                    WriteType(t, scope, nullptr);
                    m_writer.Write('>');
                }
                m_writer.Write('(');
                if (fieldIsList)
                    m_writer.Write("size");
                else if (fieldIsString)
                    m_writer.Write("str");
                m_writer.Write("); SuperType::GetPointerField({}).Set(v); return v; }}\n", norm.Index());
            }
        }
    }

    void CodeGenCpp::WriteGroupFieldClear(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.Data().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        for (Field::Reader field : structDecl.Fields())
        {
            if (field.Meta().IsGroup() || field.Meta().IsUnion())
            {
                TypeId groupTypeId = field.Meta().IsGroup() ? field.Meta().Group().TypeId() : field.Meta().Union().TypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                WriteGroupFieldClear(groupType, scope);
                continue;
            }

            he::String upperCamelName(field.Name(), Allocator::GetTemp());
            upperCamelName[0] = ToUpper(upperCamelName[0]);

            Field::Meta::Normal::Reader norm = field.Meta().Normal();
            Type::Reader fieldType = norm.Type();
            Type::Data::Reader fieldTypeData = fieldType.Data();
            const bool fieldIsPointer = IsPointer(fieldType);

            if (fieldIsPointer)
            {
                m_writer.Write("SuperType::ClearPointerField({}); ", norm.Index());
            }
            else
            {
                m_writer.Write("SuperType::ClearDataField({}); ", norm.Index());
            }
        }
    }

    void CodeGenCpp::GenSource()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");

        // headers
        StringView baseName = GetPathWithoutExtension(m_request.fileName);
        m_writer.WriteLine("#include \"{}.hsc.h\"\n", baseName);
        m_writer.WriteLine("#include \"he/core/enum_ops.h\"", baseName);
        m_writer.WriteLine("#include \"he/core/types.h\"\n", baseName);

        m_writer.WriteLine("namespace he::schema");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        WriteRawSchemaData();
        WriteDeclInfoSrc(m_root);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        m_writer.WriteLine("namespace he");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        WriteEnumStrings(m_root);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::WriteRawSchemaData()
    {
        m_writer.WriteLine("static const Word RawFileSchema_{:016x}[] =", m_root.Id());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();
        m_writer.WriteIndent();
        const uint32_t size = m_request.schemaData.Size();
        for (uint32_t i = 0; i < size; ++i)
        {
            if (i > 0)
            {
                if ((i % 10) == 0)
                {
                    m_writer.Write('\n');
                    m_writer.WriteIndent();
                }
                else
                {
                    m_writer.Write(' ');
                }
            }
            m_writer.Write("{:#018x}ull,", m_request.schemaData[i]);
        }
        m_writer.Write('\n');
        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");
    }

    void CodeGenCpp::WriteDeclInfoSrc(Declaration::Reader decl)
    {
        const ptrdiff_t schemaOffset = static_cast<StructReader&>(decl).Data() - m_request.schemaData.Data();

        const auto it = m_defaultValues.find(decl.Id());
        if (it != m_defaultValues.end())
        {
            const Builder& builder = it->second;
            const Word* data = builder.Data();
            m_writer.WriteLine("static const Word DefaultValues_{:016x}[] =", decl.Id());
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
            m_writer.WriteIndent();
            const uint32_t size = builder.Size();
            for (uint32_t i = 0; i < size; ++i)
            {
                if (i > 0)
                {
                    if ((i % 10) == 0)
                    {
                        m_writer.Write('\n');
                        m_writer.WriteIndent();
                    }
                    else
                    {
                        m_writer.Write(' ');
                    }
                }
                m_writer.Write("{:#018x}ull,", data[i]);
            }
            m_writer.Write('\n');
            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
        }

        m_writer.WriteLine("const Word* DeclInfo<" HE_ID_FMT ">::RawSchema = RawFileSchema_{:016x} + {};", decl.Id(), m_root.Id(), schemaOffset);

        if (it != m_defaultValues.end())
            m_writer.WriteLine("const Word* DeclInfo<" HE_ID_FMT ">::DefaultValues = DefaultValues_{:016x};", decl.Id(), decl.Id());
        else
            m_writer.WriteLine("const Word* DeclInfo<" HE_ID_FMT ">::DefaultValues = nullptr;", decl.Id());
        m_writer.Write('\n');

        for (Declaration::Reader child : decl.Children())
        {
            WriteDeclInfoSrc(child);
        }
    }

    void CodeGenCpp::WriteEnumStrings(Declaration::Reader decl)
    {
        if (decl.Data().IsEnum())
        {
            const Declaration::Data::Enum::Reader enumDecl = decl.Data().Enum();

            m_writer.WriteLine("template <>");

            m_writer.WriteIndent();
            m_writer.Write("const char* AsString(");
            WriteName(decl, {}, {}, nullptr);
            m_writer.Write(" x)\n");

            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("switch (x)");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            for (const Enumerator::Reader e : enumDecl.Enumerators())
            {
                m_writer.WriteIndent();
                m_writer.Write("case ");
                WriteName(decl, {}, {}, nullptr);
                m_writer.Write("::{0}: return \"{0}\";\n", e.Name().AsView());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");

            m_writer.WriteLine("return \"<unknown>\";");

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        else if (decl.Data().IsStruct() && decl.Data().Struct().IsUnion())
        {
            Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

            m_writer.WriteLine("template <>");

            m_writer.WriteIndent();
            m_writer.Write("const char* AsString(");
            WriteName(decl, {}, {}, nullptr);
            m_writer.Write("::Tag x)\n");

            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("switch (x)");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            he::String upperCamelName(Allocator::GetTemp());
            for (const Field::Reader f : structDecl.Fields())
            {
                upperCamelName = f.Name();
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteIndent();
                m_writer.Write("case ");
                WriteName(decl, {}, {}, nullptr);
                m_writer.Write("::Tag::{0}: return \"{0}\";\n", upperCamelName);
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");

            m_writer.WriteLine("return \"<unknown>\";");

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }

        for (Declaration::Reader child : decl.Children())
        {
            WriteEnumStrings(child);
        }
    }

    bool CodeGenCpp::FlushToFile(const char* suffix)
    {
        he::String filePath(m_request.outDir, Allocator::GetTemp());
        ConcatPath(filePath, m_request.fileName);
        RemoveExtension(filePath);
        filePath += suffix;

        const StringView code = m_writer.Str();

        File f;
        if (!f.Open(filePath.Data(), FileOpenMode::WriteTruncate))
            return false;

        if (!f.Write(code.Data(), code.Size()))
            return false;

        return true;
    }

    void CodeGenCpp::WriteDeclInfo(Declaration::Reader decl)
    {
        const bool isStruct = decl.Data().IsStruct();
        const uint16_t dataFieldCount = isStruct ? decl.Data().Struct().DataFieldCount() : 0;
        const uint16_t dataWordSize = isStruct ? decl.Data().Struct().DataWordSize() : 0;
        const uint16_t pointerCount = isStruct ? decl.Data().Struct().PointerCount() : 0;

        m_writer.WriteIndent();
        m_writer.Write("HE_SCHEMA_DECL_INFO(" HE_ID_FMT ", " HE_ID_FMT ", {}, {}, {}, {}); // ",
            decl.Id(), decl.ParentId(), decl.Data().Tag(), dataFieldCount, dataWordSize, pointerCount);
        if (decl.Data().IsFile())
            m_writer.Write("file");
        else
            WriteName(decl, m_root, {}, nullptr);
        m_writer.Write('\n');

        for (Declaration::Reader child : decl.Children())
        {
            WriteDeclInfo(child);
        }
    }

    void CodeGenCpp::WriteName(Declaration::Reader decl, Declaration::Reader scope, Brand::Reader brand, const char* pointerSuffix)
    {
        if (!scope.IsValid() || (decl.ParentId() != scope.Id() && decl.ParentId() != scope.ParentId()))
        {
            Declaration::Reader parent = m_request.GetDecl(decl.ParentId());
            if (!parent.Data().IsFile())
            {
                WriteName(parent, scope, brand, pointerSuffix);
                m_writer.Write("::");
            }
            else if (!scope.IsValid())
            {
                m_writer.Write("::{}::", m_namespaceName);
            }
        }

        m_writer.Write(decl.Name());

        for (Brand::Scope::Reader brandScope : brand.Scopes())
        {
            if (brandScope.ScopeId() == decl.Id())
            {
                List<Type>::Reader params = brandScope.Params();

                m_writer.Write("<");
                for (uint32_t i = 0; i < params.Size(); ++i)
                {
                    Type::Reader t = params[i];
                    WriteType(t, scope, pointerSuffix);
                    if (i < (params.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(">");
                break;
            }
        }
    }

    void CodeGenCpp::WriteTemplate(Declaration::Reader decl)
    {
        List<String>::Reader typeParams = decl.TypeParams();

        if (typeParams.IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("template <");
        for (uint32_t i = 0; i < typeParams.Size(); ++i)
        {
            m_writer.Write("typename ");
            m_writer.Write(typeParams[i]);
            if (i < (typeParams.Size() - 1))
                m_writer.Write(", ");
        }
        m_writer.Write(">\n");
    }

    void CodeGenCpp::WriteType(Type::Reader type, Declaration::Reader scope, const char* pointerSuffix)
    {
        switch (type.Data().Tag())
        {
            case Type::Data::Tag::Void: m_writer.Write("::he::schema::Void"); break;
            case Type::Data::Tag::Bool: m_writer.Write("bool"); break;
            case Type::Data::Tag::Int8: m_writer.Write("int8_t"); break;
            case Type::Data::Tag::Int16: m_writer.Write("int16_t"); break;
            case Type::Data::Tag::Int32: m_writer.Write("int32_t"); break;
            case Type::Data::Tag::Int64: m_writer.Write("int64_t"); break;
            case Type::Data::Tag::Uint8: m_writer.Write("uint8_t"); break;
            case Type::Data::Tag::Uint16: m_writer.Write("uint16_t"); break;
            case Type::Data::Tag::Uint32: m_writer.Write("uint32_t"); break;
            case Type::Data::Tag::Uint64: m_writer.Write("uint64_t"); break;
            case Type::Data::Tag::Float32: m_writer.Write("float"); break;
            case Type::Data::Tag::Float64: m_writer.Write("double"); break;
            case Type::Data::Tag::Array:
            {
                Type::Data::Array::Reader arrayType = type.Data().Array();
                if (IsPointer(arrayType.ElementType()))
                {
                    m_writer.Write("::he::schema::List<");
                    WriteType(arrayType.ElementType(), scope, nullptr);
                    m_writer.Write(">");
                }
                else
                {
                    m_writer.Write("::he::Span<const ");
                    WriteType(arrayType.ElementType(), scope, nullptr);
                    m_writer.Write(">");
                }
                break;
            }
            case Type::Data::Tag::Blob:
                m_writer.Write("::he::schema::List<uint8_t>");
                break;
            case Type::Data::Tag::String:
                m_writer.Write("::he::schema::String");
                break;
            case Type::Data::Tag::List:
            {
                Type::Data::List::Reader listType = type.Data().List();
                m_writer.Write("::he::schema::List<");
                WriteType(listType.ElementType(), scope, nullptr);
                m_writer.Write(">");
                break;
            }
            case Type::Data::Tag::Enum:
            {
                Type::Data::Enum::Reader enumType = type.Data().Enum();
                Declaration::Reader decl = m_request.GetDecl(enumType.Id());
                HE_ASSERT(decl.Data().IsEnum());
                WriteName(decl, scope, enumType.Brand(), nullptr);
                break;
            }
            case Type::Data::Tag::Struct:
            {
                Type::Data::Struct::Reader structType = type.Data().Struct();
                Declaration::Reader decl = m_request.GetDecl(structType.Id());
                HE_ASSERT(decl.Data().IsStruct());
                WriteName(decl, scope, structType.Brand(), nullptr);
                break;
            }
            case Type::Data::Tag::Interface:
            {
                Type::Data::Interface::Reader interfaceType = type.Data().Interface();
                Declaration::Reader decl = m_request.GetDecl(interfaceType.Id());
                HE_ASSERT(decl.Data().IsInterface());
                WriteName(decl, scope, interfaceType.Brand(), nullptr);
                break;
            }
            case Type::Data::Tag::AnyPointer:
            {
                Type::Data::AnyPointer::Reader anyType = type.Data().AnyPointer();

                if (anyType.ParamScopeId() == 0)
                {
                    m_writer.Write("AnyPointer");
                }
                else
                {
                    Declaration::Reader decl = m_request.GetDecl(anyType.ParamScopeId());
                    m_writer.Write(decl.TypeParams()[anyType.ParamIndex()]);
                }
                break;
            }
        }

        if (pointerSuffix && IsPointer(type))
        {
            m_writer.Write(pointerSuffix);
        }
    }

    void CodeGenCpp::WriteDataValue(Type::Reader type, Declaration::Reader scope, Value::Reader value)
    {
        switch (value.Data().Tag())
        {
            case Value::Data::Tag::Void: m_writer.Write("{}"); break;
            case Value::Data::Tag::Bool: m_writer.Write("{}", value.Data().Bool()); break;
            case Value::Data::Tag::Int8: m_writer.Write("{}", value.Data().Int8()); break;
            case Value::Data::Tag::Int16: m_writer.Write("{}", value.Data().Int16()); break;
            case Value::Data::Tag::Int32: m_writer.Write("{}", value.Data().Int32()); break;
            case Value::Data::Tag::Int64: m_writer.Write("{}", value.Data().Int64()); break;
            case Value::Data::Tag::Uint8: m_writer.Write("{}", value.Data().Uint8()); break;
            case Value::Data::Tag::Uint16: m_writer.Write("{}", value.Data().Uint16()); break;
            case Value::Data::Tag::Uint32: m_writer.Write("{}", value.Data().Uint32()); break;
            case Value::Data::Tag::Uint64: m_writer.Write("{}", value.Data().Uint64()); break;
            case Value::Data::Tag::Float32: m_writer.Write("{}", value.Data().Float32()); break;
            case Value::Data::Tag::Float64: m_writer.Write("{}", value.Data().Float64()); break;
            case Value::Data::Tag::Array:
            {
                HE_ASSERT(type.Data().IsArray());
                Type::Reader elementType = type.Data().Array().ElementType();
                List<Value>::Reader arrayValues = value.Data().Array();

                m_writer.Write("{ ");
                for (uint32_t i = 0; i < arrayValues.Size(); ++i)
                {
                    WriteDataValue(elementType, scope, arrayValues[i]);
                    if (i < (arrayValues.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(" }");
                break;
            }
            case Value::Data::Tag::Enum:
            {
                HE_ASSERT(type.Data().IsEnum());
                Type::Data::Enum::Reader enumType = type.Data().Enum();
                Declaration::Reader decl = m_request.GetDecl(enumType.Id());

                HE_ASSERT(decl.Data().IsEnum());
                Declaration::Data::Enum::Reader enumDecl = decl.Data().Enum();

                WriteName(decl, scope, enumType.Brand(), nullptr);
                m_writer.Write("::");
                for (Enumerator::Reader e : enumDecl.Enumerators())
                {
                    if (e.Ordinal() == value.Data().Enum())
                    {
                        m_writer.Write(e.Name());
                        break;
                    }
                }
                break;
            }
            case Value::Data::Tag::String:
            {
                // Technically a pointer value, but sometimes we use it like a data value (like for constants).
                HE_ASSERT(type.Data().IsString());
                String::Reader str = value.Data().String();
                m_writer.Write("\"{}\"", str.AsView());
                break;
            }
            case Value::Data::Tag::Blob:
            case Value::Data::Tag::List:
            case Value::Data::Tag::Tuple:
            case Value::Data::Tag::Interface:
            case Value::Data::Tag::AnyPointer:
                HE_ASSERT(false, "Invalid value kind. Expected a non-pointer value.");
                break;
        }
    }

    void CodeGenCpp::WriteWithReplace(StringView input, char what, StringView with)
    {
        for (char ch : input)
        {
            if (ch == what)
            {
                m_writer.Write(with);
            }
            else
            {
                m_writer.Write(ch);
            }
        }
    }

    CodeGenCpp::DefaultValueRef CodeGenCpp::GetOrMakeDefaultValue(Type::Reader type, Value::Reader value, Declaration::Reader scope)
    {
        // Maybe: One builder per struct named Defaults_declId and output here is "Defaults_declId + OFFSET"
        Value::Data::Reader valueData = value.Data();
        const Word* rootData = static_cast<const StructReader&>(m_root).Data();

        switch (valueData.Tag())
        {
            case Value::Data::Tag::Blob:
            {
                ListReader list = valueData.Blob();
                return { true, m_root.Id(), list.Data() - rootData };
            }
            case Value::Data::Tag::String:
            {
                ListReader list = valueData.String();
                return { true, m_root.Id(), list.Data() - rootData };
            }
            case Value::Data::Tag::Array:
            {
                const Type::Reader elementType = type.Data().Array().ElementType();
                const List<Value>::Reader values = value.Data().Array();
                const ListBuilder defaultValue = MakeListDefault(elementType, values, scope);
                return { false, scope.Id(), defaultValue.WordOffset() };
            }
            case Value::Data::Tag::List:
            {
                const Type::Reader elementType = type.Data().List().ElementType();
                const List<Value>::Reader values = value.Data().List();
                const ListBuilder defaultValue = MakeListDefault(elementType, values, scope);
                return { false, scope.Id(), defaultValue.WordOffset() };
            }
            case Value::Data::Tag::Tuple:
            {
                const List<Value::TupleValue>::Reader values = value.Data().Tuple();
                const StructBuilder defaultValue = MakeStructDefault(type, values, scope);
                return { false, scope.Id(), defaultValue.WordOffset() };
            }
            case Value::Data::Tag::Void:
            case Value::Data::Tag::Bool:
            case Value::Data::Tag::Int8:
            case Value::Data::Tag::Int16:
            case Value::Data::Tag::Int32:
            case Value::Data::Tag::Int64:
            case Value::Data::Tag::Uint8:
            case Value::Data::Tag::Uint16:
            case Value::Data::Tag::Uint32:
            case Value::Data::Tag::Uint64:
            case Value::Data::Tag::Float32:
            case Value::Data::Tag::Float64:
            case Value::Data::Tag::Enum:
                HE_ASSERT(false, "Invalid value kind. Expected a pointer value.");
                break;

            case Value::Data::Tag::Interface:
                HE_ASSERT(false, "Invalid value kind. Interface cannot have a default value.");
                break;

            case Value::Data::Tag::AnyPointer:
                HE_ASSERT(false, "Invalid value kind. AnyPointer cannot have a default value.");
                break;
        }

        return {};
    }

    ListBuilder CodeGenCpp::MakeListDefault(Type::Reader elementType, List<Value>::Reader values, Declaration::Reader scope)
    {
        const TypeId scopeId = scope.Id();
        const uint32_t size = values.Size();
        const Value::Data::Tag elementTag = values[0].Data().Tag();

        ElementSize elementSize = ElementSize::Void;
        switch (elementTag)
        {
            case Value::Data::Tag::Bool: elementSize = ElementSize::Bit; break;
            case Value::Data::Tag::Int8: elementSize = ElementSize::Byte; break;
            case Value::Data::Tag::Int16: elementSize = ElementSize::TwoBytes; break;
            case Value::Data::Tag::Int32: elementSize = ElementSize::FourBytes; break;
            case Value::Data::Tag::Int64: elementSize = ElementSize::EightBytes; break;
            case Value::Data::Tag::Uint8: elementSize = ElementSize::Byte; break;
            case Value::Data::Tag::Uint16: elementSize = ElementSize::TwoBytes; break;
            case Value::Data::Tag::Uint32: elementSize = ElementSize::FourBytes; break;
            case Value::Data::Tag::Uint64: elementSize = ElementSize::EightBytes; break;
            case Value::Data::Tag::Float32: elementSize = ElementSize::FourBytes; break;
            case Value::Data::Tag::Float64: elementSize = ElementSize::EightBytes; break;
            case Value::Data::Tag::Blob: elementSize = ElementSize::Pointer; break;
            case Value::Data::Tag::String: elementSize = ElementSize::Pointer; break;
            case Value::Data::Tag::List: elementSize = ElementSize::Pointer; break;
            case Value::Data::Tag::Enum: elementSize = ElementSize::TwoBytes; break;
            case Value::Data::Tag::Tuple: elementSize = ElementSize::Composite; break;
            case Value::Data::Tag::Array:
                HE_ASSERT(false, "Arrays cannot be nested in lists or other arrays");
                break;
            case Value::Data::Tag::Interface:
            case Value::Data::Tag::AnyPointer:
            case Value::Data::Tag::Void:
                HE_ASSERT(false, "{} cannot have a default value", elementTag);
                break;
        }

        Builder& builder = m_defaultValues[scopeId];
        ListBuilder list = builder.AddList(elementSize, size);

        for (uint32_t i = 0; i < size; ++i)
        {
            Value::Data::Reader valueData = values[i].Data();

            switch (elementTag)
            {
                case Value::Data::Tag::Bool: list.SetDataElement<bool>(i, valueData.Bool()); break;
                case Value::Data::Tag::Int8: list.SetDataElement<int8_t>(i, valueData.Int8()); break;
                case Value::Data::Tag::Int16: list.SetDataElement<int16_t>(i, valueData.Int16()); break;
                case Value::Data::Tag::Int32: list.SetDataElement<int32_t>(i, valueData.Int32()); break;
                case Value::Data::Tag::Int64: list.SetDataElement<int64_t>(i, valueData.Int64()); break;
                case Value::Data::Tag::Uint8: list.SetDataElement<uint8_t>(i, valueData.Uint8()); break;
                case Value::Data::Tag::Uint16: list.SetDataElement<uint16_t>(i, valueData.Uint16()); break;
                case Value::Data::Tag::Uint32: list.SetDataElement<uint32_t>(i, valueData.Uint32()); break;
                case Value::Data::Tag::Uint64: list.SetDataElement<uint64_t>(i, valueData.Uint64()); break;
                case Value::Data::Tag::Float32: list.SetDataElement<float>(i, valueData.Float32()); break;
                case Value::Data::Tag::Float64: list.SetDataElement<double>(i, valueData.Float64()); break;
                case Value::Data::Tag::Enum: list.SetDataElement<uint16_t>(i, valueData.Enum()); break;
                case Value::Data::Tag::Blob:
                {
                    const List<uint8_t>::Reader valueBytes = valueData.Blob();
                    List<uint8_t>::Builder bytes = builder.AddList<uint8_t>(valueBytes.Size());
                    MemCopy(bytes.Data(), valueBytes.Data(), valueBytes.Size());
                    list.SetPointerElement(i, bytes);
                    break;
                }
                case Value::Data::Tag::String:
                {
                    const String::Reader valueStr = valueData.String();
                    const String::Builder str = builder.AddString(valueStr);
                    list.SetPointerElement(i, str);
                    break;
                }
                case Value::Data::Tag::List:
                {
                    const Type::Reader subElementType = elementType.Data().List().ElementType();
                    ListBuilder v = MakeListDefault(subElementType, valueData.List(), scope);
                    list.SetPointerElement(i, v);
                    break;
                }
                case Value::Data::Tag::Tuple:
                {
                    const Declaration::Reader decl = m_request.GetDecl(elementType.Data().Struct().Id());
                    const Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();
                    StructBuilder v = list.GetCompositeElement(i);
                    FillStructDefault(v, structDecl, valueData.Tuple(), scope);
                    break;
                }
                case Value::Data::Tag::Array:
                    HE_ASSERT(false, "Arrays cannot be nested in lists or other arrays");
                    break;
                case Value::Data::Tag::Interface:
                case Value::Data::Tag::AnyPointer:
                case Value::Data::Tag::Void:
                    HE_ASSERT(false, "{} types cannot have default values", elementTag);
                    break;
            }
        }

        return list;
    }

    StructBuilder CodeGenCpp::MakeStructDefault(Type::Reader type, List<Value::TupleValue>::Reader values, Declaration::Reader scope)
    {
        const TypeId scopeId = scope.Id();
        Builder& builder = m_defaultValues[scopeId];

        const Type::Data::Struct::Reader structType = type.Data().Struct();
        const Declaration::Reader decl = m_request.GetDecl(structType.Id());
        const Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();

        StructBuilder dst = builder.AddStruct(structDecl.DataFieldCount(), structDecl.DataWordSize(), structDecl.PointerCount());
        FillStructDefault(dst, structDecl, values, scope);
        return dst;
    }

    void CodeGenCpp::FillStructDefault(StructBuilder dst, Declaration::Data::Struct::Reader structDecl, List<Value::TupleValue>::Reader values, Declaration::Reader scope)
    {
        for (const Value::TupleValue::Reader pair : values)
        {
            for (const Field::Reader field : structDecl.Fields())
            {
                if (pair.Name() != field.Name())
                    continue;

                const Field::Meta::Reader fieldMeta = field.Meta();

                HE_ASSERT(!fieldMeta.IsUnion(), "Union fields cannot have a default value");

                if (fieldMeta.IsGroup())
                {
                    const Declaration::Reader groupDecl = m_request.GetDecl(fieldMeta.Group().TypeId());
                    const Declaration::Data::Struct::Reader groupStructDecl = groupDecl.Data().Struct();
                    FillStructDefault(dst, groupStructDecl, pair.Value().Data().Tuple(), scope);
                }
                else
                {
                    const Field::Meta::Normal::Reader norm = fieldMeta.Normal();
                    FillStructField(dst, norm.Type().Data(), norm.Index(), norm.DataOffset(), pair.Value().Data(), scope);
                }
            }
        }
    }

    void CodeGenCpp::FillStructField(StructBuilder dst, Type::Data::Reader type, uint16_t index, uint32_t dataOffset, Value::Data::Reader value, Declaration::Reader scope)
    {
        switch (type.Tag())
        {
            case Type::Data::Tag::Bool: dst.SetAndMarkDataField<bool>(index, dataOffset, value.Bool()); break;
            case Type::Data::Tag::Int8: dst.SetAndMarkDataField<int8_t>(index, dataOffset, value.Int8()); break;
            case Type::Data::Tag::Int16: dst.SetAndMarkDataField<int16_t>(index, dataOffset, value.Int16()); break;
            case Type::Data::Tag::Int32: dst.SetAndMarkDataField<int32_t>(index, dataOffset, value.Int32()); break;
            case Type::Data::Tag::Int64: dst.SetAndMarkDataField<int64_t>(index, dataOffset, value.Int64()); break;
            case Type::Data::Tag::Uint8: dst.SetAndMarkDataField<uint8_t>(index, dataOffset, value.Uint8()); break;
            case Type::Data::Tag::Uint16: dst.SetAndMarkDataField<uint16_t>(index, dataOffset, value.Uint16()); break;
            case Type::Data::Tag::Uint32: dst.SetAndMarkDataField<uint32_t>(index, dataOffset, value.Uint32()); break;
            case Type::Data::Tag::Uint64: dst.SetAndMarkDataField<uint64_t>(index, dataOffset, value.Uint64()); break;
            case Type::Data::Tag::Float32: dst.SetAndMarkDataField<float>(index, dataOffset, value.Float32()); break;
            case Type::Data::Tag::Float64: dst.SetAndMarkDataField<double>(index, dataOffset, value.Float64()); break;
            case Type::Data::Tag::Enum: dst.SetAndMarkDataField<uint16_t>(index, dataOffset, value.Enum()); break;
            case Type::Data::Tag::Blob:
            {
                const List<uint8_t>::Reader valueBytes = value.Blob();
                List<uint8_t>::Builder bytes = dst.Builder()->AddList<uint8_t>(valueBytes.Size());
                MemCopy(bytes.Data(), valueBytes.Data(), valueBytes.Size());
                dst.GetPointerField(index).Set(bytes);
                break;
            }
            case Type::Data::Tag::String:
            {
                const String::Reader valueStr = value.String();
                const String::Builder str = dst.Builder()->AddString(valueStr);
                dst.GetPointerField(index).Set(str);
                break;
            }
            case Type::Data::Tag::Array:
            {
                const Type::Data::Array::Reader arrayType = type.Array();
                const Type::Reader elementType = arrayType.ElementType();
                const uint16_t size = arrayType.Size();
                const List<Value>::Reader arrayValues = value.Array();
                const bool elementIsPointer = IsPointer(elementType);

                for (uint16_t i = 0; i < size; ++i)
                {
                    if (elementIsPointer)
                        FillStructField(dst, elementType.Data(), index + i, 0, arrayValues[i].Data(), scope);
                    else
                        FillStructField(dst, elementType.Data(), index, dataOffset + i, arrayValues[i].Data(), scope);
                }
                break;
            }
            case Type::Data::Tag::List:
            {
                const Type::Reader elementType = type.List().ElementType();
                ListBuilder list = MakeListDefault(elementType, value.List(), scope);
                dst.GetPointerField(index).Set(list);
                break;
            }
            case Type::Data::Tag::Struct:
            {
                const Declaration::Reader decl = m_request.GetDecl(type.Struct().Id());
                const Declaration::Data::Struct::Reader structDecl = decl.Data().Struct();
                StructBuilder st = dst.Builder()->AddStruct(structDecl.DataFieldCount(), structDecl.DataWordSize(), structDecl.PointerCount());
                FillStructDefault(st, structDecl, value.Tuple(), scope);
                dst.GetPointerField(index).Set(st);
                break;
            }
            case Type::Data::Tag::Interface:
            case Type::Data::Tag::AnyPointer:
            case Type::Data::Tag::Void:
                HE_ASSERT(false, "{} types cannot have default values", type.Tag());
                break;
        }
    }

    bool GenerateCpp(const CodeGenRequest& request)
    {
        CodeGenCpp generator(request);
        if (!generator.Generate())
            return false;

        return true;
    }
}
;
