// Copyright Chad Engler

#include "codegen_cpp.h"

#include "he/core/ascii.h"
#include "he/core/file.h"
#include "he/core/path.h"
#include "he/core/enum_fmt.h"
#include "he/core/string.h"
#include "he/core/string_fmt.h"
#include "he/core/string_view.h"
#include "he/core/string_view_fmt.h"

namespace he::schema
{
    #define HE_ID_FMT "{:#018x}"

    constexpr const char ReaderSuffix[] = "::Reader";
    constexpr const char BuilderSuffix[] = "::Builder";

    CodeGenCpp::CodeGenCpp(const CodeGenRequest& request) noexcept
        : m_request(request)
        , m_root(m_request.schemaFile.GetRoot())
    {
        for (char ch : m_root.GetName())
        {
            if (ch == '.')
                m_namespaceName += "::";
            else
                m_namespaceName += ch;
        }
    }

    bool CodeGenCpp::Generate()
    {
        m_writer.Reserve(16384); // 16 KB

        GenHeader();
        if (!FlushToFile(".hsc.h"))
            return false;

        m_writer.Clear();

        GenSource();
        if (!FlushToFile(".hsc.cpp"))
            return false;

        m_writer.Clear();

        return true;
    }

    void CodeGenCpp::GenHeader()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");
        m_writer.WriteLine("#pragma once\n");
        m_writer.WriteLine("#include \"he/core/assert.h\"");
        m_writer.WriteLine("#include \"he/core/string_view.h\"");
        m_writer.WriteLine("#include \"he/core/types.h\"");
        m_writer.WriteLine("#include \"he/schema/layout.h\"");
        m_writer.WriteLine("#include \"he/schema/types.h\"\n");

        bool hasUserInclude = false;
        for (String::Reader importStr : m_root.GetData().GetFile().GetImports())
        {
            if (importStr.IsEmpty())
                continue;

            hasUserInclude = true;
            m_writer.WriteLine("#include \"{}.h\"", importStr.AsView());
        }

        if (hasUserInclude)
            m_writer.Write('\n');

        m_writer.WriteLine("namespace he::schema");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();
        WriteDeclInfo(m_root);
        m_writer.DecreaseIndent();
        m_writer.WriteLine("}\n");

        if (!m_namespaceName.IsEmpty())
        {
            m_writer.WriteLine("namespace {}", m_namespaceName);
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
        }

        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Type Declarations\n");
        for (Declaration::Reader decl : m_root.GetChildren())
        {
            WriteDecl(decl, m_root);
        }

        m_writer.Write('\n');
        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Reader & Builder Declarations\n");
        for (Declaration::Reader decl : m_root.GetChildren())
        {
            WriteImpl(decl, m_root);
        }

        m_writer.Write('\n');
        m_writer.WriteLine("// ---------------------------------------------------------------------------------------------");
        m_writer.WriteLine("// Reader & Builder Field Definitions");
        for (Declaration::Reader decl : m_root.GetChildren())
        {
            WriteFieldImpl(decl, m_root);
        }

        // Close the namespace
        if (!m_namespaceName.IsEmpty())
        {
            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        m_writer.Write('\n');
    }

    void CodeGenCpp::WriteDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        switch (decl.GetData().GetUnionTag())
        {
            case Declaration::Data::UnionTag::File:
                break;
            case Declaration::Data::UnionTag::Attribute:
                WriteAttributeDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Constant:
                WriteConstDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Enum:
                WriteEnumDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Interface:
                WriteInterfaceDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Struct:
                WriteStructDecl(decl, scope);
                break;
        }
    }

    void CodeGenCpp::WriteAttributeDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsAttribute());
        m_writer.WriteLine("struct {}", decl.GetName().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{}() = delete;", decl.GetName().AsView());
        m_writer.WriteLine("HE_SCHEMA_DECL_ATTRIBUTE(" HE_ID_FMT ", " HE_ID_FMT ");", decl.GetId(), decl.GetParentId());

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteConstDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.GetData().IsConstant());
        Declaration::Data::Constant::Reader constDecl = decl.GetData().GetConstant();

        m_writer.WriteIndent();
        if (decl.GetParentId() != m_root.GetId())
            m_writer.Write("static ");

        Type::Reader type = constDecl.GetType();
        Type::Data::Reader typeData = type.GetData();
        const bool isInline = typeData.IsBool() || typeData.IsEnum() || typeData.IsString() || IsArithmetic(typeData.GetUnionTag());

        if (isInline)
            m_writer.Write("inline constexpr ");
        else
            m_writer.Write("extern const ");

        if (typeData.IsString())
            m_writer.Write("char");
        else
            WriteType(type, scope, ReaderSuffix);

        m_writer.Write(' ');
        m_writer.Write(decl.GetName().AsView());

        if (typeData.IsArray())
            m_writer.Write("[{}]", typeData.GetArray().GetSize());
        else if (typeData.IsString())
            m_writer.Write("[]");

        if (isInline)
        {
            m_writer.Write(" = ");
            WriteDataValue(type, scope, constDecl.GetValue());
        }

        m_writer.Write(";\n");
    }

    void CodeGenCpp::WriteEnumDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsEnum());
        m_writer.WriteLine("using {0} = ::he::schema::{0}_{1:016x};", decl.GetName().AsView(), decl.GetId());
    }

    void CodeGenCpp::WriteInterfaceDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsInterface());

        m_writer.WriteLine("class {}", decl.GetName().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{}() = delete;", decl.GetName().AsView());
        m_writer.WriteLine("HE_SCHEMA_DECL_INTERFACE(" HE_ID_FMT ", " HE_ID_FMT ");", decl.GetId(), decl.GetParentId());

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteStructDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        WriteTemplate(decl);
        m_writer.WriteLine("struct {} final", decl.GetName().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{}() = delete;", decl.GetName().AsView());
        m_writer.WriteLine("HE_SCHEMA_DECL_STRUCT(" HE_ID_FMT ", " HE_ID_FMT ", {}, {}, {});",
            decl.GetId(), decl.GetParentId(), structDecl.GetDataFieldCount(), structDecl.GetDataWordSize(), structDecl.GetPointerCount());

        if (!structDecl.GetFields().IsEmpty())
        {
            m_writer.Write('\n');
            m_writer.WriteLine("class Reader;");
            m_writer.WriteLine("class Builder;");
        }

        for (Declaration::Reader child : decl.GetChildren())
        {
            m_writer.Write('\n');
            WriteDecl(child, decl);
        }

        if (structDecl.GetIsUnion())
        {
            m_writer.WriteLine("enum class UnionTag : uint16_t");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            he::String upperCamelName(Allocator::GetTemp());
            for (Field::Reader field : structDecl.GetFields())
            {
                upperCamelName = field.GetName();
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteLine("{} = {},", upperCamelName, field.GetUnionTag());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        switch (decl.GetData().GetUnionTag())
        {
            case Declaration::Data::UnionTag::File:
            case Declaration::Data::UnionTag::Attribute:
            case Declaration::Data::UnionTag::Constant:
            case Declaration::Data::UnionTag::Enum:
                break;
            case Declaration::Data::UnionTag::Interface:
                WriteInterfaceImpl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Struct:
                WriteStructImpl(decl, scope);
                break;
        }
    }

    void CodeGenCpp::WriteInterfaceImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.GetData().IsInterface());
        Declaration::Data::Interface::Reader interfaceDecl = decl.GetData().GetInterface();

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteImpl(child, scope);
        }

        WriteTemplate(decl);
        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);

        Type::Data::Reader superTypeData = interfaceDecl.GetSuper().GetData();
        Type::Data::Interface::Reader superInterface = superTypeData.IsInterface() ? superTypeData.GetInterface() : Type::Data::Interface::Reader{};

        if (superInterface.IsValid())
        {
            Declaration::Reader super = m_request.GetDecl(superInterface.GetId());
            m_writer.Write(" : public ");
            WriteName(super, scope, superInterface.GetBrand(), ReaderSuffix);
        }
        m_writer.Write('\n');
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("virtual ~{}() {{}}", decl.GetName().AsView());
        if (superInterface.IsValid())
        {
            Declaration::Reader super = m_request.GetDecl(superInterface.GetId());
            m_writer.WriteIndent();
            m_writer.Write("using SuperType = ");
            WriteName(super, scope, superInterface.GetBrand(), ReaderSuffix);
            m_writer.Write(";\n");
        }
        m_writer.Write('\n');

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteDecl(child, decl);
        }

        for (Method::Reader method : interfaceDecl.GetMethods())
        {
            Declaration::Reader params = m_request.GetDecl(method.GetParamStruct());
            Declaration::Reader result = m_request.GetDecl(method.GetResultStruct());
            m_writer.WriteLine("virtual {}::Reader {}({}::Reader) = 0;", result.GetName().AsView(), method.GetName().AsView(), params.GetName().AsView());
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteStructImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.GetData().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteImpl(child, scope);
        }

        if (structDecl.GetFields().IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write("::Reader final : public ::he::schema::StructReader\n");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteIndent();
        m_writer.Write("using StructType = ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write(";\n");
        m_writer.WriteLine("using SuperType = ::he::schema::StructReader;\n");
        m_writer.WriteLine("static constexpr bool IsSchemaReader = true;");

        if (structDecl.GetIsUnion())
        {
            //m_writer.WriteLine("bool HasUnionTag() {{ return SuperType::HasDataField({}); }}", structDecl.GetUnionTagOffset());
            m_writer.WriteLine("UnionTag GetUnionTag() const {{ return SuperType::GetDataField<UnionTag>({}); }}\n", structDecl.GetUnionTagOffset());
        }

        for (Field::Reader field : structDecl.GetFields())
        {
            WriteFieldGetDecl(field, decl, true);
            m_writer.Write('\n');
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");

        m_writer.WriteIndent();
        m_writer.Write("class ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write("::Builder final : public ::he::schema::StructBuilder\n");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteIndent();
        m_writer.Write("using StructType = ");
        WriteName(decl, scope, {}, nullptr);
        m_writer.Write(";\n");

        m_writer.WriteLine("using SuperType = ::he::schema::StructBuilder;\n");
        m_writer.WriteLine("StructType::Reader AsReader() const { return StructType::Reader(SuperType::AsReader()); }");
        m_writer.WriteLine("operator StructType::Reader() const { return AsReader(); }");

        if (structDecl.GetIsUnion())
        {
            m_writer.Write('\n');
            //m_writer.WriteLine("bool HasUnionTag() {{ return SuperType::HasDataField({}); }}", structDecl.GetUnionTagOffset());
            m_writer.WriteLine("UnionTag GetUnionTag() const {{ return SuperType::GetDataField<UnionTag>({}); }}\n", structDecl.GetUnionTagOffset());
            m_writer.WriteLine("void SetUnionTag(UnionTag t) {{ SuperType::SetDataField({}, t); }}", structDecl.GetUnionTagOffset());
        }

        for (Field::Reader field : structDecl.GetFields())
        {
            m_writer.Write('\n');
            WriteFieldGetDecl(field, decl, false);
            WriteFieldSetDecl(field, decl);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteFieldImpl(Declaration::Reader decl, Declaration::Reader scope)
    {
        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteFieldImpl(child, scope);
        }

        if (!decl.GetData().IsStruct())
            return;

        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        for (Field::Reader field : structDecl.GetFields())
        {
            m_writer.Write('\n');
            WriteFieldGetImpl(field, decl, scope, true);
        }

        for (Field::Reader field : structDecl.GetFields())
        {
            m_writer.Write('\n');
            WriteFieldGetImpl(field, decl, scope, false);
            WriteFieldSetImpl(field, decl, scope);
        }
    }

    void CodeGenCpp::WriteFieldGetDecl(Field::Reader field, Declaration::Reader decl, bool isReader)
    {
        HE_ASSERT(decl.GetData().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        he::String upperCamelName(field.GetName(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        const char* suffix = isReader ? ReaderSuffix : BuilderSuffix;

        if (structDecl.GetIsUnion())
        {
            m_writer.WriteLine("bool Is{}() const;", upperCamelName);
        }

        if (field.GetMeta().IsUnion() || field.GetMeta().IsGroup())
        {
            m_writer.WriteLine("{0}{1} Get{0}() const;", upperCamelName, suffix);
            return;
        }

        Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
        Type::Reader fieldType = norm.GetType();
        Type::Data::Reader fieldTypeData = fieldType.GetData();

        if (fieldTypeData.IsVoid())
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName, field.GetMeta().GetNormal().GetIndex());
            m_writer.WriteLine("::he::schema::Void Get{}() const;", upperCamelName);
        }
        else if (IsPointer(fieldType))
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName);

            m_writer.WriteIndent();
            WriteType(fieldType, decl, suffix);
            m_writer.Write(" Get{}() const;\n", upperCamelName);
        }
        else
        {
            m_writer.WriteLine("bool Has{}() const;", upperCamelName);

            const bool isArray = fieldTypeData.IsArray();

            m_writer.WriteIndent();
            if (isArray)
            {
                m_writer.Write("::he::Span<");
                if (isReader)
                    m_writer.Write("const ");
                WriteType(fieldTypeData.GetArray().GetElementType(), decl, nullptr);
                m_writer.Write(">");
            }
            else
            {
                WriteType(fieldType, decl, nullptr);
            }
            if (!isArray || isReader)
                m_writer.Write(" Get{}() const;\n", upperCamelName);
            else
                m_writer.Write(" Get{}();\n", upperCamelName);
        }
    }

    void CodeGenCpp::WriteFieldGetImpl(Field::Reader field, Declaration::Reader decl, Declaration::Reader scope, bool isReader)
    {
        HE_ASSERT(decl.GetData().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        he::String upperCamelName(field.GetName(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        const char* suffix = isReader ? ReaderSuffix : BuilderSuffix;

        if (structDecl.GetIsUnion())
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, m_root, {}, suffix);
            m_writer.Write("{0}::Is{1}() const {{ return GetUnionTag() == UnionTag::{1}; }}\n", suffix, upperCamelName);
        }

        if (field.GetMeta().IsGroup() || field.GetMeta().IsUnion())
        {
            TypeId groupTypeId = field.GetMeta().IsGroup() ? field.GetMeta().GetGroup().GetTypeId() : field.GetMeta().GetUnion().GetTypeId();
            Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteName(groupType, scope, {}, suffix);
            m_writer.Write(suffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Get{}() const {{ ", suffix, upperCamelName);
            if (structDecl.GetIsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);
            m_writer.Write("return {}{}(*this); }}\n", upperCamelName, suffix);
            return;
        }

        Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
        Type::Reader fieldType = norm.GetType();
        Type::Data::Reader fieldTypeData = fieldType.GetData();

        if (fieldTypeData.IsVoid())
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return false; }}\n", suffix, upperCamelName);

            m_writer.WriteIndent();
            m_writer.Write("inline ::he::schema::Void ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Get{}() const {{ ", suffix, upperCamelName);
            if (structDecl.GetIsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);
            m_writer.Write("return {}; }\n");
        }
        else if (IsPointer(fieldType))
        {

            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return ", suffix, upperCamelName);
            if (structDecl.GetIsUnion())
                m_writer.Write("Is{0}() && ", upperCamelName);
            m_writer.Write("SuperType::HasPointerField({}); }}\n", norm.GetIndex());

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteType(fieldType, scope, suffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Get{}() const {{ ", suffix, upperCamelName);

            if (structDecl.GetIsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            const bool isArray = fieldTypeData.IsArray();
            const bool hasDefault = isReader && norm.HasDefaultValue();

            if (isArray)
            {
                m_writer.Write("return SuperType::TryGetPointerArrayField<");
                WriteType(fieldTypeData.GetArray().GetElementType(), scope, nullptr);
                m_writer.Write(">({}, {}", norm.GetIndex(), fieldTypeData.GetArray().GetSize());
                if (hasDefault)
                    m_writer.Write(", ");
            }
            else if (fieldTypeData.IsAnyPointer() || fieldTypeData.IsAnyStruct() || fieldTypeData.IsAnyList())
            {
                HE_ASSERT(!hasDefault);
                m_writer.Write("return SuperType::GetPointerField({}", norm.GetIndex());
            }
            else
            {
                const Type::Data::UnionTag getterKind = fieldTypeData.IsBlob() ? Type::Data::UnionTag::List : fieldTypeData.GetUnionTag();
                m_writer.Write("return SuperType::GetPointerField({}).TryGet{:s}", norm.GetIndex(), getterKind);
                if (fieldTypeData.IsBlob())
                {
                    m_writer.Write("<uint8_t>");
                }
                else if (!fieldTypeData.IsString())
                {
                    Type::Reader t = fieldTypeData.IsList() ? fieldTypeData.GetList().GetElementType() : norm.GetType();
                    m_writer.Write("<");
                    WriteType(t, scope, nullptr);
                    m_writer.Write('>');
                }
                m_writer.Write('(');
            }

            if (hasDefault)
            {
                const Value::Data::Reader defaultValueData = norm.GetDefaultValue().GetData();
                const Word* defaultValuePtrWords = defaultValueData.IsStruct() ? defaultValueData.GetStruct().Data() : defaultValueData.GetList().Data();
                const uint64_t offset = defaultValuePtrWords - m_root.Data();
                m_writer.Write("::he::schema::DeclInfoForId<" HE_ID_FMT ">::Value.schema + {}",
                    m_root.GetId(), offset);
            }
            m_writer.Write("); }\n");
        }
        else
        {
            m_writer.WriteIndent();
            m_writer.Write("inline bool ");
            WriteName(decl, scope, {}, suffix);
            m_writer.Write("{}::Has{}() const {{ return ", suffix, upperCamelName);
            if (structDecl.GetIsUnion())
                m_writer.Write("Is{0}() && ", upperCamelName);
            m_writer.Write("SuperType::HasDataField({}); }}\n", norm.GetIndex());

            const bool isArray = fieldTypeData.IsArray();
            const bool hasDefault = (isReader || !isArray) && norm.HasDefaultValue();

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            if (isArray)
            {
                m_writer.Write("::he::Span<");
                if (isReader)
                    m_writer.Write("const ");
                WriteType(fieldTypeData.GetArray().GetElementType(), scope, nullptr);
                m_writer.Write("> ");
            }
            else
            {
                WriteType(fieldType, scope, nullptr);
                m_writer.Write(' ');
            }
            WriteName(decl, scope, {}, suffix);
            if (!isArray || isReader)
                m_writer.Write("{}::Get{}() const {{ ", suffix, upperCamelName);
            else
                m_writer.Write("{}::Get{}() {{ ", suffix, upperCamelName);

            if (structDecl.GetIsUnion())
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            if (isArray)
            {
                if (isReader)
                    m_writer.Write("return SuperType::TryGetDataArrayField<");
                else
                    m_writer.Write("return SuperType::GetAndMarkDataArrayField<");
                WriteType(fieldTypeData.GetArray().GetElementType(), scope, nullptr);
            }
            else
            {
                m_writer.Write("return SuperType::{}GetDataField<",
                    structDecl.GetIsUnion() ? "" : "Try");
                WriteType(fieldType, scope, nullptr);
            }

            if (structDecl.GetIsUnion() && !isArray)
                m_writer.Write(">({}", norm.GetDataOffset());
            else
                m_writer.Write(">({}, {}", norm.GetIndex(), norm.GetDataOffset());

            if (isArray)
            {
                m_writer.Write(", {}", fieldTypeData.GetArray().GetSize());
                if (hasDefault)
                {
                    m_writer.Write(", ");
                    const Value::Data::Reader defaultValueData = norm.GetDefaultValue().GetData();
                    const Word* defaultValuePtrWords = defaultValueData.GetList().Data();
                    const uint64_t offset = defaultValuePtrWords - m_root.Data();
                    m_writer.Write("::he::schema::DeclInfoForId<" HE_ID_FMT ">::Value.schema + {}",
                        m_root.GetId(), offset);
                }
            }
            else if (hasDefault)
            {
                m_writer.Write(", ");
                WriteDataValue(norm.GetType(), decl, norm.GetDefaultValue());
            }
            m_writer.Write("); }\n");
        }
    }

    void CodeGenCpp::WriteFieldSetDecl(Field::Reader field, Declaration::Reader decl)
    {
        HE_ASSERT(decl.GetData().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        he::String upperCamelName(field.GetName(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        if (field.GetMeta().IsGroup() || field.GetMeta().IsUnion())
        {
            if (structDecl.GetIsUnion())
            {
                TypeId groupTypeId = field.GetMeta().IsGroup() ? field.GetMeta().GetGroup().GetTypeId() : field.GetMeta().GetUnion().GetTypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                m_writer.WriteIndent();
                WriteName(groupType, decl, {}, BuilderSuffix);
                m_writer.Write(BuilderSuffix);
                m_writer.Write(' ');
                m_writer.Write("Init{}();\n", upperCamelName);
            }
            return;
        }

        Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
        Type::Reader fieldType = norm.GetType();
        Type::Data::Reader fieldTypeData = fieldType.GetData();
        const bool fieldIsPointer = IsPointer(fieldType);

        if (!fieldIsPointer && fieldTypeData.IsArray())
            return;

        m_writer.WriteIndent();
        m_writer.Write("void Set{}(", upperCamelName);
        if (!fieldTypeData.IsVoid())
        {
            WriteType(fieldType, decl, ReaderSuffix);
            m_writer.Write(" value");
        }
        m_writer.Write(");\n");

        if (fieldIsPointer)
        {
            const bool fieldIsString = fieldTypeData.IsString();
            const bool fieldIsList = fieldTypeData.IsList() || fieldTypeData.IsBlob();

            m_writer.WriteIndent();
            WriteType(fieldType, decl, BuilderSuffix);
            m_writer.Write(" Init{}(", upperCamelName);
            if (fieldIsList)
                m_writer.Write("uint32_t size");
            else if (fieldIsString)
                m_writer.Write("::he::StringView str");
            m_writer.Write(");\n");
        }
    }

    void CodeGenCpp::WriteFieldSetImpl(Field::Reader field, Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.GetData().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        he::String upperCamelName(field.GetName(), Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        if (field.GetMeta().IsGroup() || field.GetMeta().IsUnion())
        {
            if (structDecl.GetIsUnion())
            {
                TypeId groupTypeId = field.GetMeta().IsGroup() ? field.GetMeta().GetGroup().GetTypeId() : field.GetMeta().GetUnion().GetTypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                m_writer.WriteIndent();
                m_writer.Write("inline ");
                WriteName(groupType, scope, {}, BuilderSuffix);
                m_writer.Write(BuilderSuffix);
                m_writer.Write(' ');
                WriteName(decl, scope, {}, BuilderSuffix);
                m_writer.Write("::Builder::Init{0}() {{ SetUnionTag(UnionTag::{0}); ", upperCamelName);
                if (field.GetMeta().IsGroup())
                {
                    WriteGroupFieldClear(groupType, decl);
                }
                m_writer.Write("return {}{}(*this); }}\n", upperCamelName, BuilderSuffix);
            }
            return;
        }

        Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
        Type::Reader fieldType = norm.GetType();
        Type::Data::Reader fieldTypeData = fieldType.GetData();
        const bool fieldIsPointer = IsPointer(fieldType);

        if (!fieldIsPointer && fieldTypeData.IsArray())
            return;

        m_writer.WriteIndent();
        m_writer.Write("inline void ");
        WriteName(decl, scope, {}, BuilderSuffix);
        m_writer.Write("::Builder::Set{}(", upperCamelName);
        if (!fieldTypeData.IsVoid())
        {
            WriteType(fieldType, scope, ReaderSuffix);
            m_writer.Write(" value");
        }
        m_writer.Write(") { ");
        if (structDecl.GetIsUnion())
            m_writer.Write("SetUnionTag(UnionTag::{}); ", upperCamelName);
        if (fieldIsPointer)
        {
            m_writer.Write("SuperType::GetPointerField({}).Set(value); ", norm.GetIndex());
        }
        else if (!fieldTypeData.IsVoid())
        {
            m_writer.Write("SuperType::{}<",
                structDecl.GetIsUnion() ? "SetDataField" : "SetAndMarkDataField");
            WriteType(fieldType, scope, nullptr);
            if (structDecl.GetIsUnion())
                m_writer.Write(">({}, value); ", norm.GetDataOffset());
            else
                m_writer.Write(">({}, {}, value); ", norm.GetIndex(), norm.GetDataOffset());
        }
        m_writer.Write("}\n");

        if (fieldIsPointer)
        {
            const bool fieldIsString = fieldTypeData.IsString();
            const bool fieldIsList = fieldTypeData.IsList() || fieldTypeData.IsBlob();

            m_writer.WriteIndent();
            m_writer.Write("inline ");
            WriteType(fieldType, scope, BuilderSuffix);
            m_writer.Write(' ');
            WriteName(decl, scope, {}, BuilderSuffix);
            m_writer.Write("::Builder::Init{}(", upperCamelName);
            if (fieldIsList)
                m_writer.Write("uint32_t size");
            else if (fieldIsString)
                m_writer.Write("::he::StringView str");
            m_writer.Write(") { ");
            if (structDecl.GetIsUnion())
                m_writer.Write("SetUnionTag(UnionTag::{}); ", upperCamelName);

            const Type::Data::UnionTag getterKind = fieldTypeData.IsBlob() ? Type::Data::UnionTag::List : fieldTypeData.GetUnionTag();
            if (fieldTypeData.IsAnyPointer() || fieldTypeData.IsAnyStruct() || fieldTypeData.IsAnyList())
            {
                m_writer.Write("return SuperType::GetPointerField({}); }}\n", norm.GetIndex());
            }
            else
            {
                m_writer.Write("auto v = m_builder->Add{:s}", getterKind);
                if (fieldTypeData.IsBlob())
                {
                    m_writer.Write("<uint8_t>");
                }
                else if (!fieldTypeData.IsString())
                {
                    Type::Reader t = fieldTypeData.IsList() ? fieldTypeData.GetList().GetElementType() : fieldType;
                    m_writer.Write("<");
                    WriteType(t, scope, nullptr);
                    m_writer.Write('>');
                }
                m_writer.Write('(');
                if (fieldIsList)
                    m_writer.Write("size");
                else if (fieldIsString)
                    m_writer.Write("str");
                m_writer.Write("); SuperType::GetPointerField({}).Set(v); return v; }}\n", norm.GetIndex());
            }
        }
    }

    void CodeGenCpp::WriteGroupFieldClear(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.GetData().IsStruct());
        Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        for (Field::Reader field : structDecl.GetFields())
        {
            if (field.GetMeta().IsGroup() || field.GetMeta().IsUnion())
            {
                TypeId groupTypeId = field.GetMeta().IsGroup() ? field.GetMeta().GetGroup().GetTypeId() : field.GetMeta().GetUnion().GetTypeId();
                Declaration::Reader groupType = m_request.GetDecl(groupTypeId);
                WriteGroupFieldClear(groupType, scope);
                continue;
            }

            he::String upperCamelName(field.GetName(), Allocator::GetTemp());
            upperCamelName[0] = ToUpper(upperCamelName[0]);

            Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
            Type::Reader fieldType = norm.GetType();
            const bool fieldIsPointer = IsPointer(fieldType);

            if (fieldIsPointer)
            {
                m_writer.Write("SuperType::ClearPointerField({}); ", norm.GetIndex());
            }
            else
            {
                m_writer.Write("SuperType::ClearDataField({}); ", norm.GetIndex());
            }
        }
    }

    void CodeGenCpp::GenSource()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");

        // headers
        StringView baseName = GetPathWithoutExtension(m_request.fileName);
        m_writer.WriteLine("#include \"{}.hsc.h\"\n", baseName);
        m_writer.WriteLine("#include \"he/core/enum_ops.h\"", baseName);
        m_writer.WriteLine("#include \"he/core/types.h\"\n", baseName);

        m_writer.WriteLine("namespace he::schema");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        WriteRawSchemaData();
        WriteDeclInfoSrc(m_root);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        m_writer.WriteLine("namespace he");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        WriteEnumStrings(m_root);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::WriteRawSchemaData()
    {
        m_writer.WriteLine("static const Word RawFileSchema_{:016x}[] =", m_root.GetId());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();
        m_writer.WriteIndent();
        const uint32_t size = m_request.schemaData.Size();
        for (uint32_t i = 0; i < size; ++i)
        {
            if (i > 0)
            {
                if ((i % 10) == 0)
                {
                    m_writer.Write('\n');
                    m_writer.WriteIndent();
                }
                else
                {
                    m_writer.Write(' ');
                }
            }
            m_writer.Write("{:#018x}ull,", m_request.schemaData[i]);
        }
        m_writer.Write('\n');
        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");
    }

    void CodeGenCpp::WriteDeclInfoSrc(Declaration::Reader decl)
    {
        const ptrdiff_t schemaOffset = static_cast<StructReader&>(decl).Data() - m_request.schemaData.Data();

        m_writer.WriteIndent();
        m_writer.Write("// ");
        if (decl.GetData().IsFile())
            m_writer.Write("file");
        else
            WriteName(decl, m_root, {}, nullptr);
        m_writer.Write('\n');

        const bool isStruct = decl.GetData().IsStruct();
        const uint16_t dataFieldCount = isStruct ? decl.GetData().GetStruct().GetDataFieldCount() : 0;
        const uint16_t dataWordSize = isStruct ? decl.GetData().GetStruct().GetDataWordSize() : 0;
        const uint16_t pointerCount = isStruct ? decl.GetData().GetStruct().GetPointerCount() : 0;

        std::set<TypeId> dependencies;
        dependencies.insert(decl.GetParentId()); // always list parent scope as a dependency type to make it easy to find.
        FindAllDependencies(decl, dependencies);

        if (!dependencies.empty())
        {
            m_writer.WriteLine("static const DeclInfo* Dependencies_{:016x}[] =", decl.GetId());
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
            for (TypeId id : dependencies)
            {
                m_writer.WriteLine("&DeclInfoForId<" HE_ID_FMT ">::Value,", id);
            }
            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
        }

        m_writer.WriteLine("const DeclInfo DeclInfoForId<" HE_ID_FMT ">::Value =", decl.GetId());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine(HE_ID_FMT ", " HE_ID_FMT ", DeclKind::{:s}, {}, {}, {}, (RawFileSchema_{:016x} + {}),",
            decl.GetId(), decl.GetParentId(), decl.GetData().GetUnionTag(), dataFieldCount, dataWordSize, pointerCount, m_root.GetId(), schemaOffset);

        if (!dependencies.empty())
            m_writer.WriteLine("Dependencies_{:016x}, HE_LENGTH_OF(Dependencies_{:016x}),", decl.GetId(), decl.GetId());
        else
            m_writer.WriteLine("nullptr, 0,");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteDeclInfoSrc(child);
        }
    }

    void CodeGenCpp::WriteEnumStrings(Declaration::Reader decl)
    {
        if (decl.GetData().IsEnum())
        {
            const Declaration::Data::Enum::Reader enumDecl = decl.GetData().GetEnum();

            m_writer.WriteLine("template <>");

            m_writer.WriteIndent();
            m_writer.Write("const char* AsString(");
            WriteName(decl, {}, {}, nullptr);
            m_writer.Write(" x)\n");

            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("switch (x)");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            for (const Enumerator::Reader e : enumDecl.GetEnumerators())
            {
                m_writer.WriteIndent();
                m_writer.Write("case ");
                WriteName(decl, {}, {}, nullptr);
                m_writer.Write("::{0}: return \"{0}\";\n", e.GetName().AsView());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");

            m_writer.WriteLine("return \"<unknown>\";");

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        else if (decl.GetData().IsStruct() && decl.GetData().GetStruct().GetIsUnion())
        {
            Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

            m_writer.WriteLine("template <>");

            m_writer.WriteIndent();
            m_writer.Write("const char* AsString(");
            WriteName(decl, {}, {}, nullptr);
            m_writer.Write("::UnionTag x)\n");

            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("switch (x)");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            he::String upperCamelName(Allocator::GetTemp());
            for (const Field::Reader f : structDecl.GetFields())
            {
                upperCamelName = f.GetName();
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteIndent();
                m_writer.Write("case ");
                WriteName(decl, {}, {}, nullptr);
                m_writer.Write("::UnionTag::{0}: return \"{0}\";\n", upperCamelName);
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");

            m_writer.WriteLine("return \"<unknown>\";");

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteEnumStrings(child);
        }
    }

    bool CodeGenCpp::FlushToFile(const char* suffix)
    {
        he::String filePath(m_request.outDir, Allocator::GetTemp());
        ConcatPath(filePath, m_request.fileName);
        RemoveExtension(filePath);
        filePath += suffix;

        const StringView code = m_writer.Str();

        File f;
        if (!f.Open(filePath.Data(), FileOpenMode::WriteTruncate))
            return false;

        if (!f.Write(code.Data(), code.Size()))
            return false;

        return true;
    }

    void CodeGenCpp::WriteDeclInfo(Declaration::Reader decl)
    {
        m_writer.WriteIndent();
        m_writer.Write("HE_SCHEMA_DECL_INFO_FOR_ID(" HE_ID_FMT "); // ", decl.GetId());
        if (decl.GetData().IsFile())
            m_writer.Write("file");
        else
            WriteName(decl, m_root, {}, nullptr);
        m_writer.Write('\n');

        if (decl.GetData().IsEnum())
        {
            Declaration::Data::Enum::Reader enumDecl = decl.GetData().GetEnum();

            m_writer.WriteLine("enum class {}_{:016x} : uint16_t", decl.GetName().AsView(), decl.GetId());
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            for (Enumerator::Reader e : enumDecl.GetEnumerators())
            {
                m_writer.WriteLine("{} = {},", e.GetName().AsView(), e.GetOrdinal());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
            m_writer.WriteLine("HE_SCHEMA_DECL_ENUM({}_{:016x}, " HE_ID_FMT ", " HE_ID_FMT ");",
                decl.GetName().AsView(), decl.GetId(), decl.GetId(), decl.GetParentId());
        }

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteDeclInfo(child);
        }
    }

    void CodeGenCpp::WriteName(Declaration::Reader decl, Declaration::Reader scope, Brand::Reader brand, const char* pointerSuffix)
    {
        if (!scope.IsValid() || (decl.GetParentId() != scope.GetId() && decl.GetParentId() != scope.GetParentId()))
        {
            Declaration::Reader parent = m_request.GetDecl(decl.GetParentId());
            if (!parent.GetData().IsFile())
            {
                WriteName(parent, scope, brand, pointerSuffix);
                m_writer.Write("::");
            }
            else if (!scope.IsValid())
            {
                StringView nameSpace = parent.GetId() == m_root.GetId() ? m_root.GetName() : parent.GetName();
                m_writer.Write("::");
                WriteWithReplace(nameSpace, '.', "::");
                m_writer.Write("::");
            }
            else if (parent.GetId() != m_root.GetId() && m_root.GetName() != parent.GetName())
            {
                m_writer.Write("::");
                WriteWithReplace(parent.GetName().AsView(), '.', "::");
                m_writer.Write("::");
            }
        }

        m_writer.Write(decl.GetName());

        for (Brand::Scope::Reader brandScope : brand.GetScopes())
        {
            if (brandScope.GetScopeId() == decl.GetId())
            {
                List<Type>::Reader params = brandScope.GetParams();

                m_writer.Write("<");
                for (uint32_t i = 0; i < params.Size(); ++i)
                {
                    Type::Reader t = params[i];
                    WriteType(t, scope, pointerSuffix);
                    if (i < (params.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(">");
                break;
            }
        }
    }

    void CodeGenCpp::WriteTemplate(Declaration::Reader decl)
    {
        List<String>::Reader typeParams = decl.GetTypeParams();

        if (typeParams.IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("template <");
        for (uint32_t i = 0; i < typeParams.Size(); ++i)
        {
            m_writer.Write("typename ");
            m_writer.Write(typeParams[i]);
            if (i < (typeParams.Size() - 1))
                m_writer.Write(", ");
        }
        m_writer.Write(">\n");
    }

    void CodeGenCpp::WriteType(Type::Reader type, Declaration::Reader scope, const char* pointerSuffix)
    {
        switch (type.GetData().GetUnionTag())
        {
            case Type::Data::UnionTag::Void: m_writer.Write("::he::schema::Void"); break;
            case Type::Data::UnionTag::Bool: m_writer.Write("bool"); break;
            case Type::Data::UnionTag::Int8: m_writer.Write("int8_t"); break;
            case Type::Data::UnionTag::Int16: m_writer.Write("int16_t"); break;
            case Type::Data::UnionTag::Int32: m_writer.Write("int32_t"); break;
            case Type::Data::UnionTag::Int64: m_writer.Write("int64_t"); break;
            case Type::Data::UnionTag::Uint8: m_writer.Write("uint8_t"); break;
            case Type::Data::UnionTag::Uint16: m_writer.Write("uint16_t"); break;
            case Type::Data::UnionTag::Uint32: m_writer.Write("uint32_t"); break;
            case Type::Data::UnionTag::Uint64: m_writer.Write("uint64_t"); break;
            case Type::Data::UnionTag::Float32: m_writer.Write("float"); break;
            case Type::Data::UnionTag::Float64: m_writer.Write("double"); break;
            case Type::Data::UnionTag::Blob:
            {
                m_writer.Write("::he::schema::Blob");
                break;
            }
            case Type::Data::UnionTag::String:
            {
                m_writer.Write("::he::schema::String");
                break;
            }
            case Type::Data::UnionTag::Array:
            {
                Type::Data::Array::Reader arrayType = type.GetData().GetArray();
                m_writer.Write("::he::schema::List<");
                WriteType(arrayType.GetElementType(), scope, nullptr);
                m_writer.Write(">");
                break;
            }
            case Type::Data::UnionTag::List:
            {
                Type::Data::List::Reader listType = type.GetData().GetList();
                m_writer.Write("::he::schema::List<");
                WriteType(listType.GetElementType(), scope, nullptr);
                m_writer.Write(">");
                break;
            }
            case Type::Data::UnionTag::Enum:
            {
                Type::Data::Enum::Reader enumType = type.GetData().GetEnum();
                Declaration::Reader decl = m_request.GetDecl(enumType.GetId());
                HE_ASSERT(decl.GetData().IsEnum());
                WriteName(decl, scope, enumType.GetBrand(), nullptr);
                break;
            }
            case Type::Data::UnionTag::Struct:
            {
                Type::Data::Struct::Reader structType = type.GetData().GetStruct();
                Declaration::Reader decl = m_request.GetDecl(structType.GetId());
                HE_ASSERT(decl.GetData().IsStruct());
                WriteName(decl, scope, structType.GetBrand(), nullptr);
                break;
            }
            case Type::Data::UnionTag::Interface:
            {
                Type::Data::Interface::Reader interfaceType = type.GetData().GetInterface();
                Declaration::Reader decl = m_request.GetDecl(interfaceType.GetId());
                HE_ASSERT(decl.GetData().IsInterface());
                WriteName(decl, scope, interfaceType.GetBrand(), nullptr);
                break;
            }
            case Type::Data::UnionTag::Parameter:
            {
                Type::Data::Parameter::Reader param = type.GetData().GetParameter();
                Declaration::Reader decl = m_request.GetDecl(param.GetScopeId());
                m_writer.Write(decl.GetTypeParams()[param.GetIndex()]);
                break;
            }
            case Type::Data::UnionTag::AnyPointer:
            {
                m_writer.Write("::he::schema::AnyPointer");
                break;
            }
            case Type::Data::UnionTag::AnyStruct:
            {
                m_writer.Write("::he::schema::AnyStruct");
                break;
            }
            case Type::Data::UnionTag::AnyList:
            {
                m_writer.Write("::he::schema::AnyList");
                break;
            }
        }

        if (pointerSuffix && IsPointer(type))
        {
            m_writer.Write(pointerSuffix);
        }
    }

    void CodeGenCpp::WriteDataValue(Type::Reader type, Declaration::Reader scope, Value::Reader value)
    {
        switch (value.GetData().GetUnionTag())
        {
            case Value::Data::UnionTag::Void: m_writer.Write("{}"); break;
            case Value::Data::UnionTag::Bool: m_writer.Write("{}", value.GetData().GetBool()); break;
            case Value::Data::UnionTag::Int8: m_writer.Write("{}", value.GetData().GetInt8()); break;
            case Value::Data::UnionTag::Int16: m_writer.Write("{}", value.GetData().GetInt16()); break;
            case Value::Data::UnionTag::Int32: m_writer.Write("{}", value.GetData().GetInt32()); break;
            case Value::Data::UnionTag::Int64: m_writer.Write("{}", value.GetData().GetInt64()); break;
            case Value::Data::UnionTag::Uint8: m_writer.Write("{}", value.GetData().GetUint8()); break;
            case Value::Data::UnionTag::Uint16: m_writer.Write("{}", value.GetData().GetUint16()); break;
            case Value::Data::UnionTag::Uint32: m_writer.Write("{}", value.GetData().GetUint32()); break;
            case Value::Data::UnionTag::Uint64: m_writer.Write("{}", value.GetData().GetUint64()); break;
            case Value::Data::UnionTag::Float32: m_writer.Write("{}", value.GetData().GetFloat32()); break;
            case Value::Data::UnionTag::Float64: m_writer.Write("{}", value.GetData().GetFloat64()); break;
            case Value::Data::UnionTag::String:
            {
                // Technically a pointer value, but sometimes we use it like a data value (like for constants).
                HE_ASSERT(type.GetData().IsString());

                const String::Reader str = value.GetData().GetString();
                m_writer.Write("\"{}\"", str.AsView());
                break;
            }
            case Value::Data::UnionTag::Enum:
            {
                HE_ASSERT(type.GetData().IsEnum());
                Type::Data::Enum::Reader enumType = type.GetData().GetEnum();
                Declaration::Reader decl = m_request.GetDecl(enumType.GetId());

                HE_ASSERT(decl.GetData().IsEnum());
                Declaration::Data::Enum::Reader enumDecl = decl.GetData().GetEnum();

                WriteName(decl, scope, enumType.GetBrand(), nullptr);
                m_writer.Write("::");
                for (Enumerator::Reader e : enumDecl.GetEnumerators())
                {
                    if (e.GetOrdinal() == value.GetData().GetEnum())
                    {
                        m_writer.Write(e.GetName());
                        break;
                    }
                }
                break;
            }
            case Value::Data::UnionTag::Blob:
            case Value::Data::UnionTag::List:
            case Value::Data::UnionTag::Struct:
                HE_ASSERT(false, HE_MSG("Invalid value kind. Expected a non-pointer value."));
                break;
        }
    }

    void CodeGenCpp::WriteWithReplace(StringView input, char what, StringView with)
    {
        for (char ch : input)
        {
            if (ch == what)
            {
                m_writer.Write(with);
            }
            else
            {
                m_writer.Write(ch);
            }
        }
    }

    void CodeGenCpp::FindAllDependencies(Type::Reader type, std::set<TypeId>& out)
    {
        switch (type.GetData().GetUnionTag())
        {
            case Type::Data::UnionTag::Struct:
                out.insert(type.GetData().GetStruct().GetId());
                break;
            case Type::Data::UnionTag::Enum:
                out.insert(type.GetData().GetEnum().GetId());
                break;
            case Type::Data::UnionTag::Interface:
                out.insert(type.GetData().GetInterface().GetId());
                break;
            case Type::Data::UnionTag::List:
                FindAllDependencies(type.GetData().GetList().GetElementType(), out);
                break;
            case Type::Data::UnionTag::Array:
                FindAllDependencies(type.GetData().GetArray().GetElementType(), out);
                break;
            default:
                break;
        }
    }

    void CodeGenCpp::FindAllDependencies(Declaration::Reader decl, std::set<TypeId>& out)
    {
        switch (decl.GetData().GetUnionTag())
        {
            case Declaration::Data::UnionTag::Struct:
            {
                Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();
                for (Field::Reader field : structDecl.GetFields())
                {
                    switch (field.GetMeta().GetUnionTag())
                    {
                        case Field::Meta::UnionTag::Normal:
                            FindAllDependencies(field.GetMeta().GetNormal().GetType(), out);
                            break;
                        case Field::Meta::UnionTag::Group:
                            out.insert(field.GetMeta().GetGroup().GetTypeId());
                            break;
                        case Field::Meta::UnionTag::Union:
                            out.insert(field.GetMeta().GetUnion().GetTypeId());
                            break;
                    }
                }
                break;
            }
            case Declaration::Data::UnionTag::Interface:
            {
                Declaration::Data::Interface::Reader interfaceDecl = decl.GetData().GetInterface();

                Type::Data::Reader superTypeData = interfaceDecl.GetSuper().GetData();
                Type::Data::Interface::Reader superInterface = superTypeData.IsInterface() ? superTypeData.GetInterface() : Type::Data::Interface::Reader{};

                if (superInterface.IsValid())
                {
                    out.insert(superInterface.GetId());
                }

                for (Method::Reader method : interfaceDecl.GetMethods())
                {
                    out.insert(method.GetParamStruct());
                    out.insert(method.GetResultStruct());
                }
                break;
            }
            default:
                break;
        }
    }

    bool GenerateCpp(const CodeGenRequest& request)
    {
        CodeGenCpp generator(request);
        if (!generator.Generate())
            return false;

        return true;
    }
}
;
