# Copyright Chad Engler

id = "aklomp.base64"
name = "Fast Base64 Encoder/Decoder"
description = "Fast Base64 stream encoder/decoder in C99, with SIMD acceleration"
version = "0.5.0"
authors = ["Alfred Klomp"]
license = "BSD-2-Clause"
homepage = "https://github.com/aklomp/base64"

[install]
    github = "aklomp/base64#v0.5.0"

[[modules]]
    name = "libbase64"
    type = "static"
    group = "engine/contrib"
    warnings = "Off"
    cdialect = "C99"
    files = [
        # library files
        "lib/lib.c",
        "lib/codec_choose.c",
        "include/libbase64.h",
        "lib/tables/tables.c",

        # Add generated headers explicitly to target, to insert them in the dependency tree
        "lib/tables/table_dec_32bit.h",
        "lib/tables/table_enc_12bit.h",

        # codec implementations
        "lib/arch/generic/codec.c",

        "lib/arch/ssse3/codec.c",
        "lib/arch/sse41/codec.c",
        "lib/arch/sse42/codec.c",
        "lib/arch/avx/codec.c",
        "lib/arch/avx2/codec.c",

        "lib/arch/neon32/codec.c",
        "lib/arch/neon64/codec.c",
    ]
    public_includedirs = ["include"]
    public_defines = ["BASE64_STATIC_DEFINE"]
    private_includedirs = [
        "lib",
        "%{he.get_module_file_dir('libbase64')}",
    ]
