// Copyright Chad Engler

#pragma once

#include "he/core/assert.h"
#include "he/core/enum_ops.h"
#include "he/core/hash.h"
#include "he/core/types.h"
#include "he/schema/types.h"

// A bit of a circular dependency since this is generated by the schema compiler, but is
// also required to build the schema compiler. Run the `gen_reflection.sh` script to regenerate
// the reflection files if `schema.hsc` is changed.
#include "he/schema/schema.hsc.h"

namespace he::schema
{
    inline TypeId MakeTypeId(StringView name, TypeId parentId)
    {
        HE_ASSERT(HasFlag(parentId, TypeIdFlag));
        return FNV64::HashData(name.Data(), name.Size(), parentId) | TypeIdFlag;
    }

    constexpr bool IsSignedIntegral(Type::Data::Tag t)
    {
        switch (t)
        {
            case Type::Data::Tag::Int8:
            case Type::Data::Tag::Int16:
            case Type::Data::Tag::Int32:
            case Type::Data::Tag::Int64:
                return true;
            default:
                return false;
        }
    }

    constexpr bool IsUnsignedIntegral(Type::Data::Tag t)
    {
        switch (t)
        {
            case Type::Data::Tag::Uint8:
            case Type::Data::Tag::Uint16:
            case Type::Data::Tag::Uint32:
            case Type::Data::Tag::Uint64:
                return true;
            default:
                return false;
        }
    }

    constexpr bool IsIntegral(Type::Data::Tag t)
    {
        return IsSignedIntegral(t) || IsUnsignedIntegral(t);
    }

    constexpr bool IsFloat(Type::Data::Tag t)
    {
        switch (t)
        {
            case Type::Data::Tag::Float32:
            case Type::Data::Tag::Float64:
                return true;
            default:
                return false;
        }
    }

    constexpr bool IsArithmetic(Type::Data::Tag t)
    {
        return IsIntegral(t) || IsFloat(t);
    }

    constexpr bool IsPointer(Type::Data::Tag t)
    {
        switch (t)
        {
            case Type::Data::Tag::Blob:
            case Type::Data::Tag::String:
            case Type::Data::Tag::List:
            case Type::Data::Tag::Struct:
            case Type::Data::Tag::Interface:
            case Type::Data::Tag::AnyPointer:
                return true;

            default:
                return false;
        }
    }

    inline bool IsPointer(const Type::Reader& t)
    {
        if (t.GetData().IsArray())
        {
            const Type::Reader elmType = t.GetData().GetArray().GetElementType();
            HE_ASSERT(!elmType.GetData().IsArray(), HE_MSG("Arrays of arrays are not supported"));
            return IsPointer(elmType);
        }

        return IsPointer(t.GetData().GetTag());
    }

    // Returns the bit alignment requirements for a type
    inline uint32_t GetBitsInElementSize(ElementSize s)
    {
        switch (s)
        {
            case ElementSize::Void: return 0;
            case ElementSize::Bit: return 1;
            case ElementSize::Byte: return 8;
            case ElementSize::TwoBytes: return 16;
            case ElementSize::FourBytes: return 32;
            case ElementSize::EightBytes: return 64;
            case ElementSize::Pointer: return 64;
            case ElementSize::Composite: return 0;
            case ElementSize::_Count: break;
        }

        HE_ASSERT(false, HE_MSG("Unknown type kind"));
        return 0;
    }

    // Returns the bit alignment requirements for a type
    inline uint32_t GetTypeAlign(const Type::Reader& t)
    {
        switch (t.GetData().GetTag())
        {
            case Type::Data::Tag::Void: return 0;
            case Type::Data::Tag::Bool: return 1;
            case Type::Data::Tag::Int8: return 8;
            case Type::Data::Tag::Int16: return 16;
            case Type::Data::Tag::Int32: return 32;
            case Type::Data::Tag::Int64: return 64;
            case Type::Data::Tag::Uint8: return 8;
            case Type::Data::Tag::Uint16: return 16;
            case Type::Data::Tag::Uint32: return 32;
            case Type::Data::Tag::Uint64: return 64;
            case Type::Data::Tag::Float32: return 32;
            case Type::Data::Tag::Float64: return 64;
            case Type::Data::Tag::Array: return GetTypeAlign(t.GetData().GetArray().GetElementType());
            case Type::Data::Tag::Blob: return 64; // pointer
            case Type::Data::Tag::String: return 64; // pointer
            case Type::Data::Tag::List: return 64; // pointer
            case Type::Data::Tag::Enum: return 16; // uint16
            case Type::Data::Tag::Struct: return 64; // pointer
            case Type::Data::Tag::Interface: return 64; // pointer
            case Type::Data::Tag::AnyPointer: return 64; // pointer
        }

        HE_ASSERT(false, HE_MSG("Unknown type kind"));
        return 0;
    }

    // Returns the size of a type in bits
    inline uint32_t GetTypeSize(const Type::Reader& type)
    {
        const uint32_t align = GetTypeAlign(type);
        const uint32_t count = type.GetData().IsArray() ? type.GetData().GetArray().GetSize() : 1;
        return align * count;
    }

    inline ElementSize GetTypeElementSize(const Type::Reader& t)
    {
        switch (t.GetData().GetTag())
        {
            case Type::Data::Tag::Void: return ElementSize::Void;
            case Type::Data::Tag::Bool: return ElementSize::Bit;
            case Type::Data::Tag::Int8: return ElementSize::Byte;
            case Type::Data::Tag::Int16: return ElementSize::TwoBytes;
            case Type::Data::Tag::Int32: return ElementSize::FourBytes;
            case Type::Data::Tag::Int64: return ElementSize::EightBytes;
            case Type::Data::Tag::Uint8: return ElementSize::Byte;
            case Type::Data::Tag::Uint16: return ElementSize::TwoBytes;
            case Type::Data::Tag::Uint32: return ElementSize::FourBytes;
            case Type::Data::Tag::Uint64: return ElementSize::EightBytes;
            case Type::Data::Tag::Float32: return ElementSize::FourBytes;
            case Type::Data::Tag::Float64: return ElementSize::EightBytes;
            case Type::Data::Tag::Array: return GetTypeElementSize(t.GetData().GetArray().GetElementType());
            case Type::Data::Tag::Blob: return ElementSize::Pointer;
            case Type::Data::Tag::String: return ElementSize::Pointer;
            case Type::Data::Tag::List: return ElementSize::Pointer;
            case Type::Data::Tag::Enum: return ElementSize::TwoBytes;
            case Type::Data::Tag::Struct: return ElementSize::Composite;
            case Type::Data::Tag::Interface: return ElementSize::Pointer;
            case Type::Data::Tag::AnyPointer: return ElementSize::Pointer;
        }

        HE_ASSERT(false, HE_MSG("Unknown type kind"));
        return ElementSize::Void;
    }

    inline Attribute::Reader FindAttribute(List<Attribute>::Reader attributes, TypeId id)
    {
        for (Attribute::Reader attribute : attributes)
        {
            if (attribute.GetId() == id)
                return attribute;
        }

        return {};
    }

    inline Declaration::Reader GetSchema(const DeclInfo& info)
    {
        const DeclInfo& I = Declaration::DeclInfo;
        return Declaration::Reader(StructReader(info.schema, I.dataWordSize, I.pointerCount));
    }

    inline Field::Reader FindField(StringView name, Declaration::Data::Struct::Reader st)
    {
        for (Field::Reader field : st.GetFields())
        {
            if (field.GetName() == name)
                return field;
        }

        return {};
    }

    const DeclInfo* FindDependency(const DeclInfo& info, TypeId id);

    class SchemaVisitor
    {
    public:
        virtual ~SchemaVisitor() = default;

        virtual bool Visit(Declaration::Reader schema) { return VisitDecl(schema, {}); }

    protected:
        virtual bool VisitDecl(Declaration::Reader decl, Declaration::Reader scope);

        virtual bool VisitFile(Declaration::Reader decl);
        virtual bool VisitAttribute(Declaration::Reader decl, Declaration::Reader scope) { HE_UNUSED(decl, scope); return true; }
        virtual bool VisitConstant(Declaration::Reader decl, Declaration::Reader scope) { HE_UNUSED(decl, scope); return true; }

        virtual bool VisitEnum(Declaration::Reader decl, Declaration::Reader scope);
        virtual bool VisitEnumerator(Enumerator::Reader enumerator, Declaration::Reader scope) { HE_UNUSED(enumerator, scope); return true; }

        virtual bool VisitInterface(Declaration::Reader decl, Declaration::Reader scope);
        virtual bool VisitMethod(Method::Reader method, Declaration::Reader scope) { HE_UNUSED(method, scope); return true; }

        virtual bool VisitStruct(Declaration::Reader decl, Declaration::Reader scope);
        virtual bool VisitField(Field::Reader field, Declaration::Reader scope);
        virtual bool VisitNormalField(Field::Reader field, Declaration::Reader scope) { HE_UNUSED(field, scope); return true; }
        virtual bool VisitGroupField(Field::Reader field, Declaration::Reader scope) { HE_UNUSED(field, scope); return true; }
        virtual bool VisitUnionField(Field::Reader field, Declaration::Reader scope) { HE_UNUSED(field, scope); return true; }

    protected:
        Declaration::Reader m_schema;
    };
}
