# Copyright Chad Engler

id = "ocornut.imgui"
version = "1.89.5"
name = "Dear ImGUI"
description = "Dear ImGui is a bloat-free graphical user interface library for C++."
author = "Omar Cornut <contact@dearimgui.com>"
license = "MIT"
homepage = "https://github.com/ocornut/imgui"

[install]
    github = "ocornut/imgui#0ea3b87bd63ecbf359585b7c235839146e84dedb" # latest docking branch (as of v1.89.5)

[[modules]]
    name = "imgui"
    type = "static"
    group = "engine/contrib"
    files = [
        "%{path.getdirectory(he.get_plugin('ocornut.imgui')._file_path)}/imgui_user_config.h",
        "imgui_draw.cpp",
        "imgui_internal.h",
        "imgui_tables.cpp",
        "imgui_widgets.cpp",
        "imgui.cpp",
        "imgui.h",
        "imstb_rectpack.h",
        "imstb_textedit.h",
        "misc/debuggers/imgui.natstepfilter",
        "misc/debuggers/imgui.natvis",
        "misc/freetype/imgui_freetype.cpp",
        "misc/freetype/imgui_freetype.h",
    ]
    public_defines = ["IMGUI_USER_CONFIG=\"imgui_user_config.h\""]
    public_dependson = ["freetype", "he_core"]
    public_dependson_include = ["he_math"] # Need the types for the ImVec2 class extras
    public_includedirs = [
        ".",
        "%{path.getdirectory(he.get_plugin('ocornut.imgui')._file_path)}",
    ]

    [[modules.variants]]
        conditions = ["tags:internal"]
        files = [
            "imgui_demo.cpp",
        ]
