# Copyright Chad Engler

id = "ocornut.imgui"
name = "Dear ImGUI"
description = "Dear ImGui is a bloat-free graphical user interface library for C++."
version = "docking"
author = "Omar Cornut <contact@dearimgui.com>"
license = "MIT"
homepage = "https://github.com/ocornut/imgui"

[install]
    github = "ocornut/imgui#1ee252772ae9c0a971d06257bb5c89f628fa696a" # v1.87 docking branch

[[modules]]
    name = "imgui"
    type = "static"
    group = "engine/contrib"
    files = [
        "%{path.getdirectory(he.get_plugin('ocornut.imgui')._file_path)}/imgui_user_config.h",
        "imgui_demo.cpp",
        "imgui_draw.cpp",
        "imgui_internal.h",
        "imgui_tables.cpp",
        "imgui_widgets.cpp",
        "imgui.cpp",
        "imgui.h",
        "imstb_rectpack.h",
        "imstb_textedit.h",
        "imstb_truetype.h",
        "misc/debuggers/imgui.natvis",
        "misc/freetype/imgui_freetype.cpp",
        "misc/freetype/imgui_freetype.h",
    ]
    public_defines = ["IMGUI_USER_CONFIG=\"imgui_user_config.h\""]
    public_dependson = ["freetype", "he_core"]
    public_dependson_include = ["he_math"]
    public_includedirs = [
        ".",
        "%{path.getdirectory(he.get_plugin('ocornut.imgui')._file_path)}",
    ]
