# Copyright Chad Engler

id = "matusnovak.doxybook2"
name = "Doxybook2"
description = "Doxygen XML to Markdown (or JSON) converter."
version = "1.4.0"
authors = ["Matus Novak <email@matusnovak.com>"]
license = "MIT"
homepage = "https://matusnovak.github.io/doxybook2/"

[install]
    index_archive_by_host = true

    [install.archive]
        linux = "https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip"
        windows = "https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-windows-win64-v1.4.0.zip"
