// Copyright Chad Engler

#include "codegen_cpp_native.h"

#include "he/core/file.h"
#include "he/core/path.h"
#include "he/core/string.h"
#include "he/core/string_fmt.h"

namespace he::schema
{
    #define HE_ID_FMT "{:#018x}"

    CodeGenCppNative::CodeGenCppNative(const CodeGenRequest& request) noexcept
        : m_request(request)
        , m_root(m_request.schemaFile.GetRoot())
    {
        for (const char ch : m_root.GetName())
        {
            if (ch == '.')
                m_namespaceName += "::";
            else
                m_namespaceName += ch;
        }
    }

    bool CodeGenCppNative::Generate()
    {
        m_writer.Reserve(16384); // 16 KB

        GenHeader();
        if (!FlushToFile(".hsc.h"))
            return false;

        m_writer.Clear();

        GenSource();
        if (!FlushToFile(".hsc.cpp"))
            return false;

        m_writer.Clear();

        return true;
    }

    void CodeGenCppNative::GenHeader()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");
        m_writer.WriteLine("#pragma once\n");
        m_writer.WriteLine("#include \"he/core/array.h\"");
        m_writer.WriteLine("#include \"he/core/assert.h\"");
        m_writer.WriteLine("#include \"he/core/string_view.h\"");
        m_writer.WriteLine("#include \"he/core/types.h\"");
        m_writer.WriteLine("#include \"he/core/unique_ptr.h\"");
        m_writer.WriteLine("#include \"he/core/variant.h\"");
        m_writer.WriteLine("#include \"he/core/vector.h\"");
        m_writer.WriteLine("#include \"he/schema/types.h\"\n");

        bool hasUserInclude = false;
        for (const String::Reader importStr : m_root.GetData().GetFile().GetImports())
        {
            if (importStr.IsEmpty())
                continue;

            hasUserInclude = true;
            m_writer.WriteLine("#include \"{}.h\"", importStr.AsView());
        }

        if (hasUserInclude)
            m_writer.Write('\n');

        m_writer.WriteLine("namespace he::schema");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();
        WriteDeclInfo(m_root);
        m_writer.DecreaseIndent();
        m_writer.WriteLine("}\n");

        if (!m_namespaceName.IsEmpty())
        {
            m_writer.WriteLine("namespace {}", m_namespaceName);
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
        }

        for (const Declaration::Reader decl : m_root.GetChildren())
        {
            WriteForwardDecl(decl, m_root);
        }

        m_writer.Write('\n');

        for (const Declaration::Reader decl : m_root.GetChildren())
        {
            WriteDecl(decl, m_root);
        }

        if (!m_namespaceName.IsEmpty())
        {
            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        m_writer.Write('\n');
    }

    void CodeGenCppNative::WriteForwardDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        switch (decl.GetData().GetUnionTag())
        {
            case Declaration::Data::UnionTag::File:
            case Declaration::Data::UnionTag::Attribute:
            case Declaration::Data::UnionTag::Constant:
            case Declaration::Data::UnionTag::Enum:
                break;
            case Declaration::Data::UnionTag::Interface:
            case Declaration::Data::UnionTag::Struct:
                m_writer.WriteLine("struct {};", decl.GetName().AsView());
                break;
        }
    }

    void CodeGenCppNative::WriteDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        switch (decl.GetData().GetUnionTag())
        {
            case Declaration::Data::UnionTag::File:
                break;
            case Declaration::Data::UnionTag::Attribute:
                WriteAttributeDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Constant:
                WriteConstDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Enum:
                WriteEnumDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Interface:
                WriteInterfaceDecl(decl, scope);
                break;
            case Declaration::Data::UnionTag::Struct:
                WriteStructDecl(decl, scope);
                break;
        }
    }

    void CodeGenCppNative::WriteAttributeDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsAttribute());
        m_writer.WriteLine("struct {}", decl.GetName().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("HE_SCHEMA_DECL_ATTRIBUTE(" HE_ID_FMT ", " HE_ID_FMT ");", decl.GetId(), decl.GetParentId());

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCppNative::WriteConstDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_ASSERT(decl.GetData().IsConstant());
        const Declaration::Data::Constant::Reader constDecl = decl.GetData().GetConstant();

        const Type::Reader type = constDecl.GetType();
        const Type::Data::Reader typeData = type.GetData();
        const bool isInline = typeData.IsBool() || typeData.IsEnum() || typeData.IsString() || IsArithmetic(typeData.GetUnionTag());
        const bool isStatic = decl.GetParentId() != m_root.GetId();

        m_writer.WriteIndent();
        if (isInline)
            m_writer.Write("{} constexpr ", isStatic ? "static" : "inline");
        else
            m_writer.Write("{} const ", isStatic ? "static" : "extern");

        if (typeData.IsString())
            m_writer.Write("::he::StringView");
        else
            WriteType(type, scope);

        m_writer.Write(' ');
        m_writer.Write(decl.GetName().AsView());

        if (typeData.IsArray())
            m_writer.Write("[{}]", typeData.GetArray().GetSize());

        if (isInline)
        {
            m_writer.Write(" = ");
            WriteDataValue(type, scope, constDecl.GetValue());
        }

        m_writer.Write(";\n");
    }

    void CodeGenCppNative::WriteEnumDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsEnum());

        m_writer.WriteLine("using {0} = ::he::schema::{0}_{1:016x};", decl.GetName().AsView(), decl.GetId());
    }

    void CodeGenCppNative::WriteInterfaceDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsInterface());
        const Declaration::Data::Interface::Reader interfaceDecl = decl.GetData().GetInterface();

        WriteTemplate(decl);
        m_writer.WriteIndent();
        m_writer.Write("class {}", decl.GetName().AsView());

        const Type::Data::Reader superTypeData = interfaceDecl.GetSuper().GetData();
        const Type::Data::Interface::Reader superInterfaceType = superTypeData.IsInterface() ? superTypeData.GetInterface() : Type::Data::Interface::Reader{};
        const Declaration::Reader superDecl = superInterfaceType.IsValid() ? m_request.GetDecl(superInterfaceType.GetId()) : Declaration::Reader{};

        if (superDecl.IsValid())
        {
            m_writer.Write(" : public ");
            WriteName(superDecl, scope, superInterfaceType.GetBrand());
        }
        m_writer.Write('\n');

        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("HE_SCHEMA_DECL_INTERFACE(" HE_ID_FMT ", " HE_ID_FMT ");\n", decl.GetId(), decl.GetParentId());
        m_writer.WriteLine("virtual ~{}() noexcept {{}}", decl.GetName().AsView());

        if (superDecl.IsValid())
        {
            m_writer.WriteIndent();
            m_writer.Write("using SuperType = ");
            WriteName(superDecl, scope, superInterfaceType.GetBrand());
            m_writer.Write(";\n");
        }
        m_writer.Write('\n');

        for (const Declaration::Reader child : decl.GetChildren())
        {
            m_writer.Write('\n');
            WriteDecl(child, decl);
        }

        for (const Method::Reader method : interfaceDecl.GetMethods())
        {
            const Declaration::Reader params = m_request.GetDecl(method.GetParamStruct());
            const Declaration::Reader result = m_request.GetDecl(method.GetResultStruct());
            m_writer.WriteLine("virtual {} {}({}) = 0;", result.GetName().AsView(), method.GetName().AsView(), params.GetName().AsView());
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCppNative::WriteStructDecl(Declaration::Reader decl, Declaration::Reader scope)
    {
        HE_UNUSED(scope);
        HE_ASSERT(decl.GetData().IsStruct());
        const Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();
        // TODO: Passing allocator into vectors
        WriteTemplate(decl);
        m_writer.WriteLine("struct {}", decl.GetName().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("HE_SCHEMA_DECL_STRUCT(" HE_ID_FMT ", " HE_ID_FMT ", {}, {}, {});",
            decl.GetId(), decl.GetParentId(), structDecl.GetDataFieldCount(), structDecl.GetDataWordSize(), structDecl.GetPointerCount());

        for (const Declaration::Reader child : decl.GetChildren())
        {
            WriteDecl(child, decl);
        }

        m_writer.WriteLine("{}() noexcept;", decl.GetName().AsView());

        if (structDecl.GetIsUnion())
        {
            m_writer.WriteLine("enum class UnionTag : uint16_t");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
            m_writer.WriteLine("_Unset = 0,");

            he::String upperCamelName;
            for (const Field::Reader field : structDecl.GetFields())
            {
                upperCamelName = field.GetName();
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteLine("{} = {},", upperCamelName, field.GetUnionTag());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
            m_writer.WriteLine("UnionTag GetUnionTag() const { return value.IsValid() ? static_cast<UnionTag>(value.Index()) : UnionTag::_Unset; }\n");
            m_writer.WriteLine("void SetUnionTag(UnionTag t);");

            m_writer.WriteIndent();
            m_writer.Write("::he::Variant<");

            const auto fields = structDecl.GetFields();
            for (uint32_t i = 0; i < fields.Size(); ++i)
            {
                if (i > 0)
                    m_writer.Write(", ");

                const Field::Reader field = fields[i];
                switch (field.GetMeta().GetUnionTag())
                {
                    case Field::Meta::UnionTag::Normal:
                    {
                        const Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
                        WriteType(norm.GetType(), decl);
                        break;
                    }
                    case Field::Meta::UnionTag::Group:
                    {
                        const Field::Meta::Group::Reader fieldGroup = field.GetMeta().GetGroup();
                        const Declaration::Reader groupDecl = m_request.GetDecl(fieldGroup.GetTypeId());
                        m_writer.Write(groupDecl.GetName().AsView());
                        break;
                    }
                    case Field::Meta::UnionTag::Union:
                    {
                        const Field::Meta::Union::Reader fieldUnion = field.GetMeta().GetUnion();
                        const Declaration::Reader unionDecl = m_request.GetDecl(fieldUnion.GetTypeId());
                        m_writer.Write(unionDecl.GetName().AsView());
                        break;
                    }
                }
            }
            m_writer.Write("> value;");
        }
        else
        {
            bool needCtor = false;
            for (const Field::Reader field : structDecl.GetFields())
            {
                m_writer.WriteIndent();
                switch (field.GetMeta().GetUnionTag())
                {
                    case Field::Meta::UnionTag::Normal:
                    {
                        const Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
                        const bool hasDefault = norm.HasDefaultValue();
                        const bool isPointer = IsPointer(norm.GetType());

                        needCtor |= hasDefault && isPointer;

                        WriteType(norm.GetType(), decl);
                        m_writer.Write(' ');
                        m_writer.Write(field.GetName().AsView());
                        if (hasDefault && !isPointer)
                        {
                            m_writer.Write("{ ");
                            WriteDataValue(norm.GetType(), decl, norm.GetDefaultValue());
                            m_writer.Write(" }");
                        }
                        break;
                    }
                    case Field::Meta::UnionTag::Group:
                    {
                        const Field::Meta::Group::Reader fieldGroup = field.GetMeta().GetGroup();
                        const Declaration::Reader groupDecl = m_request.GetDecl(fieldGroup.GetTypeId());
                        m_writer.Write(groupDecl.GetName().AsView());
                        m_writer.Write(field.GetName().AsView());
                        break;
                    }
                    case Field::Meta::UnionTag::Union:
                    {
                        const Field::Meta::Union::Reader fieldUnion = field.GetMeta().GetUnion();
                        const Declaration::Reader unionDecl = m_request.GetDecl(fieldUnion.GetTypeId());
                        m_writer.Write(unionDecl.GetName().AsView());
                        m_writer.Write(field.GetName().AsView());
                        break;
                    }
                }
                m_writer.Write(";\n");
            }

            if (needCtor)
            {
                m_writer.WriteLine("{}() noexcept;", decl.GetName().AsView());
            }
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCppNative::WriteDeclInfo(Declaration::Reader decl)
    {
        m_writer.WriteIndent();
        m_writer.Write("HE_SCHEMA_DECL_INFO_FOR_ID(" HE_ID_FMT "); // ", decl.GetId());
        if (decl.GetData().IsFile())
            m_writer.Write("file");
        else
            WriteName(decl, m_root, {});
        m_writer.Write('\n');

        if (decl.GetData().IsEnum())
        {
            const Declaration::Data::Enum::Reader enumDecl = decl.GetData().GetEnum();

            m_writer.WriteLine("enum class {}_{:016x} : uint16_t", decl.GetName().AsView(), decl.GetId());
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            for (const Enumerator::Reader e : enumDecl.GetEnumerators())
            {
                m_writer.WriteLine("{} = {},", e.GetName().AsView(), e.GetOrdinal());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
            m_writer.WriteLine("HE_SCHEMA_DECL_ENUM({}_{:016x}, " HE_ID_FMT ", " HE_ID_FMT ");",
                decl.GetName().AsView(), decl.GetId(), decl.GetId(), decl.GetParentId());
        }

        for (const Declaration::Reader child : decl.GetChildren())
        {
            WriteDeclInfo(child);
        }
    }

    void CodeGenCppNative::GenSource()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");

        StringView baseName = GetPathWithoutExtension(m_request.fileName);
        m_writer.WriteLine("#include \"{}.hsc.h\"\n", baseName);
        m_writer.WriteLine("#include \"he/core/enum_ops.h\"", baseName);
        m_writer.WriteLine("#include \"he/core/types.h\"\n", baseName);

        // Schema data
        m_writer.WriteLine("namespace he::schema");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        WriteRawSchemaData();
        WriteDeclInfoSrc(m_root);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        // Enum strings for the AsString<> template
        m_writer.WriteLine("namespace he");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        WriteEnumStrings(m_root);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        // Generated code definitions
        if (!m_namespaceName.IsEmpty())
        {
            m_writer.WriteLine("namespace {}", m_namespaceName);
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
        }

        for (const Declaration::Reader decl : m_root.GetChildren())
        {
            WriteDeclSrc(decl);
        }

        if (!m_namespaceName.IsEmpty())
        {
            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
    }

    void CodeGenCppNative::WriteDeclSrc(Declaration::Reader decl)
    {
        switch (decl.GetData().GetUnionTag())
        {
            case Declaration::Data::UnionTag::File:
            case Declaration::Data::UnionTag::Attribute:
                break;
            case Declaration::Data::UnionTag::Constant:
                WriteConstDeclSrc(decl);
                break;
            case Declaration::Data::UnionTag::Enum:
            case Declaration::Data::UnionTag::Interface:
                break;
            case Declaration::Data::UnionTag::Struct:
                WriteStructDeclSrc(decl);
                break;
        }
    }

    void CodeGenCppNative::WriteConstDeclSrc(Declaration::Reader decl)
    {
        HE_ASSERT(decl.GetData().IsConstant());
        const Declaration::Data::Constant::Reader constDecl = decl.GetData().GetConstant();

        const Type::Reader type = constDecl.GetType();
        const Type::Data::Reader typeData = type.GetData();
        const bool isInline = typeData.IsBool() || typeData.IsEnum() || typeData.IsString() || IsArithmetic(typeData.GetUnionTag());

        if (isInline)
            return;

        const bool isStatic = decl.GetParentId() != m_root.GetId();

        m_writer.WriteIndent();
        m_writer.Write("const ");
        WriteType(type, m_root);
        m_writer.Write(' ');
        WriteName(decl, m_root, {});

        if (typeData.IsArray())
            m_writer.Write("[{}]", typeData.GetArray().GetSize());

        m_writer.Write("{");
        // TODO: const values
        m_writer.Write("};\n");
    }

    void CodeGenCppNative::WriteStructDeclSrc(Declaration::Reader decl)
    {
        HE_ASSERT(decl.GetData().IsStruct());
        const Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

        bool needCtor = false;
        for (const Field::Reader field : structDecl.GetFields())
        {
            if (field.GetMeta().IsNormal())
            {
                const Field::Meta::Normal::Reader norm = field.GetMeta().GetNormal();
                if (norm.HasDefaultValue() && IsPointer(norm.GetType()))
                {
                    needCtor = true;
                    break;
                }
            }
        }

        if (!needCtor)
            return;

        WriteTemplate(decl);
        m_writer.WriteIndent();
        WriteName(decl, m_root, {});
        // TODO: template brand
        m_writer.Write("::{}() noexcept\n", decl.GetName().AsView());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();
        // TODO: default value initialization
        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCppNative::WriteDeclInfoSrc(Declaration::Reader decl)
    {
        const ptrdiff_t schemaOffset = static_cast<StructReader&>(decl).Data() - m_request.schemaData.Data();

        m_writer.WriteIndent();
        m_writer.Write("// ");
        if (decl.GetData().IsFile())
            m_writer.Write("file");
        else
            WriteName(decl, m_root, {});
        m_writer.Write('\n');

        const bool isStruct = decl.GetData().IsStruct();
        const uint16_t dataFieldCount = isStruct ? decl.GetData().GetStruct().GetDataFieldCount() : 0;
        const uint16_t dataWordSize = isStruct ? decl.GetData().GetStruct().GetDataWordSize() : 0;
        const uint16_t pointerCount = isStruct ? decl.GetData().GetStruct().GetPointerCount() : 0;

        RBTreeSet<TypeId> dependencies;

        // Everything but the file scope should list its parent scope as a dependency.
        if (!decl.GetData().IsFile())
        {
            dependencies.Insert(decl.GetParentId());
        }
        FindAllDependencies(decl, dependencies);

        if (!dependencies.IsEmpty())
        {
            m_writer.WriteLine("static const DeclInfo* Dependencies_{:016x}[] =", decl.GetId());
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
            for (auto&& node : dependencies)
            {
                m_writer.WriteLine("&DeclInfoForId<" HE_ID_FMT ">::Value,", node.value);
            }
            m_writer.DecreaseIndent();
            m_writer.WriteLine("};");
        }

        bool hasFields = false;
        if (isStruct)
        {
            const Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();
            if (structDecl.GetFields().IsEmpty())
            {
                hasFields = true;

                m_writer.WriteLine("static const FieldInfo Fields_{:016x}[] =", decl.GetId());
                m_writer.WriteLine("{");
                m_writer.IncreaseIndent();
                for (const Field::Reader field : structDecl.GetFields())
                {
                    const Word* defaultValuePtrWords = field.Data();
                    const uint64_t offset = defaultValuePtrWords - m_request.schemaData.Data();

                    m_writer.WriteIndent();
                    m_writer.Write("{ offsetof(");
                    WriteName(decl, m_root, {});
                    m_writer.Write(", {}), RawFileSchema_{:016x} + {} }},\n",
                        field.GetName().AsView(), m_root.GetId(), offset);
                }
                m_writer.DecreaseIndent();
                m_writer.WriteLine("};");
            }
        }

        m_writer.WriteLine("const DeclInfo DeclInfoForId<" HE_ID_FMT ">::Value =", decl.GetId());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine(HE_ID_FMT ", " HE_ID_FMT ", DeclKind::{:s}, {}, {}, {}, (RawFileSchema_{:016x} + {}),",
            decl.GetId(), decl.GetParentId(), decl.GetData().GetUnionTag(), dataFieldCount, dataWordSize, pointerCount, m_root.GetId(), schemaOffset);

        if (!dependencies.IsEmpty())
            m_writer.WriteLine("Dependencies_{0:016x}, HE_LENGTH_OF(Dependencies_{0:016x}),", decl.GetId());
        else
            m_writer.WriteLine("nullptr, 0,");

        if (hasFields)
            m_writer.WriteLine("Fields_{0:016x}, HE_LENGTH_OF(Fields_{0:016x}),", decl.GetId());
        else
            m_writer.WriteLine("nullptr, 0,");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteDeclInfoSrc(child);
        }
    }

    void CodeGenCppNative::WriteEnumStrings(Declaration::Reader decl)
    {
        if (decl.GetData().IsEnum())
        {
            const Declaration::Data::Enum::Reader enumDecl = decl.GetData().GetEnum();

            m_writer.WriteLine("template <>");

            m_writer.WriteIndent();
            m_writer.Write("const char* AsString(");
            WriteName(decl, {}, {});
            m_writer.Write(" x)\n");

            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("switch (x)");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            for (const Enumerator::Reader e : enumDecl.GetEnumerators())
            {
                m_writer.WriteIndent();
                m_writer.Write("case ");
                WriteName(decl, {}, {});
                m_writer.Write("::{0}: return \"{0}\";\n", e.GetName().AsView());
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");

            m_writer.WriteLine("return \"<unknown>\";");

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        else if (decl.GetData().IsStruct() && decl.GetData().GetStruct().GetIsUnion())
        {
            Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();

            m_writer.WriteLine("template <>");

            m_writer.WriteIndent();
            m_writer.Write("const char* AsString(");
            WriteName(decl, {}, {});
            m_writer.Write("::UnionTag x)\n");

            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("switch (x)");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            he::String upperCamelName;
            for (const Field::Reader f : structDecl.GetFields())
            {
                upperCamelName = f.GetName();
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteIndent();
                m_writer.Write("case ");
                WriteName(decl, {}, {});
                m_writer.Write("::UnionTag::{0}: return \"{0}\";\n", upperCamelName);
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");

            m_writer.WriteLine("return \"<unknown>\";");

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }

        for (Declaration::Reader child : decl.GetChildren())
        {
            WriteEnumStrings(child);
        }
    }

    void CodeGenCppNative::WriteRawSchemaData()
    {
        m_writer.WriteLine("static const Word RawFileSchema_{:016x}[] =", m_root.GetId());
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();
        m_writer.WriteIndent();
        const uint32_t size = m_request.schemaData.Size();
        for (uint32_t i = 0; i < size; ++i)
        {
            if (i > 0)
            {
                if ((i % 10) == 0)
                {
                    m_writer.Write('\n');
                    m_writer.WriteIndent();
                }
                else
                {
                    m_writer.Write(' ');
                }
            }
            m_writer.Write("{:#018x}ull,", m_request.schemaData[i]);
        }
        m_writer.Write('\n');
        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");
    }

    void CodeGenCppNative::WriteName(Declaration::Reader decl, Declaration::Reader scope, Brand::Reader brand)
    {
        if (!scope.IsValid() || (decl.GetParentId() != scope.GetId() && decl.GetParentId() != scope.GetParentId()))
        {
            const Declaration::Reader parent = m_request.GetDecl(decl.GetParentId());
            if (!parent.GetData().IsFile())
            {
                WriteName(parent, scope, brand);
                m_writer.Write("::");
            }
            else if (!scope.IsValid())
            {
                const StringView nameSpace = parent.GetId() == m_root.GetId() ? m_root.GetName() : parent.GetName();
                m_writer.Write("::");
                WriteWithReplace(nameSpace, '.', "::");
                m_writer.Write("::");
            }
            else if (parent.GetId() != m_root.GetId() && m_root.GetName() != parent.GetName())
            {
                m_writer.Write("::");
                WriteWithReplace(parent.GetName().AsView(), '.', "::");
                m_writer.Write("::");
            }
        }

        m_writer.Write(decl.GetName());

        for (const Brand::Scope::Reader brandScope : brand.GetScopes())
        {
            if (brandScope.GetScopeId() == decl.GetId())
            {
                const List<Type>::Reader params = brandScope.GetParams();

                m_writer.Write("<");
                for (uint32_t i = 0; i < params.Size(); ++i)
                {
                    const Type::Reader t = params[i];
                    WriteType(t, scope);
                    if (i < (params.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(">");
                break;
            }
        }
    }

    void CodeGenCppNative::WriteTemplate(Declaration::Reader decl)
    {
        const List<String>::Reader typeParams = decl.GetTypeParams();

        if (typeParams.IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("template <");
        for (uint32_t i = 0; i < typeParams.Size(); ++i)
        {
            m_writer.Write("typename ");
            m_writer.Write(typeParams[i]);
            if (i < (typeParams.Size() - 1))
                m_writer.Write(", ");
        }
        m_writer.Write(">\n");
    }

    void CodeGenCppNative::WriteType(Type::Reader type, Declaration::Reader scope, bool isStorage)
    {
        const bool isArray = type.GetData().IsArray();
        const bool isPointer = IsPointer(type);

        if (isPointer && !isArray && isStorage)
        {
            m_writer.Write("::he::UniquePtr<");
        }

        switch (type.GetData().GetUnionTag())
        {
            case Type::Data::UnionTag::Void: m_writer.Write("::he::schema::Void"); break;
            case Type::Data::UnionTag::Bool: m_writer.Write("bool"); break;
            case Type::Data::UnionTag::Int8: m_writer.Write("int8_t"); break;
            case Type::Data::UnionTag::Int16: m_writer.Write("int16_t"); break;
            case Type::Data::UnionTag::Int32: m_writer.Write("int32_t"); break;
            case Type::Data::UnionTag::Int64: m_writer.Write("int64_t"); break;
            case Type::Data::UnionTag::Uint8: m_writer.Write("uint8_t"); break;
            case Type::Data::UnionTag::Uint16: m_writer.Write("uint16_t"); break;
            case Type::Data::UnionTag::Uint32: m_writer.Write("uint32_t"); break;
            case Type::Data::UnionTag::Uint64: m_writer.Write("uint64_t"); break;
            case Type::Data::UnionTag::Float32: m_writer.Write("float"); break;
            case Type::Data::UnionTag::Float64: m_writer.Write("double"); break;
            case Type::Data::UnionTag::Blob: m_writer.Write("::he::Vector<uint8_t>"); break;
            case Type::Data::UnionTag::String: m_writer.Write("::he::String"); break;
            case Type::Data::UnionTag::Array:
            {
                const Type::Data::Array::Reader arrayType = type.GetData().GetArray();
                m_writer.Write("::he::Array<");
                WriteType(arrayType.GetElementType(), scope, true);
                m_writer.Write(", {}>{}", arrayType.GetSize(), isStorage ? "" : "&");
                break;
            }
            case Type::Data::UnionTag::List:
            {
                const Type::Data::List::Reader listType = type.GetData().GetList();
                m_writer.Write("::he::Vector<");
                WriteType(listType.GetElementType(), scope, true);
                m_writer.Write(">");
                break;
            }
            case Type::Data::UnionTag::Enum:
            {
                const Type::Data::Enum::Reader enumType = type.GetData().GetEnum();
                const Declaration::Reader decl = m_request.GetDecl(enumType.GetId());
                HE_ASSERT(decl.GetData().IsEnum());
                WriteName(decl, scope, enumType.GetBrand());
                break;
            }
            case Type::Data::UnionTag::Struct:
            {
                const Type::Data::Struct::Reader structType = type.GetData().GetStruct();
                const Declaration::Reader decl = m_request.GetDecl(structType.GetId());
                HE_ASSERT(decl.GetData().IsStruct());
                WriteName(decl, scope, structType.GetBrand());
                break;
            }
            case Type::Data::UnionTag::Interface:
            {
                const Type::Data::Interface::Reader interfaceType = type.GetData().GetInterface();
                const Declaration::Reader decl = m_request.GetDecl(interfaceType.GetId());
                HE_ASSERT(decl.GetData().IsInterface());
                WriteName(decl, scope, interfaceType.GetBrand());
                break;
            }
            case Type::Data::UnionTag::Parameter:
            {
                const Type::Data::Parameter::Reader param = type.GetData().GetParameter();
                const Declaration::Reader decl = m_request.GetDecl(param.GetScopeId());
                const String::Reader name = decl.GetTypeParams()[param.GetIndex()];
                m_writer.Write(name);
                break;
            }
            case Type::Data::UnionTag::AnyPointer:
            {
                // TODO
                m_writer.Write("void");
                break;
            }
            case Type::Data::UnionTag::AnyStruct:
            {
                // TODO
                m_writer.Write("void");
                break;
            }
            case Type::Data::UnionTag::AnyList:
            {
                // TODO
                m_writer.Write("void");
                break;
            }
        }

        if (isPointer && !isArray)
        {
            if (isStorage)
                m_writer.Write('>');
            else
                m_writer.Write('*');
        }
    }

    void CodeGenCppNative::WriteDataValue(Type::Reader type, Declaration::Reader scope, Value::Reader value)
    {
        switch (value.GetData().GetUnionTag())
        {
            case Value::Data::UnionTag::Void: m_writer.Write("{}"); break;
            case Value::Data::UnionTag::Bool: m_writer.Write("{}", value.GetData().GetBool()); break;
            case Value::Data::UnionTag::Int8: m_writer.Write("{}", value.GetData().GetInt8()); break;
            case Value::Data::UnionTag::Int16: m_writer.Write("{}", value.GetData().GetInt16()); break;
            case Value::Data::UnionTag::Int32: m_writer.Write("{}", value.GetData().GetInt32()); break;
            case Value::Data::UnionTag::Int64: m_writer.Write("{}", value.GetData().GetInt64()); break;
            case Value::Data::UnionTag::Uint8: m_writer.Write("{}", value.GetData().GetUint8()); break;
            case Value::Data::UnionTag::Uint16: m_writer.Write("{}", value.GetData().GetUint16()); break;
            case Value::Data::UnionTag::Uint32: m_writer.Write("{}", value.GetData().GetUint32()); break;
            case Value::Data::UnionTag::Uint64: m_writer.Write("{}", value.GetData().GetUint64()); break;
            case Value::Data::UnionTag::Float32: m_writer.Write("{}", value.GetData().GetFloat32()); break;
            case Value::Data::UnionTag::Float64: m_writer.Write("{}", value.GetData().GetFloat64()); break;
            case Value::Data::UnionTag::String:
            {
                // Technically a pointer value, but sometimes we use it like a data value (like for constants).
                HE_ASSERT(type.GetData().IsString());

                const String::Reader str = value.GetData().GetString();
                m_writer.Write('"');
                for (char ch : str)
                {
                    switch (ch)
                    {
                        case '\'': m_writer.Write("\\\'"); break;
                        case '\"': m_writer.Write("\\\""); break;
                        case '\?': m_writer.Write("\\?"); break;
                        case '\\': m_writer.Write("\\\\"); break;
                        case '\a': m_writer.Write("\\a"); break;
                        case '\b': m_writer.Write("\\b"); break;
                        case '\f': m_writer.Write("\\f"); break;
                        case '\n': m_writer.Write("\\n"); break;
                        case '\r': m_writer.Write("\\r"); break;
                        case '\t': m_writer.Write("\\t"); break;
                        case '\v': m_writer.Write("\\v"); break;
                        default:
                            if (IsPrint(ch))
                                m_writer.Write(ch);
                            else
                                m_writer.Write("\\x{:02x}", static_cast<uint8_t>(ch));
                    }
                }
                m_writer.Write('"');
                break;
            }
            case Value::Data::UnionTag::Enum:
            {
                HE_ASSERT(type.GetData().IsEnum());
                const Type::Data::Enum::Reader enumType = type.GetData().GetEnum();
                const Declaration::Reader decl = m_request.GetDecl(enumType.GetId());

                HE_ASSERT(decl.GetData().IsEnum());
                const Declaration::Data::Enum::Reader enumDecl = decl.GetData().GetEnum();

                WriteName(decl, scope, enumType.GetBrand());
                m_writer.Write("::");
                for (Enumerator::Reader e : enumDecl.GetEnumerators())
                {
                    if (e.GetOrdinal() == value.GetData().GetEnum())
                    {
                        m_writer.Write(e.GetName());
                        break;
                    }
                }
                break;
            }
            case Value::Data::UnionTag::Blob:
            case Value::Data::UnionTag::List:
            case Value::Data::UnionTag::Struct:
                HE_ASSERT(false, HE_MSG("Invalid value kind. Expected a non-pointer value."));
                break;
        }
    }

    void CodeGenCppNative::WriteWithReplace(StringView input, char what, StringView with)
    {
        for (char ch : input)
        {
            if (ch == what)
            {
                m_writer.Write(with);
            }
            else
            {
                m_writer.Write(ch);
            }
        }
    }

    bool CodeGenCppNative::FlushToFile(const char* suffix)
    {
        he::String filePath(m_request.outDir);
        ConcatPath(filePath, m_request.fileName);
        RemoveExtension(filePath);
        filePath += suffix;

        const he::String& code = m_writer.Str();

        File f;
        if (!f.Open(filePath.Data(), FileOpenMode::WriteTruncate))
            return false;

        if (!f.Write(code.Data(), code.Size()))
            return false;

        return true;
    }

    void CodeGenCppNative::FindAllDependencies(Type::Reader type, RBTreeSet<TypeId>& out)
    {
        switch (type.GetData().GetUnionTag())
        {
            case Type::Data::UnionTag::Struct:
                out.Insert(type.GetData().GetStruct().GetId());
                break;
            case Type::Data::UnionTag::Enum:
                out.Insert(type.GetData().GetEnum().GetId());
                break;
            case Type::Data::UnionTag::Interface:
                out.Insert(type.GetData().GetInterface().GetId());
                break;
            case Type::Data::UnionTag::List:
                FindAllDependencies(type.GetData().GetList().GetElementType(), out);
                break;
            case Type::Data::UnionTag::Array:
                FindAllDependencies(type.GetData().GetArray().GetElementType(), out);
                break;
            default:
                break;
        }
    }

    void CodeGenCppNative::FindAllDependencies(Declaration::Reader decl, RBTreeSet<TypeId>& out)
    {
        switch (decl.GetData().GetUnionTag())
        {
            case Declaration::Data::UnionTag::Struct:
            {
                Declaration::Data::Struct::Reader structDecl = decl.GetData().GetStruct();
                for (Field::Reader field : structDecl.GetFields())
                {
                    switch (field.GetMeta().GetUnionTag())
                    {
                        case Field::Meta::UnionTag::Normal:
                            FindAllDependencies(field.GetMeta().GetNormal().GetType(), out);
                            break;
                        case Field::Meta::UnionTag::Group:
                            out.Insert(field.GetMeta().GetGroup().GetTypeId());
                            break;
                        case Field::Meta::UnionTag::Union:
                            out.Insert(field.GetMeta().GetUnion().GetTypeId());
                            break;
                    }
                }
                break;
            }
            case Declaration::Data::UnionTag::Interface:
            {
                Declaration::Data::Interface::Reader interfaceDecl = decl.GetData().GetInterface();

                Type::Data::Reader superTypeData = interfaceDecl.GetSuper().GetData();
                Type::Data::Interface::Reader superInterface = superTypeData.IsInterface() ? superTypeData.GetInterface() : Type::Data::Interface::Reader{};

                if (superInterface.IsValid())
                {
                    out.Insert(superInterface.GetId());
                }

                for (Method::Reader method : interfaceDecl.GetMethods())
                {
                    out.Insert(method.GetParamStruct());
                    out.Insert(method.GetResultStruct());
                }
                break;
            }
            default:
                break;
        }
    }

    bool GenerateCppNative(const CodeGenRequest& request)
    {
        CodeGenCppNative generator(request);
        if (!generator.Generate())
            return false;

        return true;
    }
}
