# Copyright Chad Engler

id = "llvm.libcxx"
name = "C++ Standard Library"
description = "An implementation of the C++ standard library, targeting C++11 and above."
version = "17.0.6"
authors = []
license = "Apache-2.0 WITH LLVM-exception"
homepage = "https://github.com/llvm/llvm-project"

[install]
    base_path = "libcxx-17.0.6.src.tar/libcxx-17.0.6.src"
    archive = "https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/libcxx-17.0.6.src.tar.xz"
