# Copyright Chad Engler

id = "fmtlib.fmt"
name = "{fmt}"
description = "An open-source formatting library providing a fast and safe alternative to C stdio and C++ iostreams."
version = "8.0.1"
author = "Victor Zverovich"
license = "MIT"
homepage = "https://fmt.dev/"

[install]
    github = "fmtlib/fmt#8.0.1"

[[modules]]
    name = "fmt"
    type = "static"
    group = "engine/contrib"
    files = [
        "include/fmt/core.h",
        "include/fmt/compile.h",
        "include/fmt/format.h",
        "include/fmt/xchar.h",
        "src/format.cc",
    ]
    # There are a number of warnings emitted from fmt headers, so treat them as external
    public_externalincludedirs = ["include"]
