# Copyright Chad Engler

id = "gohugoio.hugo"
name = "Hugo"
description = "A Fast and Flexible Static Site Generator."
version = "0.104.2"
authors = ["Bjørn Erik Pedersen <bjorn.erik.pedersen@gmail.com>", "Steve Francia <steve.francia@gmail.com>"]
license = "Apache-2.0"
homepage = "https://gohugo.io/"

[install]
    index_archive_by_host = true

    [install.archive]
        linux = "https://github.com/gohugoio/hugo/releases/download/v0.104.2/hugo_extended_0.104.2_linux-amd64.tar.gz"
        windows = "https://github.com/gohugoio/hugo/releases/download/v0.104.2/hugo_extended_0.104.2_windows-amd64.zip"
