# Copyright Chad Engler

id = "microsoft.typescript"
name = "TypeScript"
description = "TypeScript is a superset of JavaScript that compiles to clean JavaScript output."
version = "5.3.3"
authors = ["Microsoft"]
license = "Apache-2.0"
homepage = "https://github.com/microsoft/TypeScript"

[install]
    nuget = "Microsoft.TypeScript.MSBuild#5.3.3"
