# Copyright Chad Engler

id = "nodejs.nodejs"
name = "Node.js"
description = "Node.js® is an open-source, cross-platform JavaScript runtime environment."
version = "20.11.0"
authors = ["OpenJS Foundation"]
license = ""
homepage = "https://nodejs.org/"

[install]
    base_path = "node-v20.11.0-win-x64"
    index_archive_by_host = true

    [install.archive]
        linux = "https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.xz"
        windows = "https://nodejs.org/dist/v20.11.0/node-v20.11.0-win-x64.zip"
