// Generated by the Harvest Schema compiler

#pragma once

#include "he/core/types.h"
#include "he/core/enum_ops.h"
#include "he/core/string.h"
#include "he/core/unique_ptr.h"
#include "he/core/vector.h"
#include "he/schema/buffer.h"
#include "he/schema/reflection.h"

namespace he::schema
{
    extern const uint8_t Schema_Reflection[25606];

    static constexpr uint16_t InvalidSchemaIndex = 65535;
    enum class BaseType : uint8_t
    {
        Unknown = 0,
        Bool = 1,
        Int8 = 2,
        Int16 = 3,
        Int32 = 4,
        Int64 = 5,
        Uint8 = 6,
        Uint16 = 7,
        Uint32 = 8,
        Uint64 = 9,
        Float32 = 10,
        Float64 = 11,
        Array = 12,
        List = 13,
        Map = 14,
        Pointer = 15,
        Set = 16,
        String = 17,
        Vector = 18,
        Alias = 19,
        Enum = 20,
        Interface = 21,
        Struct = 22,
        Union = 23,

        _Count,
    };

    enum class AttributeTarget : uint32_t
    {
        Alias = 0x00000001,
        Const = 0x00000002,
        Enum = 0x00000004,
        EnumValue = 0x00000008,
        Field = 0x00000010,
        File = 0x00000020,
        Interface = 0x00000040,
        Method = 0x00000080,
        Parameter = 0x00000100,
        Struct = 0x00000200,
        Union = 0x00000400,

        None = 0,
        All = 0xffffffff,
    };
    HE_ENUM_FLAGS(AttributeTarget);

    struct BasicValue
    {
        static constexpr uint32_t TypeId = 0x2ae55fb0;

        static constexpr uint32_t TagId_b = 0xe70c2de5;
        static constexpr uint32_t TagId_i8 = 0x9338fbb4;
        static constexpr uint32_t TagId_i16 = 0x56a2c0db;
        static constexpr uint32_t TagId_i32 = 0xcaa7f4a5;
        static constexpr uint32_t TagId_i64 = 0xc69b2266;
        static constexpr uint32_t TagId_u8 = 0x0b42b2f8;
        static constexpr uint32_t TagId_u16 = 0x79ee1b1f;
        static constexpr uint32_t TagId_u32 = 0x05f374b1;
        static constexpr uint32_t TagId_u64 = 0x79fae712;
        static constexpr uint32_t TagId_f32 = 0x84375ec4;
        static constexpr uint32_t TagId_f64 = 0x00435aeb;

        static constexpr uint32_t FieldId_tag = 0x95f72993;
        static constexpr uint32_t FieldId_value = 0x425ed3ca;

        static constexpr uint32_t FieldCount = 2;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::UnionReader
        {
        public:
            using he::schema::UnionReader::GetTagId;
            using he::schema::UnionReader::IsUnset;

            const auto* B() const { return GetTagId() == TagId_b ? Get<bool>() : nullptr; }
            const auto* I8() const { return GetTagId() == TagId_i8 ? Get<int8_t>() : nullptr; }
            const auto* I16() const { return GetTagId() == TagId_i16 ? Get<int16_t>() : nullptr; }
            const auto* I32() const { return GetTagId() == TagId_i32 ? Get<int32_t>() : nullptr; }
            const auto* I64() const { return GetTagId() == TagId_i64 ? Get<int64_t>() : nullptr; }
            const auto* U8() const { return GetTagId() == TagId_u8 ? Get<uint8_t>() : nullptr; }
            const auto* U16() const { return GetTagId() == TagId_u16 ? Get<uint16_t>() : nullptr; }
            const auto* U32() const { return GetTagId() == TagId_u32 ? Get<uint32_t>() : nullptr; }
            const auto* U64() const { return GetTagId() == TagId_u64 ? Get<uint64_t>() : nullptr; }
            const auto* F32() const { return GetTagId() == TagId_f32 ? Get<float>() : nullptr; }
            const auto* F64() const { return GetTagId() == TagId_f64 ? Get<double>() : nullptr; }
        };

        uint32_t tag;
        union
        {
            bool b;
            int8_t i8;
            int16_t i16;
            int32_t i32;
            int64_t i64;
            uint8_t u8;
            uint16_t u16;
            uint32_t u32;
            uint64_t u64;
            float f32;
            double f64;
        } value;
    };

    struct ObjectDef
    {
        static constexpr uint32_t TypeId = 0x7111ebff;

        static constexpr uint32_t FieldId_type = 0x5127f14d;
        static constexpr uint32_t FieldId_index = 0x090aa9ab;

        static constexpr uint32_t FieldCount = 2;

        static const he::schema::FieldInfo Fields[FieldCount];

        enum class Type : uint8_t
        {
            Alias = 0,
            Attribute = 1,
            Const = 2,
            Enum = 3,
            Interface = 4,
            Struct = 5,
            Union = 6,

            _Count,
        };


        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Type() const { return GetFieldPointer<ObjectDef::Type>(FieldId_type); }
            const auto* Index() const { return GetFieldPointer<uint32_t>(FieldId_index); }
        };

        ObjectDef::Type type{};
        uint32_t index{};
    };

    struct Value
    {
        static constexpr uint32_t TypeId = 0x632bcaa0;

        static constexpr uint32_t FieldId_basic = 0x0535023d;
        static constexpr uint32_t FieldId_str = 0xc24bd190;

        static constexpr uint32_t FieldCount = 2;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Basic() const { return GetFieldPointer<BasicValue::BufferReader>(FieldId_basic); }
            const auto* Str() const { return GetFieldPointer<he::schema::StringReader>(FieldId_str); }
        };

        BasicValue basic{};
        he::String str{};
    };

    struct Attribute
    {
        static constexpr uint32_t TypeId = 0xc2545749;

        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_parameters = 0x48a52ed9;

        static constexpr uint32_t FieldCount = 2;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Parameters() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Value::BufferReader>>>(FieldId_parameters); }
        };

        he::String name{};
        he::Vector<Value> parameters{};
    };

    struct Type
    {
        static constexpr uint32_t TypeId = 0x367ddc5b;

        static constexpr uint32_t FieldId_base = 0x3ddc94d8;
        static constexpr uint32_t FieldId_fixedSize = 0x0ae776c8;
        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_element = 0x4f4d3bf7;
        static constexpr uint32_t FieldId_key = 0x6815c86c;
        static constexpr uint32_t FieldId_typeParams = 0xd708606b;

        static constexpr uint32_t FieldCount = 6;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Base() const { return GetFieldPointer<BaseType>(FieldId_base); }
            const auto* FixedSize() const { return GetFieldPointer<uint16_t>(FieldId_fixedSize); }
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Element() const { return GetFieldPointer<Type::BufferReader>(FieldId_element); }
            const auto* Key() const { return GetFieldPointer<Type::BufferReader>(FieldId_key); }
            const auto* TypeParams() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Type::BufferReader>>>(FieldId_typeParams); }
        };

        BaseType base{};
        uint16_t fixedSize{};
        he::String name{};
        he::UniquePtr<Type> element{};
        he::UniquePtr<Type> key{};
        he::Vector<Type> typeParams{};
    };

    struct AttributeDef
    {
        static constexpr uint32_t TypeId = 0x1e471090;

        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_type = 0x5127f14d;
        static constexpr uint32_t FieldId_targets = 0x88f674e1;

        static constexpr uint32_t FieldCount = 3;

        static const he::schema::FieldInfo Fields[FieldCount];

        static constexpr ObjectDef::Type ObjectType = ObjectDef::Type::Attribute;

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Type() const { return GetFieldPointer<Type::BufferReader>(FieldId_type); }
            const auto* Targets() const { return GetFieldPointer<AttributeTarget>(FieldId_targets); }
        };

        he::String name{};
        Type type{};
        AttributeTarget targets{};
    };

    struct FieldDef
    {
        static constexpr uint32_t TypeId = 0x67705ab4;

        static constexpr uint32_t FieldId_id = 0x37386ae0;
        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_type = 0x5127f14d;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_defaultValue = 0xd81264bf;

        static constexpr uint32_t FieldCount = 5;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Id() const { return GetFieldPointer<uint32_t>(FieldId_id); }
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Type() const { return GetFieldPointer<Type::BufferReader>(FieldId_type); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* DefaultValue() const { return GetFieldPointer<Value::BufferReader>(FieldId_defaultValue); }
        };

        uint32_t id{};
        he::String name{};
        Type type{};
        he::Vector<Attribute> attributes{};
        Value defaultValue{};
    };

    struct EnumValueDef
    {
        static constexpr uint32_t TypeId = 0xb2eb7712;

        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_value = 0x425ed3ca;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;

        static constexpr uint32_t FieldCount = 3;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Value() const { return GetFieldPointer<Value::BufferReader>(FieldId_value); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
        };

        he::String name{};
        Value value{};
        he::Vector<Attribute> attributes{};
    };

    struct EnumDef
    {
        static constexpr uint32_t TypeId = 0x9bcae111;

        static constexpr uint32_t FieldId_base = 0x3ddc94d8;
        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_values = 0x34474c3b;

        static constexpr uint32_t FieldCount = 4;

        static const he::schema::FieldInfo Fields[FieldCount];

        static constexpr ObjectDef::Type ObjectType = ObjectDef::Type::Enum;

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Base() const { return GetFieldPointer<BaseType>(FieldId_base); }
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* Values() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<EnumValueDef::BufferReader>>>(FieldId_values); }
        };

        BaseType base{};
        he::String name{};
        he::Vector<Attribute> attributes{};
        he::Vector<EnumValueDef> values{};
    };

    struct AliasDef
    {
        static constexpr uint32_t TypeId = 0x23548974;

        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_type = 0x5127f14d;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_typeParams = 0xd708606b;

        static constexpr uint32_t FieldCount = 4;

        static const he::schema::FieldInfo Fields[FieldCount];

        static constexpr ObjectDef::Type ObjectType = ObjectDef::Type::Alias;

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Type() const { return GetFieldPointer<Type::BufferReader>(FieldId_type); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* TypeParams() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<he::schema::StringReader>>>(FieldId_typeParams); }
        };

        he::String name{};
        Type type{};
        he::Vector<Attribute> attributes{};
        he::Vector<he::String> typeParams{};
    };

    struct ConstDef
    {
        static constexpr uint32_t TypeId = 0x56433fc5;

        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_type = 0x5127f14d;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_value = 0x425ed3ca;

        static constexpr uint32_t FieldCount = 4;

        static const he::schema::FieldInfo Fields[FieldCount];

        static constexpr ObjectDef::Type ObjectType = ObjectDef::Type::Const;

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Type() const { return GetFieldPointer<Type::BufferReader>(FieldId_type); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* Value() const { return GetFieldPointer<Value::BufferReader>(FieldId_value); }
        };

        he::String name{};
        Type type{};
        he::Vector<Attribute> attributes{};
        Value value{};
    };

    struct UnionDef
    {
        static constexpr uint32_t TypeId = 0x98dafb99;

        static constexpr uint32_t FieldId_id = 0x37386ae0;
        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_fields = 0x0640657c;

        static constexpr uint32_t FieldCount = 4;

        static const he::schema::FieldInfo Fields[FieldCount];

        static constexpr ObjectDef::Type ObjectType = ObjectDef::Type::Union;

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Id() const { return GetFieldPointer<uint32_t>(FieldId_id); }
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* Fields() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<FieldDef::BufferReader>>>(FieldId_fields); }
        };

        uint32_t id{};
        he::String name{};
        he::Vector<Attribute> attributes{};
        he::Vector<FieldDef> fields{};
    };

    struct StructDef
    {
        static constexpr uint32_t TypeId = 0x7feda781;

        static constexpr uint32_t FieldId_id = 0x37386ae0;
        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_extends = 0x9d85d64e;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_fields = 0x0640657c;
        static constexpr uint32_t FieldId_typeParams = 0xd708606b;
        static constexpr uint32_t FieldId_objects = 0xa8c6206b;
        static constexpr uint32_t FieldId_aliases = 0x2bc0e91f;
        static constexpr uint32_t FieldId_consts = 0xb6a709e5;
        static constexpr uint32_t FieldId_enums = 0x3119c509;
        static constexpr uint32_t FieldId_structs = 0x5b919ca9;
        static constexpr uint32_t FieldId_unions = 0xa6cbb685;

        static constexpr uint32_t FieldCount = 12;

        static const he::schema::FieldInfo Fields[FieldCount];

        static constexpr ObjectDef::Type ObjectType = ObjectDef::Type::Struct;

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Id() const { return GetFieldPointer<uint32_t>(FieldId_id); }
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Extends() const { return GetFieldPointer<Type::BufferReader>(FieldId_extends); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* Fields() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<FieldDef::BufferReader>>>(FieldId_fields); }
            const auto* TypeParams() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<he::schema::StringReader>>>(FieldId_typeParams); }
            const auto* Objects() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<ObjectDef::BufferReader>>>(FieldId_objects); }
            const auto* Aliases() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<AliasDef::BufferReader>>>(FieldId_aliases); }
            const auto* Consts() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<ConstDef::BufferReader>>>(FieldId_consts); }
            const auto* Enums() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<EnumDef::BufferReader>>>(FieldId_enums); }
            const auto* Structs() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<StructDef::BufferReader>>>(FieldId_structs); }
            const auto* Unions() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<UnionDef::BufferReader>>>(FieldId_unions); }
        };

        uint32_t id{};
        he::String name{};
        Type extends{};
        he::Vector<Attribute> attributes{};
        he::Vector<FieldDef> fields{};
        he::Vector<he::String> typeParams{};
        he::Vector<ObjectDef> objects{};
        he::Vector<AliasDef> aliases{};
        he::Vector<ConstDef> consts{};
        he::Vector<EnumDef> enums{};
        he::Vector<StructDef> structs{};
        he::Vector<UnionDef> unions{};
    };

    struct MethodParamDef
    {
        static constexpr uint32_t TypeId = 0x0ca615f2;

        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_type = 0x5127f14d;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;

        static constexpr uint32_t FieldCount = 3;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Type() const { return GetFieldPointer<Type::BufferReader>(FieldId_type); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
        };

        he::String name{};
        Type type{};
        he::Vector<Attribute> attributes{};
    };

    struct MethodDef
    {
        static constexpr uint32_t TypeId = 0x794e95b9;

        static constexpr uint32_t FieldId_id = 0x37386ae0;
        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_parameters = 0x48a52ed9;
        static constexpr uint32_t FieldId_returnType = 0xca1f7ce7;

        static constexpr uint32_t FieldCount = 5;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Id() const { return GetFieldPointer<uint32_t>(FieldId_id); }
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* Parameters() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<MethodParamDef::BufferReader>>>(FieldId_parameters); }
            const auto* ReturnType() const { return GetFieldPointer<Type::BufferReader>(FieldId_returnType); }
        };

        uint32_t id{};
        he::String name{};
        he::Vector<Attribute> attributes{};
        he::Vector<MethodParamDef> parameters{};
        Type returnType{};
    };

    struct InterfaceDef
    {
        static constexpr uint32_t TypeId = 0x1e49b999;

        static constexpr uint32_t FieldId_id = 0x37386ae0;
        static constexpr uint32_t FieldId_name = 0x8d39bde6;
        static constexpr uint32_t FieldId_implements = 0x9d0f221f;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_methods = 0xe2243e79;
        static constexpr uint32_t FieldId_typeParams = 0xd708606b;
        static constexpr uint32_t FieldId_objects = 0xa8c6206b;
        static constexpr uint32_t FieldId_aliases = 0x2bc0e91f;
        static constexpr uint32_t FieldId_consts = 0xb6a709e5;
        static constexpr uint32_t FieldId_enums = 0x3119c509;
        static constexpr uint32_t FieldId_structs = 0x5b919ca9;
        static constexpr uint32_t FieldId_unions = 0xa6cbb685;

        static constexpr uint32_t FieldCount = 12;

        static const he::schema::FieldInfo Fields[FieldCount];

        static constexpr ObjectDef::Type ObjectType = ObjectDef::Type::Interface;

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* Id() const { return GetFieldPointer<uint32_t>(FieldId_id); }
            const auto* Name() const { return GetFieldPointer<he::schema::StringReader>(FieldId_name); }
            const auto* Implements() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Type::BufferReader>>>(FieldId_implements); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<Attribute::BufferReader>>>(FieldId_attributes); }
            const auto* Methods() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<MethodDef::BufferReader>>>(FieldId_methods); }
            const auto* TypeParams() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<he::schema::StringReader>>>(FieldId_typeParams); }
            const auto* Objects() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<ObjectDef::BufferReader>>>(FieldId_objects); }
            const auto* Aliases() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<AliasDef::BufferReader>>>(FieldId_aliases); }
            const auto* Consts() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<ConstDef::BufferReader>>>(FieldId_consts); }
            const auto* Enums() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<EnumDef::BufferReader>>>(FieldId_enums); }
            const auto* Structs() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<StructDef::BufferReader>>>(FieldId_structs); }
            const auto* Unions() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<UnionDef::BufferReader>>>(FieldId_unions); }
        };

        uint32_t id{};
        he::String name{};
        he::Vector<Type> implements{};
        he::Vector<Attribute> attributes{};
        he::Vector<MethodDef> methods{};
        he::Vector<he::String> typeParams{};
        he::Vector<ObjectDef> objects{};
        he::Vector<AliasDef> aliases{};
        he::Vector<ConstDef> consts{};
        he::Vector<EnumDef> enums{};
        he::Vector<StructDef> structs{};
        he::Vector<UnionDef> unions{};
    };

    struct SchemaDef
    {
        static constexpr uint32_t TypeId = 0xbb6c2f4b;

        static constexpr uint32_t FieldId_namespaceId = 0x0515477d;
        static constexpr uint32_t FieldId_namespaceName = 0xe4a53003;
        static constexpr uint32_t FieldId_imports = 0xad01b6e5;
        static constexpr uint32_t FieldId_objects = 0xa8c6206b;
        static constexpr uint32_t FieldId_aliases = 0x2bc0e91f;
        static constexpr uint32_t FieldId_attributes = 0xe1ffdb94;
        static constexpr uint32_t FieldId_consts = 0xb6a709e5;
        static constexpr uint32_t FieldId_enums = 0x3119c509;
        static constexpr uint32_t FieldId_interfaces = 0x7fddec79;
        static constexpr uint32_t FieldId_structs = 0x5b919ca9;
        static constexpr uint32_t FieldId_unions = 0xa6cbb685;
        static constexpr uint32_t FieldId_usedTypesMask = 0xe477d60d;

        static constexpr uint32_t FieldCount = 12;

        static const he::schema::FieldInfo Fields[FieldCount];

        class BufferReader : private he::schema::StructureReader
        {
        public:
            const auto* NamespaceId() const { return GetFieldPointer<uint32_t>(FieldId_namespaceId); }
            const auto* NamespaceName() const { return GetFieldPointer<he::schema::StringReader>(FieldId_namespaceName); }
            const auto* Imports() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<he::schema::StringReader>>>(FieldId_imports); }
            const auto* Objects() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<ObjectDef::BufferReader>>>(FieldId_objects); }
            const auto* Aliases() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<AliasDef::BufferReader>>>(FieldId_aliases); }
            const auto* Attributes() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<AttributeDef::BufferReader>>>(FieldId_attributes); }
            const auto* Consts() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<ConstDef::BufferReader>>>(FieldId_consts); }
            const auto* Enums() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<EnumDef::BufferReader>>>(FieldId_enums); }
            const auto* Interfaces() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<InterfaceDef::BufferReader>>>(FieldId_interfaces); }
            const auto* Structs() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<StructDef::BufferReader>>>(FieldId_structs); }
            const auto* Unions() const { return GetFieldPointer<he::schema::VectorReader<he::schema::RelPointer<UnionDef::BufferReader>>>(FieldId_unions); }
            const auto* UsedTypesMask() const { return GetFieldPointer<uint64_t>(FieldId_usedTypesMask); }
        };

        uint32_t namespaceId{};
        he::String namespaceName{};
        he::Vector<he::String> imports{};
        he::Vector<ObjectDef> objects{};
        he::Vector<AliasDef> aliases{};
        he::Vector<AttributeDef> attributes{};
        he::Vector<ConstDef> consts{};
        he::Vector<EnumDef> enums{};
        he::Vector<InterfaceDef> interfaces{};
        he::Vector<StructDef> structs{};
        he::Vector<UnionDef> unions{};
        uint64_t usedTypesMask{};
    };

}

