# Copyright Chad Engler

id = "DirectStorage"
name = "DirectStorage"
description = "DirectStorage for Windows."
version = "1.2.1"
authors = ["Microsoft"]
license = "SEE LICENSE IN LICENSE.txt"
homepage = "https://www.nuget.org/packages/Microsoft.Direct3D.DirectStorage"

[install]
    nuget = "Microsoft.Direct3D.DirectStorage#1.2.1"
    valid_targets = ["windows"]

[[modules]]
    name = "DirectStorage"
    type = "shared"
    group = "engine/contrib"
    public_includedirs = ["native/include"]

    [[modules.variants]]
        conditions = ["system:windows", "architecture:x86_64"]
        public_dependson = [
            "file:native/lib/x64/dstorage.lib"
        ]
        copy_files = [
            "native/bin/x64/dstorage.dll",
            "native/bin/x64/dstoragecore.dll",
        ]

    [[modules.variants]]
        conditions = ["system:windows", "architecture:ARM64"]
        public_dependson = [
            "file:native/lib/ARM64/dstorage.lib"
        ]
        copy_files = [
            "native/bin/ARM64/dstorage.dll",
            "native/bin/ARM64/dstoragecore.dll",
        ]
