// Copyright Chad Engler

#include "codegen_cpp.h"

#include "he/core/file.h"
#include "he/core/path.h"
#include "he/core/enum_fmt.h"
#include "he/core/span_fmt.h"
#include "he/core/string.h"
#include "he/core/string_fmt.h"
#include "he/core/string_view.h"
#include "he/core/string_view_fmt.h"

namespace he::schema
{
    #define HE_ID_FMT "{:#16x}"

    constexpr const char ReaderSuffix[] = "::Reader";
    constexpr const char BuilderSuffix[] = "::Builder";

    CodeGenCpp::CodeGenCpp(const CodeGenRequest& request)
        : m_request(request)
        , m_writer(Allocator::GetDefault())
    {}

    bool CodeGenCpp::Generate()
    {
        m_namespaceName.Clear();
        for (char ch : m_request.schema.root.name)
        {
            if (ch == '.')
                m_namespaceName += "::";
            else
                m_namespaceName += ch;
        }

        m_writer.Reserve(8192);

        GenHeader();
        if (!FlushToFile(".hsc.h"))
            return false;

        m_writer.Clear();

        GenSource();
        if (!FlushToFile(".hsc.cpp"))
            return false;

        m_writer.Clear();

        return true;
    }

    void CodeGenCpp::GenHeader()
    {
        m_writer.Write("// Generated by the Harvest Schema compiler\n\n");
        m_writer.Write("#pragma once\n\n");

        m_writer.WriteLine("#include \"he/core/assert.h\"");
        m_writer.WriteLine("#include \"he/core/types.h\"");
        m_writer.WriteLine("#include \"he/schema/layout.h\"");
        m_writer.WriteLine("#include \"he/schema/schema.h\"\n");

        bool hasUserInclude = false;
        for (uint32_t i = 0; i < m_request.schema.imports.Size(); ++i)
        {
            const Import& import = m_request.schema.imports[i];
            if (import.path.IsEmpty())
                continue;

            hasUserInclude = true;

            m_writer.WriteLine("#include \"{}.hsc.h\"", GetPathWithoutExtension(import.path));
        }

        if (hasUserInclude)
            m_writer.Write('\n');

        WriteDeclInfo(m_request.schema.root);
        m_writer.Write('\n');

        if (!m_request.schema.root.name.IsEmpty())
        {
            m_writer.WriteLine("namespace {}", m_namespaceName);
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
        }

        for (const Declaration& decl : m_request.schema.root.children)
        {
            WriteDecl(decl, m_request.schema.root);
        }

        // Close the namespace
        if (!m_request.schema.root.name.IsEmpty())
        {
            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        m_writer.Write('\n');
    }

    void CodeGenCpp::WriteDecl(const Declaration& decl, const Declaration& scope)
    {
        switch (decl.kind)
        {
            case DeclKind::None: break;
            case DeclKind::Attribute: WriteAttributeDecl(decl, scope); break;
            case DeclKind::Const: WriteConstDecl(decl, scope); break;
            case DeclKind::Enum: WriteEnumDecl(decl, scope); break;
            case DeclKind::Interface: WriteInterfaceDecl(decl, scope); break;
            case DeclKind::Struct: WriteStructDecl(decl, scope); break;
        }
    }

    void CodeGenCpp::WriteAttributeDecl(const Declaration& decl, const Declaration& scope)
    {
        HE_UNUSED(scope);
        m_writer.WriteLine("struct {} {{ using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">; }};", decl.name, decl.id);
    }

    void CodeGenCpp::WriteConstDecl(const Declaration& decl, const Declaration& scope)
    {
        m_writer.WriteIndent();
        if (decl.parentId != m_request.schema.root.id)
            m_writer.Write("static ");

        const Type& type = decl.const_.type;
        const bool isInline = type.kind == TypeKind::Bool || type.kind == TypeKind::Enum || type.kind == TypeKind::String || IsArithmetic(type.kind);

        if (isInline)
            m_writer.Write("inline constexpr ");
        else
            m_writer.Write("extern const ");

        if (type.kind == TypeKind::String)
            m_writer.Write("char");
        else
            WriteType(type, scope, ReaderSuffix);

        m_writer.Write(' ');
        m_writer.Write(decl.name);

        if (type.kind == TypeKind::Array)
            m_writer.Write("[{}]", type.array_.size);
        else if (type.kind == TypeKind::String)
            m_writer.Write("[]");

        if (isInline)
        {
            m_writer.Write(" = ");
            WriteValue(type, scope, decl.const_.value);
        }

        m_writer.Write(";\n");
    }

    void CodeGenCpp::WriteEnumDecl(const Declaration& decl, const Declaration& scope)
    {
        HE_UNUSED(scope);
        m_writer.WriteLine("enum class {} : uint16_t", decl.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const Enumerator& e : decl.enum_.enumerators)
        {
            m_writer.WriteLine("{} = {},", e.name, e.ordinal);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteInterfaceDecl(const Declaration& decl, const Declaration& scope)
    {
        WriteTemplate(decl);
        m_writer.WriteIndent();
        m_writer.Write("class {}", decl.name);
        if (decl.interface_.super.kind == TypeKind::Interface)
        {
            const Type& superType = decl.interface_.super;
            const Declaration& super = m_request.GetDecl(superType.interface_.id);
            m_writer.Write(" : public ");
            WriteName(super, scope, superType.interface_.brand, ReaderSuffix);
        }
        m_writer.Write('\n');
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("virtual ~{}() {{}}", decl.name);
        m_writer.WriteLine("using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">;", decl.id);
        if (decl.interface_.super.kind == TypeKind::Interface)
        {
            const Type& superType = decl.interface_.super;
            const Declaration& super = m_request.GetDecl(superType.interface_.id);
            m_writer.WriteIndent();
            m_writer.Write("using Super = ");
            WriteName(super, scope, superType.interface_.brand, ReaderSuffix);
            m_writer.Write(";\n");
        }
        m_writer.Write('\n');

        for (const Declaration& child : decl.children)
        {
            WriteDecl(child, decl);
        }


        for (const Method& method : decl.interface_.methods)
        {
            const Declaration& params = m_request.GetDecl(method.paramStruct);
            const Declaration& result = m_request.GetDecl(method.resultStruct);
            m_writer.WriteLine("virtual {}::Reader {}({}::Reader) = 0;", result.name, method.name, params.name);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteStructDecl(const Declaration& decl, const Declaration& scope)
    {
        HE_UNUSED(scope);
        WriteTemplate(decl);
        m_writer.WriteLine("struct {} final", decl.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{}() = delete;", decl.name);
        m_writer.WriteLine("using DeclInfo = ::he::schema::DeclInfo<" HE_ID_FMT ">;\n", decl.id);

        for (const Declaration& child : decl.children)
        {
            WriteDecl(child, decl);
        }
        if (!decl.children.IsEmpty())
            m_writer.Write('\n');

        if (decl.struct_.isUnion)
        {
            m_writer.WriteLine("enum class Tag : uint16_t");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            String upperCamelName(Allocator::GetTemp());
            for (const Field& field : decl.struct_.fields)
            {
                upperCamelName = field.name;
                upperCamelName[0] = ToUpper(upperCamelName[0]);

                m_writer.WriteLine("{} = {},", upperCamelName, field.unionTag);
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};\n");
        }

        m_writer.WriteLine("class Reader final : public ::he::schema::StructReader");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("using StructType = {};", decl.name);
        m_writer.WriteLine("using Super = ::he::schema::StructReader;\n");

        if (decl.struct_.isUnion)
        {
            m_writer.WriteLine("Tag GetTag() const {{ return Super::GetDataField<Tag>({}); }}\n", decl.struct_.unionTagOffset);
        }

        for (const Field& field : decl.struct_.fields)
        {
            WriteFieldGetDecl(field, decl, true);
            m_writer.Write('\n');
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");

        m_writer.WriteLine("class Builder final : public ::he::schema::StructBuilder");
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("using StructType = {};", decl.name);
        m_writer.WriteLine("using Super = ::he::schema::StructBuilder;\n");
        m_writer.WriteLine("Reader AsReader() const { return Reader(Super::AsReader()); }");
        m_writer.WriteLine("operator Reader() const { return AsReader(); }\n");

        if (decl.struct_.isUnion)
        {
            m_writer.WriteLine("Tag GetTag() const {{ return Super::GetDataField<Tag>({}); }}\n", decl.struct_.unionTagOffset);
        }

        for (const Field& field : decl.struct_.fields)
        {
            WriteFieldGetDecl(field, decl, false);
            WriteFieldSetDecl(field, decl);
            m_writer.Write('\n');
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::WriteFieldGetDecl(const Field& field, const Declaration& decl, bool isReader)
    {
        HE_ASSERT(decl.kind == DeclKind::Struct);

        String upperCamelName(field.name, Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        if (decl.struct_.isUnion)
        {
            m_writer.WriteLine("bool Is{0}() const {{ return GetTag() == Tag::{0}; }}", upperCamelName);
        }

        if (field.isUnion || field.isGroup)
        {
            m_writer.WriteLine("{0}::Reader Get{0}() const {{ return {0}::Reader(*this); }}", upperCamelName);
        }
        else if (field.type.kind == TypeKind::Void)
        {
            m_writer.WriteLine("bool Has{}() const {{ return false; }}", upperCamelName, field.index);
            if (decl.struct_.isUnion)
                m_writer.WriteLine("::he::schema::Void Get{0}() const {{ HE_ASSERT(Is{0}()); return {{}}; }}", upperCamelName);
            else
                m_writer.WriteLine("::he::schema::Void Get{}() const {{ return {{}}; }}", upperCamelName);
        }
        else if (IsPointer(field.type))
        {
            if (decl.struct_.isUnion)
                m_writer.WriteLine("bool Has{0}() const {{ return Is{0}() && Super::HasPointerField({1}); }}", upperCamelName, field.index);
            else
                m_writer.WriteLine("bool Has{}() const {{ return Super::HasPointerField({}); }}", upperCamelName, field.index);

            m_writer.WriteIndent();
            WriteType(field.type, decl, isReader ? ReaderSuffix : BuilderSuffix);
            m_writer.Write(" Get{}() const {{ ", upperCamelName);

            if (decl.struct_.isUnion)
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            const bool isArray = field.type.kind == TypeKind::Array;
            const bool hasDefault = isReader && field.defaultValue.kind != TypeKind::Void;

            if (isArray)
            {
                m_writer.Write("return Super::TryGetPointerArrayField<");
                WriteType(*field.type.array_.elementType, decl, nullptr);
                m_writer.Write(">({}, {}", field.index, field.type.array_.size);
                if (hasDefault)
                    m_writer.Write(", ");
            }
            else
            {
                m_writer.Write("return Super::GetPointerField({}).TryGet{}", field.index, field.type.kind);
                if (field.type.kind != TypeKind::String)
                {
                    const Type& t = field.type.kind == TypeKind::List ? *field.type.list_.elementType : field.type;
                    m_writer.Write('<');
                    WriteType(t, decl, nullptr);
                    m_writer.Write('>');
                }
                m_writer.Write('(');
            }
            if (hasDefault)
            {
                m_writer.Write("::he::schema::DeclInfo<" HE_ID_FMT ">::DefaultValue + {}", decl.id, 0);
            }
            m_writer.Write("); }\n");
        }
        else
        {
            if (decl.struct_.isUnion)
                m_writer.WriteLine("bool Has{0}() const {{ return Is{0}() && Super::HasDataField({1}); }}", upperCamelName, field.index);
            else
                m_writer.WriteLine("bool Has{}() const {{ return Super::HasDataField({}); }}", upperCamelName, field.index);

            const bool isArray = field.type.kind == TypeKind::Array;
            const bool hasDefault = (isReader || !isArray) && field.defaultValue.kind != TypeKind::Void;

            m_writer.WriteIndent();
            if (isArray)
            {
                m_writer.Write("::he::Span<");
                if (isReader)
                    m_writer.Write("const ");
                WriteType(*field.type.array_.elementType, decl, nullptr);
                m_writer.Write(">");
            }
            else
            {
                WriteType(field.type, decl, nullptr);
            }
            m_writer.Write(" Get{}() const {{ ", upperCamelName);

            if (decl.struct_.isUnion)
                m_writer.Write("HE_ASSERT(Is{}()); ", upperCamelName);

            if (isArray)
            {
                if (hasDefault)
                {
                    m_writer.Write("static const ");
                    WriteType(*field.type.array_.elementType, decl, nullptr);
                    m_writer.Write(" {}_DefaultValue[]", upperCamelName);
                    WriteValue(field.type, decl, field.defaultValue);
                    m_writer.Write("; ");
                }
                m_writer.Write("return Super::TryGetDataArrayField<");
                WriteType(*field.type.array_.elementType, decl, nullptr);
            }
            else
            {
                m_writer.Write("return Super::TryGetDataField<");
                WriteType(field.type, decl, nullptr);
            }
            m_writer.Write(">({}, {}", field.index, field.dataOffset);
            if (isArray)
            {
                m_writer.Write(", {}", field.type.array_.size);
                if (hasDefault)
                {
                    m_writer.Write(", {}_DefaultValue", upperCamelName);
                }
            }
            else if (hasDefault)
            {
                m_writer.Write(", ");
                WriteValue(field.type, decl, field.defaultValue);
            }
            m_writer.Write("); }\n");
        }
    }

    void CodeGenCpp::WriteFieldSetDecl(const Field& field, const Declaration& decl)
    {
        HE_ASSERT(decl.kind == DeclKind::Struct);

        String upperCamelName(field.name, Allocator::GetTemp());
        upperCamelName[0] = ToUpper(upperCamelName[0]);

        const bool fieldIsPointer = IsPointer(field.type);

        m_writer.WriteIndent();
        m_writer.Write("void Set{}(", upperCamelName);
        if (fieldIsPointer)
            m_writer.Write("const ");
        WriteType(field.type, decl, ReaderSuffix);
        if (fieldIsPointer)
            m_writer.Write("&");
        m_writer.Write(" value) { ");
        if (decl.struct_.isUnion)
            m_writer.Write("Super::SetDataField<Tag>({}, Tag::{}); ", decl.struct_.unionTagOffset, upperCamelName);
        if (fieldIsPointer)
        {
            m_writer.Write("Super::GetPointerField({}).Set(value);", field.index);
        }
        else
        {
            m_writer.Write("Super::SetDataField<");
            WriteType(field.type, decl, nullptr);
            m_writer.Write(">({}, {}, value);", field.index, field.dataOffset);
        }
        m_writer.Write(" }\n");
    }

    void CodeGenCpp::GenSource()
    {
        m_writer.Write("// Generated by the Harvest Schema compiler\n\n");

        StringView baseName = GetPathWithoutExtension(m_request.fileName);
        m_writer.WriteLine("#include \"{}.hsc.h\"", baseName);
    }

    bool CodeGenCpp::FlushToFile(const char* suffix)
    {
        String filePath(m_request.outDir, Allocator::GetTemp());
        ConcatPath(filePath, m_request.fileName);
        RemoveExtension(filePath);
        filePath += suffix;

        const StringView code = m_writer.Str();

        File f;
        if (!f.Open(filePath.Data(), FileOpenMode::WriteTruncate))
            return false;

        if (!f.Write(code.Data(), code.Size()))
            return false;

        return true;
    }

    void CodeGenCpp::WriteDeclInfo(const Declaration& decl)
    {
        const uint32_t fieldCount = decl.kind == DeclKind::Struct ? decl.struct_.fields.Size() : 0;
        const uint16_t dataWordSize = decl.kind == DeclKind::Struct ? decl.struct_.dataWordSize : 0;
        const uint16_t pointerCount = decl.kind == DeclKind::Struct ? decl.struct_.pointerCount : 0;

        m_writer.WriteLine("HE_SCHEMA_DECL_INFO(" HE_ID_FMT ", " HE_ID_FMT ", {}, {}, {}, {});",
            decl.id, decl.parentId, decl.kind, fieldCount, dataWordSize, pointerCount);

        for (const Declaration& child : decl.children)
        {
            WriteDeclInfo(child);
        }
    }

    void CodeGenCpp::WriteName(const Declaration& decl, const Declaration& scope, const Brand& brand, const char* pointerSuffix)
    {
        if (decl.parentId != scope.id && decl.parentId != scope.parentId && decl.parentId != m_request.schema.root.id)
        {
            const Declaration& parent = m_request.GetDecl(decl.parentId);
            WriteName(parent, scope, brand, pointerSuffix);
            m_writer.Write("::");
        }

        m_writer.Write(decl.name);

        for (const Brand::Scope& brandScope : brand.scopes)
        {
            if (brandScope.scopeId == decl.id)
            {
                m_writer.Write("<");
                for (uint32_t i = 0; i < brandScope.params.Size(); ++i)
                {
                    const Type* t = brandScope.params[i];
                    WriteType(*t, scope, pointerSuffix);
                    if (i < (brandScope.params.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(">");
                break;
            }
        }
    }

    void CodeGenCpp::WriteTemplate(const Declaration& decl)
    {
        if (decl.typeParams.IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("template <");
        for (uint32_t i = 0; i < decl.typeParams.Size(); ++i)
        {
            m_writer.Write("typename ");
            m_writer.Write(decl.typeParams[i]);
            if (i < (decl.typeParams.Size() - 1))
                m_writer.Write(", ");
        }
        m_writer.Write(">\n");
    }

    void CodeGenCpp::WriteType(const Type& type, const Declaration& scope, const char* pointerSuffix)
    {
        switch (type.kind)
        {
            case TypeKind::Void: m_writer.Write("::he::schema::Void"); break;
            case TypeKind::Bool: m_writer.Write("bool"); break;
            case TypeKind::Int8: m_writer.Write("int8_t"); break;
            case TypeKind::Int16: m_writer.Write("int16_t"); break;
            case TypeKind::Int32: m_writer.Write("int32_t"); break;
            case TypeKind::Int64: m_writer.Write("int64_t"); break;
            case TypeKind::Uint8: m_writer.Write("uint8_t"); break;
            case TypeKind::Uint16: m_writer.Write("uint16_t"); break;
            case TypeKind::Uint32: m_writer.Write("uint32_t"); break;
            case TypeKind::Uint64: m_writer.Write("uint64_t"); break;
            case TypeKind::Float32: m_writer.Write("float"); break;
            case TypeKind::Float64: m_writer.Write("double"); break;
            case TypeKind::Array:
                HE_ASSERT(type.array_.elementType);
                if (IsPointer(*type.array_.elementType))
                {
                    m_writer.Write("::he::schema::List<");
                    WriteType(*type.array_.elementType, scope, pointerSuffix);
                    m_writer.Write(">");
                }
                else
                {
                    m_writer.Write("::he::Span<const ");
                    WriteType(*type.array_.elementType, scope, pointerSuffix);
                    m_writer.Write(">");
                }
                break;
            case TypeKind::Blob:
                m_writer.Write("::he::schema::List<uint8_t>");
                break;
            case TypeKind::String:
                m_writer.Write("::he::schema::String");
                break;
            case TypeKind::List:
                HE_ASSERT(type.list_.elementType);
                m_writer.Write("::he::schema::List<");
                WriteType(*type.list_.elementType, scope, pointerSuffix);
                m_writer.Write(">");
                break;
            case TypeKind::Enum:
            {
                const Declaration& decl = m_request.GetDecl(type.enum_.id);
                HE_ASSERT(decl.kind == DeclKind::Enum);
                WriteName(decl, scope, type.enum_.brand, pointerSuffix);
                break;
            }
            case TypeKind::Struct:
            {
                const Declaration& decl = m_request.GetDecl(type.struct_.id);
                HE_ASSERT(decl.kind == DeclKind::Struct);
                WriteName(decl, scope, type.struct_.brand, pointerSuffix);
                break;
            }
            case TypeKind::Interface:
            {
                const Declaration& decl = m_request.GetDecl(type.interface_.id);
                HE_ASSERT(decl.kind == DeclKind::Interface);
                WriteName(decl, scope, type.interface_.brand, pointerSuffix);
                break;
            }
            case TypeKind::AnyPointer:
            {
                if (type.any_.paramScopeId == 0)
                {
                    m_writer.Write("AnyPointer");
                }
                else
                {
                    const Declaration& decl = m_request.GetDecl(type.any_.paramScopeId);
                    m_writer.Write(decl.typeParams[type.any_.paramIndex]);
                }
                break;
            }
        }

        if (pointerSuffix && IsPointer(type))
        {
            m_writer.Write(pointerSuffix);
        }
    }

    void CodeGenCpp::WriteValue(const Type& type, const Declaration& scope, const Value& value)
    {
        HE_ASSERT(type.kind == value.kind);

        switch (value.kind)
        {
            case TypeKind::Void: break;
            case TypeKind::Bool: m_writer.Write("{}", value.b); break;
            case TypeKind::Int8: m_writer.Write("{}", value.i8); break;
            case TypeKind::Int16: m_writer.Write("{}", value.i16); break;
            case TypeKind::Int32: m_writer.Write("{}", value.i32); break;
            case TypeKind::Int64: m_writer.Write("{}", value.i64); break;
            case TypeKind::Uint8: m_writer.Write("{}", value.u8); break;
            case TypeKind::Uint16: m_writer.Write("{}", value.u16); break;
            case TypeKind::Uint32: m_writer.Write("{}", value.u32); break;
            case TypeKind::Uint64: m_writer.Write("{}", value.u64); break;
            case TypeKind::Float32: m_writer.Write("{}", value.f32); break;
            case TypeKind::Float64: m_writer.Write("{}", value.f64); break;
            case TypeKind::Array:
            {
                m_writer.Write("{ ");
                for (uint32_t i = 0; i < value.array.Size(); ++i)
                {
                    WriteValue(*type.array_.elementType, scope, *value.array[i]);
                    if (i < (value.array.Size() - 1))
                        m_writer.Write(", ");
                }
                m_writer.Write(" }");
                break;
            }
            case TypeKind::Blob:
                break;
        //     {
        //         m_writer.Write("{ ");
        //         for (uint32_t i = 0; i < value.blob.Size(); ++i)
        //         {
        //             m_writer.Write("{:#4x}", value.blob[i]);
        //             if (i < (value.blob.Size() - 1))
        //                 m_writer.Write(", ");
        //         }
        //         m_writer.Write(" }");
        //         break;
        //     }
            case TypeKind::String:
                m_writer.Write("\"{}\"", value.str);
                break;
            case TypeKind::List:
                break;
        //         m_writer.Write('[');
        //         for (uint32_t i = 0; i < value.list.Size(); ++i)
        //         {
        //             WriteValue(*type.list_.elementType, *value.list[i]);

        //             if (i != (value.list.Size() - 1))
        //                 m_writer.Write(", ");
        //         }
        //         m_writer.Write(']');
        //         break;
            case TypeKind::Enum:
            {
                const Declaration& decl = m_request.GetDecl(type.enum_.id);
                HE_ASSERT(decl.kind == DeclKind::Enum);
                WriteName(decl, scope, type.enum_.brand, nullptr);
                m_writer.Write("::");
                for (const Enumerator& e : decl.enum_.enumerators)
                {
                    if (e.ordinal == value.enum_)
                    {
                        m_writer.Write(e.name);
                        break;
                    }
                }
                break;
            }
            case TypeKind::Struct:
                break;
        //     {
        //         const Declaration& decl = m_request.GetDecl(type.struct_.id);
        //         HE_ASSERT(decl.kind == DeclKind::Struct);

        //         m_writer.Write("{ ");
        //         for (uint32_t i = 0; i < value.struct_.Size(); ++i)
        //         {
        //             const Value::StructValue& v = value.struct_[i];
        //             const Field* field = nullptr;
        //             for (uint32_t j = 0; j < decl.struct_.fields.Size(); ++j)
        //             {
        //                 if (decl.struct_.fields[j].name == v.fieldName)
        //                 {
        //                     field = &decl.struct_.fields[j];
        //                     break;
        //                 }
        //             }
        //             HE_ASSERT(field);
        //             m_writer.Write("{} = ", v.fieldName);
        //             WriteValue(field->type, *v.value);

        //             if (i != (value.list.Size() - 1))
        //                 m_writer.Write(", ");
        //         }
        //         m_writer.Write(" }");
        //         break;
        //     }
            case TypeKind::Interface:
                break;
            case TypeKind::AnyPointer:
                break;
        }
    }

    void CodeGenCpp::WriteWithReplace(StringView input, char what, StringView with)
    {
        for (char ch : input)
        {
            if (ch == what)
            {
                m_writer.Write(with);
            }
            else
            {
                m_writer.Write(ch);
            }
        }
    }

    bool GenerateCpp(const CodeGenRequest& request)
    {
        CodeGenCpp generator(request);
        if (!generator.Generate())
            return false;

        return true;
    }
}
