// Copyright Chad Engler

#include "codegen_cpp.h"

#include "he/core/ascii.h"
#include "he/core/allocator.h"
#include "he/core/assert.h"
#include "he/core/file.h"
#include "he/core/hash.h"
#include "he/core/path.h"
#include "he/core/string.h"
#include "he/core/string_fmt.h"
#include "he/core/string_view.h"
#include "he/core/string_view_fmt.h"

namespace he::schema
{
    #define HE_HEX_FMT "{:#0{}x}"
    #define HE_HEX_VAL(x) x, (2 + (sizeof(x) * 2))

    constexpr uint32_t UnionFieldId_tag = FNV32::HashString("tag");
    constexpr uint32_t UnionFieldId_value = FNV32::HashString("value");

    bool CodeGenCpp::Generate()
    {
        m_namespacePrefix.Clear();
        for (char ch : m_schema.namespaceName)
        {
            if (ch == '.')
                m_namespacePrefix += "::";
            else
                m_namespacePrefix += ch;
        }

        m_writer.Reserve(8192);

        GenHeader();
        if (!FlushToFile(".generated.h"))
            return false;

        m_writer.Clear();

        GenSource();
        if (!FlushToFile(".generated.cpp"))
            return false;

        return true;
    }

    void CodeGenCpp::GenHeader()
    {
        m_writer.Write("// Generated by the Harvest Schema compiler\n\n");
        m_writer.Write("#pragma once\n\n");

        GenHdr_Includes();

        if (!m_schema.namespaceName.IsEmpty())
        {
            m_writer.WriteIndent();
            m_writer.Write("namespace ");
            WriteWithReplace(m_schema.namespaceName, '.', "::");
            m_writer.Write('\n');
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();
        }

        for (const ObjectDef& obj : m_schema.objects)
        {
            switch (obj.type)
            {
                case ObjectDef::Type::Alias:
                    GenHdr_Alias(m_schema.aliases[obj.index]);
                    break;
                case ObjectDef::Type::Attribute:
                    GenHdr_Attribute(m_schema.attributes[obj.index]);
                    break;
                case ObjectDef::Type::Const:
                    GenHdr_Const(m_schema.consts[obj.index]);
                    break;
                case ObjectDef::Type::Enum:
                    GenHdr_Enum(m_schema.enums[obj.index]);
                    break;
                case ObjectDef::Type::Interface:
                    GenHdr_Interface(m_schema.interfaces[obj.index]);
                    break;
                case ObjectDef::Type::Struct:
                    GenHdr_Struct(m_schema.structs[obj.index]);
                    break;
                case ObjectDef::Type::Union:
                    GenHdr_Union(m_schema.unions[obj.index]);
                    break;
            }
        }

        // Close the namespace
        if (!m_schema.namespaceName.IsEmpty())
        {
            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
        m_writer.Write('\n');
    }

    void CodeGenCpp::GenHdr_Includes()
    {
        // Harvest Engine includes
        m_writer.WriteLine("#include \"he/core/types.h\"");
        if (IsTypeUsed(m_schema, BaseType::Enum))
            m_writer.WriteLine("#include \"he/core/enum_ops.h\"");

        if (!m_options.zeroCopy)
        {
            if (IsTypeUsed(m_schema, BaseType::String))
                m_writer.Write("#include \"he/core/string.h\"\n");
            if (IsTypeUsed(m_schema, BaseType::Pointer))
                m_writer.WriteLine("#include \"he/core/unique_ptr.h\"\n");
            if (IsTypeUsed(m_schema, BaseType::Vector))
                m_writer.WriteLine("#include \"he/core/vector.h\"");
        }

        if (m_options.buffer)
        {
            m_writer.WriteLine("#include \"he/schema/buffer.h\"");
        }

        m_writer.Write('\n');

        // User defined includes
        bool hasUserInclude = false;
        for (uint32_t i = 0; i < m_schema.imports.Size(); ++i)
        {
            const String& import = m_schema.imports[i];
            if (import.IsEmpty())
                continue;

            hasUserInclude = true;

            m_writer.WriteLine("#include \"{}.generated.h\"", GetPathWithoutExtension(import));
        }

        if (hasUserInclude)
            m_writer.Write('\n');

        if (!m_options.zeroCopy)
        {
            // STL includes
            if (IsTypeUsed(m_schema, BaseType::List))
                m_writer.WriteLine("#include <list>");
            if (IsTypeUsed(m_schema, BaseType::Map))
                m_writer.WriteLine("#include <unordered_map>");
            if (IsTypeUsed(m_schema, BaseType::Set))
                m_writer.WriteLine("#include <unordered_set>");
            m_writer.Write('\n');
        }
    }

    void CodeGenCpp::GenHdr_Alias(const AliasDef& def)
    {
        WriteGenericDecl(def.typeParams);
        m_writer.WriteIndent();
        m_writer.Write("using {} = ", def.name);
        WriteNativeType(def.type);
        WriteArraySize(def.type);
        m_writer.Write(";\n");
    }

    void CodeGenCpp::GenHdr_Attribute(const AttributeDef& def)
    {
        HE_UNUSED(def);
    }

    void CodeGenCpp::GenHdr_Const(const ConstDef& def)
    {
        m_writer.WriteIndent();
        m_writer.Write("constexpr {1} {0}{2} = ",
            def.name,
            def.base == BaseType::String ? "char" : GetScalarType(def.base),
            def.base == BaseType::String ? "[] " : "");
        WriteNativeValue(def.base, def.value);
        m_writer.Write(";\n");
    }

    void CodeGenCpp::GenHdr_Enum(const EnumDef& def)
    {
        const bool isFlags = HasAttribute("Flags", def.attributes);

        m_writer.WriteLine("enum class {} : {}", def.name, GetScalarType(def.base));
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const EnumValueDef& val : def.values)
        {
            m_writer.WriteIndent();
            m_writer.Write(val.name);
            m_writer.Write(" = ");
            if (isFlags)
                WriteUnsignedAsHex(def.base, val.value);
            else
                WriteNativeValue(def.base, val.value);
            m_writer.Write(",\n");
        }

        m_writer.Write('\n');
        if (isFlags)
        {
            m_writer.WriteLine("None = 0,");

            switch (def.base)
            {
                case BaseType::Uint8: m_writer.WriteLine("All = 0xff,"); break;
                case BaseType::Uint16: m_writer.WriteLine("All = 0xffff,"); break;
                case BaseType::Uint32: m_writer.WriteLine("All = 0xffffffff,"); break;
                case BaseType::Uint64: m_writer.WriteLine("All = 0xffffffffffffffff,"); break;
            }
        }
        else
        {
            m_writer.WriteLine("_Count,");
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");

        if (isFlags)
        {
            m_writer.WriteLine("HE_ENUM_FLAGS({});\n\n", def.name);
        }
    }

    void CodeGenCpp::GenHdr_Interface(const InterfaceDef& def)
    {
        WriteGenericDecl(def.typeParams);
        m_writer.WriteIndent();
        m_writer.Write("class ");
        m_writer.Write(def.name);
        if (!def.implements.IsEmpty())
        {
            m_writer.Write(" : ");
            for (uint32_t i = 0; i < def.implements.Size(); ++i)
            {
                m_writer.Write("public ");
                WriteNativeType(def.implements[i]);
                if (i < (def.implements.Size() - 1))
                    m_writer.Write(", ");
            }
        }
        m_writer.Write('\n');
        m_writer.WriteLine("{");
        m_writer.WriteLine("public:");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("static constexpr uint32_t TypeId = " HE_HEX_FMT ";", HE_HEX_VAL(def.id));

        for (const MethodDef& method : def.methods)
        {
            m_writer.Write("static constexpr uint32_t MethodId_{} = " HE_HEX_FMT ";", method.name, HE_HEX_VAL(method.id));
        }
        m_writer.Write('\n');

        m_writer.WriteLine("virtual ~{}() {{}}", def.name);

        for (const ObjectDef& obj : def.objects)
        {
            switch (obj.type)
            {
                case ObjectDef::Type::Alias:
                    GenHdr_Alias(def.aliases[obj.index]);
                    break;
                case ObjectDef::Type::Attribute:
                    // GenHdr_Attribute(def.attributes[obj.index]);
                    break;
                case ObjectDef::Type::Const:
                    GenHdr_Const(def.consts[obj.index]);
                    break;
                case ObjectDef::Type::Enum:
                    GenHdr_Enum(def.enums[obj.index]);
                    break;
                case ObjectDef::Type::Interface:
                    // GenHdr_Interface(def.interfaces[obj.index]);
                    break;
                case ObjectDef::Type::Struct:
                    GenHdr_Struct(def.structs[obj.index]);
                    break;
                case ObjectDef::Type::Union:
                    // GenHdr_Union(def.unions[obj.index]); // TODO: UNCOMMENT
                    break;
            }
        }

        for (const MethodDef& method : def.methods)
        {
            m_writer.WriteIndent();
            m_writer.Write("virtual ");
            WriteNativeType(method.returnType);
            m_writer.Write(' ');
            m_writer.Write(method.name);
            m_writer.Write('(');

            for (uint32_t i = 0; i < method.parameters.Size(); ++i)
            {
                const MethodParamDef& param = method.parameters[i];
                WriteParamType(param.type);
                m_writer.Write(' ');
                m_writer.Write(param.name);
                if (i < (method.parameters.Size() - 1))
                    m_writer.Write(", ");
            }
            m_writer.Write(") = 0;\n");
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::GenHdr_Struct(const StructDef& def)
    {
        WriteGenericDecl(def.typeParams);
        m_writer.WriteIndent();
        m_writer.Write("struct ");
        m_writer.Write(def.name);
        if (!m_options.zeroCopy && (def.extends.base != BaseType::Unknown || !def.extends.name.IsEmpty()))
        {
            m_writer.Write(" : ");
            WriteNativeType(def.extends);
        }
        m_writer.Write('\n');
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("static constexpr uint32_t TypeId = " HE_HEX_FMT ";\n", HE_HEX_VAL(def.id));

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("static constexpr uint32_t FieldId_{} = " HE_HEX_FMT ";", field.name, HE_HEX_VAL(field.id));
        }
        if (!def.fields.IsEmpty())
            m_writer.Write('\n');

        m_writer.WriteLine("static constexpr uint32_t FieldCount = {};\n", def.fields.Size());

        if (m_options.reflection && !m_options.zeroCopy && !def.fields.IsEmpty())
        {
            m_writer.WriteLine("static const he::schema::FieldInfo Fields[FieldCount];\n");
        }

        for (const ObjectDef& obj : def.objects)
        {
            switch (obj.type)
            {
                case ObjectDef::Type::Alias:
                    GenHdr_Alias(def.aliases[obj.index]);
                    break;
                case ObjectDef::Type::Attribute:
                    // GenHdr_Attribute(def.attributes[obj.index]);
                    break;
                case ObjectDef::Type::Const:
                    GenHdr_Const(def.consts[obj.index]);
                    break;
                case ObjectDef::Type::Enum:
                    GenHdr_Enum(def.enums[obj.index]);
                    break;
                case ObjectDef::Type::Interface:
                    // GenHdr_Interface(def.interfaces[obj.index]);
                    break;
                case ObjectDef::Type::Struct:
                    GenHdr_Struct(def.structs[obj.index]);
                    break;
                case ObjectDef::Type::Union:
                    GenHdr_Union(def.unions[obj.index]);
                    break;
            }
            m_writer.Write('\n');
        }

        if (m_options.buffer)
        {
            m_writer.WriteIndent();
            m_writer.Write("class BufferReader : ");
            if (def.extends.base != BaseType::Unknown || !def.extends.name.IsEmpty())
            {
                m_writer.Write("public ");
                WriteNativeType(def.extends);
                m_writer.Write("::BufferReader");
            }
            else
            {
                m_writer.Write("private he::schema::StructureReader");
            }
            m_writer.Write('\n');
            m_writer.WriteLine("{");
            m_writer.WriteLine("public:");
            m_writer.IncreaseIndent();

            for (const FieldDef& field : def.fields)
            {
                m_writer.WriteIndent();
                m_writer.Write("const auto* {}{}() const {{ return GetFieldPointer<",
                    ToUpper(field.name[0]), field.name.Data() + 1);
                WriteBufferType(field.type);
                m_writer.Write(">(FieldId_{}); }}\n", field.name);
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};\n");
        }

        if (!m_options.zeroCopy)
        {
            for (const FieldDef& field : def.fields)
            {
                m_writer.WriteIndent();
                WriteNativeType(field.type);
                m_writer.Write(' ');
                // m_writer.Write(" m_");
                m_writer.Write(field.name);
                WriteArraySize(field.type);
                m_writer.Write("{};\n");
            }
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");
    }

    void CodeGenCpp::GenHdr_Union(const UnionDef& def)
    {
        m_writer.WriteLine("struct {}", def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("static constexpr uint32_t TypeId = " HE_HEX_FMT ";\n", HE_HEX_VAL(def.id));

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("static constexpr uint32_t TagId_{} = " HE_HEX_FMT ";", field.name, HE_HEX_VAL(field.id));
        }
        if (!def.fields.IsEmpty())
            m_writer.Write('\n');

        m_writer.WriteLine("static constexpr uint32_t FieldId_tag = " HE_HEX_FMT ";", HE_HEX_VAL(UnionFieldId_tag));
        m_writer.WriteLine("static constexpr uint32_t FieldId_value = " HE_HEX_FMT ";\n", HE_HEX_VAL(UnionFieldId_value));
        m_writer.WriteLine("static constexpr uint32_t FieldCount = 2;\n");

        if (m_options.reflection && !m_options.zeroCopy)
        {
            m_writer.WriteLine("static const he::schema::FieldInfo Fields[FieldCount];\n");
        }

        if (m_options.buffer)
        {
            m_writer.WriteLine("class BufferReader : private he::schema::UnionReader");
            m_writer.WriteLine("{");
            m_writer.WriteLine("public:");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("using he::schema::UnionReader::GetTagId;");
            m_writer.WriteLine("using he::schema::UnionReader::IsUnset;\n");

            for (const FieldDef& field : def.fields)
            {
                m_writer.WriteIndent();
                m_writer.Write("const auto* {}{}() const {{ return GetTagId() == TagId_{} ? Get<",
                    ToUpper(field.name[0]), field.name.Data() + 1, field.name);
                WriteBufferType(field.type);
                m_writer.Write(">() : nullptr; }\n");
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("};\n");
        }

        if (!m_options.zeroCopy)
        {
            m_writer.WriteLine("uint32_t tag;");
            m_writer.WriteLine("union");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            for (const FieldDef& field : def.fields)
            {
                m_writer.WriteIndent();
                WriteNativeType(field.type);
                m_writer.Write(' ');
                m_writer.Write(field.name);
                WriteArraySize(field.type);
                m_writer.Write(";\n");
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("} value;");
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};\n");
    }

    void CodeGenCpp::GenSource()
    {
        m_writer.WriteLine("// Generated by the Harvest Schema compiler\n");
        m_writer.WriteLine("#include \"{}.generated.h\"\n", GetPathWithoutExtension(m_options.fileName));

        if (m_options.json)
        {
            m_writer.WriteLine("#include \"he/core/string_view.h\"");
        }

        if (m_options.buffer)
        {
            m_writer.WriteLine("#include \"he/schema/buffer.h\"");
        }

        if (m_options.json)
        {
            m_writer.WriteLine("#include \"he/schema/json.h\"\n");
            m_writer.WriteLine("#include \"rapidjson/document.h\"");
        }

        m_writer.Write('\n');

        GenSrc_StringImpl();
        GenSrc_ReflectionImpl();

        GenSrc_BufferImpl();
        GenSrc_JsonImpl();
    }

    void CodeGenCpp::GenSrc_BufferImpl()
    {
        if (m_options.buffer)
        {
            m_writer.WriteLine("// Buffer Implementation");
            m_writer.WriteLine("namespace he::schema");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            GenSrc_BufferImplRecursive(
                m_namespacePrefix,
                m_schema.objects,
                m_schema.enums,
                m_schema.interfaces,
                m_schema.structs,
                m_schema.unions);

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
    }
    void CodeGenCpp::GenSrc_BufferImplRecursive(
        StringView prefix,
        Span<const ObjectDef> objects,
        Span<const EnumDef> enums,
        Span<const InterfaceDef> interfaces,
        Span<const StructDef> structs,
        Span<const UnionDef> unions)
    {
        HE_UNUSED(enums);
        for (const ObjectDef& obj : objects)
        {
            switch (obj.type)
            {
                case ObjectDef::Type::Interface:
                {
                    const InterfaceDef& def = interfaces[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_BufferImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    break;
                }
                case ObjectDef::Type::Struct:
                {
                    const StructDef& def = structs[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_BufferImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    GenSrc_StructBuffer(prefix, def);
                    break;
                }
                case ObjectDef::Type::Union:
                    GenSrc_UnionBuffer(prefix, unions[obj.index]);
                    break;
            }
        }
    }

    void CodeGenCpp::GenSrc_StructBuffer(StringView prefix, const StructDef& def)
    {
        m_writer.WriteLine("template <> BufferOffset ToBuffer(BufferBuilder& builder, const {0}::{1}& value)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteIndent();
            m_writer.Write("const BufferOffset fieldOffset_{0}_ = ToBuffer(builder, value.{0});\n", field.name);
        }

        m_writer.WriteLine("builder.StartVTable();");

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("builder.AddVTableField({0}::{1}::FieldId_{2}, fieldOffset_{2}_);", prefix, def.name, field.name);
        }

        m_writer.WriteLine("return builder.EndVTable();");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::GenSrc_UnionBuffer(StringView prefix, const UnionDef& def)
    {
        m_writer.WriteLine("template <> BufferOffset ToBuffer(BufferBuilder& builder, const {0}::{1}& value)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("const BufferOffset offset = builder.WriteValue(value.tag);");
        m_writer.WriteLine("switch (value.tag)");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("case {0}::{1}::TagId_{2}: builder.WriteValue(value.value.{2}); break;", prefix, def.name, field.name);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
        m_writer.WriteLine("return offset;");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::GenSrc_JsonImpl()
    {
        if (m_options.json)
        {
            m_writer.WriteLine("// JSON Implementation");
            m_writer.WriteLine("namespace he::schema");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            GenSrc_JsonImplRecursive(
                m_namespacePrefix,
                m_schema.objects,
                m_schema.enums,
                m_schema.interfaces,
                m_schema.structs,
                m_schema.unions);

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }
    }

    void CodeGenCpp::GenSrc_JsonImplRecursive(
        StringView prefix,
        Span<const ObjectDef> objects,
        Span<const EnumDef> enums,
        Span<const InterfaceDef> interfaces,
        Span<const StructDef> structs,
        Span<const UnionDef> unions)
    {
        for (const ObjectDef& obj : objects)
        {
            switch (obj.type)
            {
                case ObjectDef::Type::Enum:
                    GenSrc_EnumJson(prefix, enums[obj.index]);
                    break;
                case ObjectDef::Type::Interface:
                {
                    const InterfaceDef& def = interfaces[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_JsonImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    break;
                }
                case ObjectDef::Type::Struct:
                {
                    const StructDef& def = structs[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_JsonImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    GenSrc_StructJson(prefix, def);
                    break;
                }
                case ObjectDef::Type::Union:
                    GenSrc_UnionJson(prefix, unions[obj.index]);
                    break;
            }
        }
    }

    void CodeGenCpp::GenSrc_EnumJson(StringView prefix, const EnumDef& def)
    {
        const bool isFlags = HasAttribute("Flags", def.attributes);

        m_writer.WriteLine("template <> rapidjson::Value ToJsonValue(rapidjson::Document&, const {0}::{1}& value)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        if (isFlags)
        {
            m_writer.WriteLine("using ValueType = std::underlying_type_t<{0}::{1}>;", prefix, def.name);
            m_writer.WriteLine("return rapidjson::Value(static_cast<ValueType>(value));");
        }
        else
        {
            m_writer.WriteLine("return rapidjson::Value(rapidjson::StringRef(AsString(value)));");
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        m_writer.WriteLine("template <> bool FromJsonValue(const rapidjson::Value& value, {0}::{1}& out)", prefix, def.name);

        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("if (value.IsNumber())");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        const char* const getIntStr = IsUnsignedIntegral(def.base) ? "GetUint64" : "GetInt64";
        m_writer.WriteLine("out = static_cast<{0}::{1}>(value.{2}());", prefix, def.name, getIntStr);
        m_writer.WriteLine("return true;");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        if (!isFlags)
        {
            m_writer.WriteLine("if (value.IsString())");
            m_writer.WriteLine("{");
            m_writer.IncreaseIndent();

            m_writer.WriteLine("const he::StringView valueName(value.GetString(), value.GetStringLength());");

            for (uint32_t i = 0; i < def.values.Size(); ++i)
            {
                const EnumValueDef& value = def.values[i];

                const char* const elseStr = i > 0 ? "else " : "";
                m_writer.WriteLine("{}if (valueName == \"{}\")", elseStr, value.name);
                m_writer.WriteLine("{");
                m_writer.IncreaseIndent();

                m_writer.WriteLine("out = {0}::{1}::{2};", prefix, def.name, value.name);
                m_writer.WriteLine("return true;");

                m_writer.DecreaseIndent();
                m_writer.WriteLine("}");
            }

            m_writer.DecreaseIndent();
            m_writer.WriteLine("}");
        }

        m_writer.WriteLine("return false;");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::GenSrc_StructJson(StringView prefix, const StructDef& def)
    {
        m_writer.WriteLine("template <> rapidjson::Value ToJsonValue(rapidjson::Document& doc, const {0}::{1}& value)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("rapidjson::Value v(rapidjson::kObjectType);");
        m_writer.WriteLine("v.MemberReserve({}, doc.GetAllocator());", def.fields.Size());

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("v.AddMember(\"{0}\", he::schema::ToJsonValue(doc, value.{0}).Move(), doc.GetAllocator());", field.name);
        }

        m_writer.WriteLine("return v;");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        m_writer.WriteLine("template <> bool FromJsonValue(const rapidjson::Value& value, {0}::{1}& out)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("if (!he::schema::FromJsonMember(value, \"{0}\", out.{0}))", field.name);
            m_writer.IncreaseIndent();

            m_writer.WriteLine("return false;");
            m_writer.DecreaseIndent();
        }

        m_writer.WriteLine("return true;");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::GenSrc_UnionJson(StringView prefix, const UnionDef& def)
    {
        m_writer.WriteLine("template <> rapidjson::Value ToJsonValue(rapidjson::Document& doc, const {0}::{1}& value)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("rapidjson::Value v(rapidjson::kObjectType);");
        m_writer.WriteLine("v.MemberReserve(2, doc.GetAllocator());");
        m_writer.WriteLine("v.AddMember(\"tag\", he::schema::ToJsonValue(doc, value.tag).Move(), doc.GetAllocator());");
        m_writer.WriteLine("switch (value.tag)");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("case {0}::{1}::TagId_{2}: v.AddMember(\"value\", he::schema::ToJsonValue(doc, value.value.{2}).Move(), doc.GetAllocator()); break;",
                prefix, def.name, field.name);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        m_writer.WriteLine("return v;");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        m_writer.WriteLine("template <> bool FromJsonValue(const rapidjson::Value& value, {0}::{1}& out)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("if (!he::schema::FromJsonMember(value, \"tag\", out.tag))");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("return false;");
        m_writer.DecreaseIndent();

        m_writer.WriteLine("switch (out.tag)");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("case {0}::{1}::TagId_{2}:", prefix, def.name, field.name);
            m_writer.IncreaseIndent();

            m_writer.WriteLine("if (!he::schema::FromJsonMember(value, \"value\", out.value.{}))", field.name);
            m_writer.IncreaseIndent();

            m_writer.WriteLine("return false;");
            m_writer.DecreaseIndent();

            m_writer.WriteLine("break;");
            m_writer.DecreaseIndent();
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");

        m_writer.WriteLine("return true;");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::GenSrc_ReflectionImpl()
    {
        if (m_options.reflection && !m_options.zeroCopy)
        {
            m_writer.WriteLine("// Reflection Implementation");
            if (!m_schema.namespaceName.IsEmpty())
            {
                m_writer.WriteIndent();
                m_writer.Write("namespace ");
                WriteWithReplace(m_schema.namespaceName, '.', "::");
                m_writer.Write('\n');
                m_writer.WriteLine("{");
                m_writer.IncreaseIndent();
            }

            GenSrc_ReflectionImplRecursive(
                m_namespacePrefix,
                m_schema.objects,
                m_schema.enums,
                m_schema.interfaces,
                m_schema.structs,
                m_schema.unions);

            if (!m_schema.namespaceName.IsEmpty())
            {
                m_writer.DecreaseIndent();
                m_writer.WriteLine("}");
            }
            m_writer.Write('\n');
        }
    }
    void CodeGenCpp::GenSrc_ReflectionImplRecursive(
        StringView prefix,
        Span<const ObjectDef> objects,
        Span<const EnumDef> enums,
        Span<const InterfaceDef> interfaces,
        Span<const StructDef> structs,
        Span<const UnionDef> unions)
    {
        HE_UNUSED(enums);
        for (const ObjectDef& obj : objects)
        {
            switch (obj.type)
            {
                case ObjectDef::Type::Interface:
                {
                    const InterfaceDef& def = interfaces[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_ReflectionImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    break;
                }
                case ObjectDef::Type::Struct:
                {
                    const StructDef& def = structs[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_ReflectionImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    GenSrc_StructReflection(prefix, def);
                    break;
                }
                case ObjectDef::Type::Union:
                    GenSrc_UnionReflection(prefix, unions[obj.index]);
                    break;
            }
        }
    }

    void CodeGenCpp::GenSrc_StructReflection(StringView prefix, const StructDef& def)
    {
        if (def.fields.IsEmpty())
            return;

        m_writer.WriteLine("const he::schema::FieldInfo {0}::{1}::Fields[FieldCount] = ", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const FieldDef& field : def.fields)
        {
            m_writer.WriteLine("{{ FieldId_{2}, sizeof({0}::{1}::{2}), offsetof({1}, {2}) }},", prefix, def.name, field.name);
        }

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::GenSrc_UnionReflection(StringView prefix, const UnionDef& def)
    {
        m_writer.WriteLine("const he::schema::FieldInfo {0}::{1}::Fields[FieldCount] = ", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("{{ FieldId_tag, sizeof({0}::{1}::tag), offsetof({1}, tag) }},", prefix, def.name);
        m_writer.WriteLine("{{ FieldId_value, sizeof({0}::{1}::value), offsetof({1}, value) }},", prefix, def.name);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("};");
    }

    void CodeGenCpp::GenSrc_StringImpl()
    {
        if (m_schema.enums.IsEmpty())
            return;

        m_writer.WriteLine("// Enum Stringification");
        m_writer.WriteLine("namespace he");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        GenSrc_StringImplRecursive(
            m_namespacePrefix,
            m_schema.objects,
            m_schema.enums,
            m_schema.interfaces,
            m_schema.structs,
            m_schema.unions);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
    }

    void CodeGenCpp::GenSrc_StringImplRecursive(
        StringView prefix,
        Span<const ObjectDef> objects,
        Span<const EnumDef> enums,
        Span<const InterfaceDef> interfaces,
        Span<const StructDef> structs,
        Span<const UnionDef> unions)
    {
        HE_UNUSED(unions);
        for (const ObjectDef& obj : objects)
        {
            switch (obj.type)
            {
                case ObjectDef::Type::Enum:
                    GenSrc_EnumAsString(prefix, enums[obj.index]);
                    break;
                case ObjectDef::Type::Struct:
                {
                    const StructDef& def = structs[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_StringImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    break;
                }
                case ObjectDef::Type::Interface:
                {
                    const InterfaceDef& def = interfaces[obj.index];
                    String childPrefix = prefix;
                    childPrefix += "::";
                    childPrefix += def.name;
                    GenSrc_StringImplRecursive(childPrefix, def.objects, def.enums, {}, def.structs, def.unions);
                    break;
                }
            }
        }
    }

    void CodeGenCpp::GenSrc_EnumAsString(StringView prefix, const EnumDef& def)
    {
        if (HasAttribute("Flags", def.attributes))
            return;

        m_writer.WriteLine("template <> const char* AsString({0}::{1} x)", prefix, def.name);
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        m_writer.WriteLine("switch (x)");
        m_writer.WriteLine("{");
        m_writer.IncreaseIndent();

        for (const EnumValueDef& val : def.values)
        {
            m_writer.WriteLine("case {0}::{1}::{2}: return \"{2}\";", prefix, def.name, val.name);
        }

        m_writer.WriteLine("case {0}::{1}::_Count: return \"_Count\";", prefix, def.name);

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}");
        m_writer.WriteLine("return \"<unknown>\";");

        m_writer.DecreaseIndent();
        m_writer.WriteLine("}\n");
    }

    bool CodeGenCpp::FlushToFile(const char* suffix)
    {
        String filePath(m_options.outDir, Allocator::GetTemp());
        ConcatPath(filePath, m_options.fileName);
        RemoveExtension(filePath);
        filePath += suffix;

        const StringView code = m_writer.Str();

        File f;
        if (!f.Open(filePath.Data(), FileOpenMode::WriteTruncate))
            return false;

        if (!f.Write(code.Data(), code.Size()))
            return false;

        return true;
    }

    void CodeGenCpp::WriteArraySize(const Type& t)
    {
        if (t.base != BaseType::Array)
            return;

        m_writer.Write('[');
        if (t.fixedSize != 0)
            m_writer.Write("{}", t.fixedSize);
        else
            WriteWithReplace(t.name, '.', "::");
        m_writer.Write(']');
    }

    void CodeGenCpp::WriteBufferType(const Type& t)
    {
        switch (t.base)
        {
            case BaseType::Bool:
            case BaseType::Int8:
            case BaseType::Int16:
            case BaseType::Int32:
            case BaseType::Int64:
            case BaseType::Uint8:
            case BaseType::Uint16:
            case BaseType::Uint32:
            case BaseType::Uint64:
            case BaseType::Float32:
            case BaseType::Float64:
            case BaseType::Enum:
                WriteNativeType(t);
                break;
            case BaseType::Array:
                m_writer.Write("he::schema::ArrayReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">");
                break;
            case BaseType::List:
                m_writer.Write("he::schema::ListReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">");
                break;
            case BaseType::Map:
                m_writer.Write("he::schema::MapReader<");
                WriteBufferWrappedType(*t.key);
                m_writer.Write(", ");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">");
                break;
            case BaseType::Pointer:
                WriteBufferType(*t.element);
                break;
            case BaseType::Set:
                m_writer.Write("he::schema::SetReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">");
                break;
            case BaseType::String:
                m_writer.Write("he::schema::StringReader");
                break;
            case BaseType::Vector:
                m_writer.Write("he::schema::VectorReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">");
                break;
            case BaseType::Alias:
            case BaseType::Interface:
            case BaseType::Struct:
            case BaseType::Union:
                m_writer.Write(t.name);
                m_writer.Write("::BufferReader");
                break;
            case BaseType::Unknown:
                HE_ASSERT(false, "Encountered an unknown type!");
                break;
        }
    }

    void CodeGenCpp::WriteBufferWrappedType(const Type& t)
    {
        switch (t.base)
        {
            case BaseType::Bool:
            case BaseType::Int8:
            case BaseType::Int16:
            case BaseType::Int32:
            case BaseType::Int64:
            case BaseType::Uint8:
            case BaseType::Uint16:
            case BaseType::Uint32:
            case BaseType::Uint64:
            case BaseType::Float32:
            case BaseType::Float64:
            case BaseType::Enum:
                WriteNativeType(t);
                break;
            case BaseType::Array:
                m_writer.Write("he::schema::RelPointer<he::schema::ArrayReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">>");
                break;
            case BaseType::List:
                m_writer.Write("he::schema::RelPointer<he::schema::ListReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">>");
                break;
            case BaseType::Map:
                m_writer.Write("he::schema::RelPointer<he::schema::MapReader<");
                WriteBufferWrappedType(*t.key);
                m_writer.Write(", ");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">>");
                break;
            case BaseType::Pointer:
                WriteBufferWrappedType(*t.element);
                break;
            case BaseType::Set:
                m_writer.Write("he::schema::RelPointer<he::schema::SetReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">>");
                break;
            case BaseType::String:
                m_writer.Write("he::schema::RelPointer<he::schema::StringReader>");
                break;
            case BaseType::Vector:
                m_writer.Write("he::schema::RelPointer<he::schema::VectorReader<");
                WriteBufferWrappedType(*t.element);
                m_writer.Write(">>");
                break;
            case BaseType::Alias:
            case BaseType::Interface:
            case BaseType::Struct:
            case BaseType::Union:
                m_writer.Write("he::schema::RelPointer<{}::BufferReader>", t.name);
                break;
            case BaseType::Unknown:
                HE_ASSERT(false, "Encountered an unknown type!");
                break;
        }
    }

    void CodeGenCpp::WriteEscaped(StringView input)
    {
        for (char ch : input)
        {
            switch (ch)
            {
                case '\'': // single quote
                    m_writer.Write("\\\'");
                    break;
                case '\"': // double quote
                    m_writer.Write("\\\"");
                    break;
                case '\\': // backslash
                    m_writer.Write("\\\\");
                    break;
                case '\b': // backspace
                    m_writer.Write("\\b");
                    break;
                case '\f': // form feed - new page
                    m_writer.Write("\\f");
                    break;
                case '\n': // line feed - new line
                    m_writer.Write("\\n");
                    break;
                case '\r': // carriage return
                    m_writer.Write("\\r");
                    break;
                case '\t': // horizontal tab
                    m_writer.Write("\\t");
                    break;
                case '\v': // vertical tab
                    m_writer.Write("\\v");
                    break;
                default:
                    // TODO: Hex sequence, Unicode sequence
                    m_writer.Write(ch);
            }
        }
    }

    void CodeGenCpp::WriteGenericDecl(const Vector<String>& typeParams)
    {
        if (typeParams.IsEmpty())
            return;

        m_writer.WriteIndent();
        m_writer.Write("template <");
        for (uint32_t i = 0; i < typeParams.Size(); ++i)
        {
            m_writer.Write("typename ");
            m_writer.Write(typeParams[i]);
            if (i < (typeParams.Size() - 1))
                m_writer.Write(", ");
        }
        m_writer.Write(">\n");
    }

    void CodeGenCpp::WriteNativeType(const Type& t)
    {
        switch (t.base)
        {
            case BaseType::Bool:
            case BaseType::Int8:
            case BaseType::Int16:
            case BaseType::Int32:
            case BaseType::Int64:
            case BaseType::Uint8:
            case BaseType::Uint16:
            case BaseType::Uint32:
            case BaseType::Uint64:
            case BaseType::Float32:
            case BaseType::Float64:
                m_writer.Write(GetScalarType(t.base));
                break;
            case BaseType::String:
                m_writer.Write("he::String");
                break;
            case BaseType::Array:
            {
                HE_ASSERT(t.element);
                WriteNativeType(*t.element);
                break;
            }
            case BaseType::List:
            {
                HE_ASSERT(t.element);
                m_writer.Write("std::list<");
                WriteNativeType(*t.element);
                WriteArraySize(*t.element);
                m_writer.Write('>');
                break;
            }
            case BaseType::Map:
            {
                HE_ASSERT(t.key && t.element);
                m_writer.Write("std::unordered_map<");
                WriteNativeType(*t.key);
                WriteArraySize(*t.element);
                m_writer.Write(", ");
                WriteNativeType(*t.element);
                WriteArraySize(*t.element);
                m_writer.Write('>');
                break;
            }
            case BaseType::Pointer:
                m_writer.Write("he::UniquePtr<");
                WriteNativeType(*t.element);
                m_writer.Write('>');
                break;
            case BaseType::Set:
            {
                HE_ASSERT(t.element);
                m_writer.Write("std::unordered_set<");
                WriteNativeType(*t.element);
                WriteArraySize(*t.element);
                m_writer.Write('>');
                break;
            }
            case BaseType::Vector:
            {
                HE_ASSERT(t.element);
                m_writer.Write("he::Vector<");
                WriteNativeType(*t.element);
                WriteArraySize(*t.element);
                m_writer.Write('>');
            }
            case BaseType::Alias:
            case BaseType::Enum:
                WriteWithReplace(t.name, '.', "::");
                break;
            case BaseType::Interface:
            case BaseType::Struct:
                m_writer.Write(t.name);
                if (!t.typeParams.IsEmpty())
                {
                    m_writer.Write('<');
                    for (uint32_t i = 0; i < t.typeParams.Size(); ++i)
                    {
                        WriteNativeType(t.typeParams[i]);
                        if (i < (t.typeParams.Size() - 1))
                            m_writer.Write(", ");
                    }
                    m_writer.Write('>');
                }
                break;
            case BaseType::Union:
                m_writer.Write(t.name);
                break;
            case BaseType::Unknown:
                HE_ASSERT(false, "Encountered an unknown type!");
                break;
        }
    }

    void CodeGenCpp::WriteNativeValue(BaseType t, const Value& v)
    {
        switch (t)
        {
            case BaseType::Bool: m_writer.Write("{}", v.basic.value.b); break;
            case BaseType::Int8: m_writer.Write("{}", v.basic.value.i8); break;
            case BaseType::Int16: m_writer.Write("{}", v.basic.value.i16); break;
            case BaseType::Int32: m_writer.Write("{}", v.basic.value.i32); break;
            case BaseType::Int64: m_writer.Write("{}", v.basic.value.i64); break;
            case BaseType::Uint8: m_writer.Write("{}", v.basic.value.u8); break;
            case BaseType::Uint16: m_writer.Write("{}", v.basic.value.u16); break;
            case BaseType::Uint32: m_writer.Write("{}", v.basic.value.u32); break;
            case BaseType::Uint64: m_writer.Write("{}", v.basic.value.u64); break;
            case BaseType::Float32: m_writer.Write("{}", v.basic.value.f32); break;
            case BaseType::Float64: m_writer.Write("{}", v.basic.value.f64); break;
            case BaseType::String:
                if (!v.str.IsEmpty())
                {
                    m_writer.Write('"');
                    WriteEscaped(v.str);
                    m_writer.Write('"');
                }
                break;
            case BaseType::Pointer:
                break;
            case BaseType::Array:
            case BaseType::List:
            case BaseType::Map:
            case BaseType::Set:
            case BaseType::Vector:
            case BaseType::Interface:
            case BaseType::Struct:
            case BaseType::Union:
                m_writer.Write(v.str);
                break;
            case BaseType::Alias:
            case BaseType::Enum:
                WriteWithReplace(v.str, '.', "::");
                break;
            case BaseType::Unknown:
                HE_ASSERT(false, "Encountered an unknown type!");
                break;
        }
    }

    void CodeGenCpp::WriteParamType(const Type& t)
    {
        switch (t.base)
        {
            case BaseType::Bool:
            case BaseType::Int8:
            case BaseType::Int16:
            case BaseType::Int32:
            case BaseType::Int64:
            case BaseType::Uint8:
            case BaseType::Uint16:
            case BaseType::Uint32:
            case BaseType::Uint64:
            case BaseType::Float32:
            case BaseType::Float64:
            case BaseType::Enum:
                WriteNativeType(t);
                break;
            case BaseType::Pointer:
                WriteNativeType(*t.element);
                m_writer.Write('*');
                break;
            case BaseType::String:
            case BaseType::Array:
            case BaseType::List:
            case BaseType::Map:
            case BaseType::Set:
            case BaseType::Vector:
            case BaseType::Alias:
            case BaseType::Interface:
            case BaseType::Struct:
            case BaseType::Union:
                m_writer.Write("const ");
                WriteNativeType(t);
                m_writer.Write('&');
                break;
            case BaseType::Unknown:
                HE_ASSERT(false, "Encountered an unknown type!");
                break;
        }
    }

    void CodeGenCpp::WriteUnsignedAsHex(BaseType t, const Value& v)
    {
        switch (t)
        {
            case BaseType::Uint8: m_writer.Write(HE_HEX_FMT, HE_HEX_VAL(v.basic.value.u8)); break;
            case BaseType::Uint16: m_writer.Write(HE_HEX_FMT, HE_HEX_VAL(v.basic.value.u16)); break;
            case BaseType::Uint32: m_writer.Write(HE_HEX_FMT, HE_HEX_VAL(v.basic.value.u32)); break;
            case BaseType::Uint64: m_writer.Write(HE_HEX_FMT, HE_HEX_VAL(v.basic.value.u64)); break;
            default:
                HE_ASSERT(false, "Can only write unsigned integer values as hex.");
                break;
        }
    }

    void CodeGenCpp::WriteWithReplace(StringView input, char what, StringView with)
    {
        for (char ch : input)
        {
            if (ch == what)
            {
                m_writer.Write(with);
            }
            else
            {
                m_writer.Write(ch);
            }
        }
    }

    const char* CodeGenCpp::GetScalarType(BaseType t)
    {
        switch (t)
        {
            case BaseType::Bool: return "bool";
            case BaseType::Int8: return "int8_t";
            case BaseType::Int16: return "int16_t";
            case BaseType::Int32: return "int32_t";
            case BaseType::Int64: return "int64_t";
            case BaseType::Uint8: return "uint8_t";
            case BaseType::Uint16: return "uint16_t";
            case BaseType::Uint32: return "uint32_t";
            case BaseType::Uint64: return "uint64_t";
            case BaseType::Float32: return "float";
            case BaseType::Float64: return "double";
            default:
                HE_ASSERT(false, "Invalid base type encountered in WriteSimpleType!");
                break;
        }

        return "";
    }

    bool GenerateCpp(const SchemaDef& def, const CodeGenOptions& options)
    {
        CodeGenCpp generator(def, options);
        if (!generator.Generate())
            return false;

        return true;
    }
}
