using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Harvest.SourceGenerators;

[Generator]
public class CommandProviderGenerator : IIncrementalGenerator
{
    private const string CommandAttributeName = "Harvest.Common.Attributes.CommandAttribute";
    private const string OptionAttributeName = "Harvest.Common.Attributes.OptionAttribute";
    private const string ArgumentAttributeName = "Harvest.Common.Attributes.ArgumentAttribute";

    private const string ICommandExecutorInterfaceName = "Harvest.Common.ICommandExecutor";

    private static readonly DiagnosticDescriptor NoCommandExecutorInterfaceError = new(
        id: "HE0002",
        title: "Class does not implement ICommandExecutor",
        messageFormat: $"Class '{{0}}' must implement the {ICommandExecutorInterfaceName} interface to be used as a Command",
        category: "SourceGeneration",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTarget(s),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classDeclarations, GenerateSource);
    }

    private static bool IsSyntaxTarget(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0;
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        ISymbol? symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
        if (symbol is not INamedTypeSymbol namedTypeSymbol || namedTypeSymbol.IsAbstract)
        {
            return null;
        }

        foreach (AttributeData attribute in namedTypeSymbol.GetAttributes())
        {
            string? attrName = attribute.AttributeClass?.ToDisplayString();
            if (attrName == CommandAttributeName)
            {
                return namedTypeSymbol;
            }
        }

        return null;
    }

    private static void GenerateSource(SourceProductionContext context, INamedTypeSymbol? symbol)
    {
        if (symbol is null)
        {
            return;
        }

        AttributeData? commandAttribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == CommandAttributeName);

        if (commandAttribute is null)
        {
            return;
        }

        if (symbol.AllInterfaces.FirstOrDefault(i => i.ToDisplayString() == ICommandExecutorInterfaceName) is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                NoCommandExecutorInterfaceError,
                symbol.Locations.FirstOrDefault(),
                symbol.Name));
            return;
        }

        string? commandDesc = commandAttribute.ConstructorArguments[0].Value?.ToString();
        string commandName = commandAttribute.ConstructorArguments[1].Value?.ToString() ?? GetDefaultCommandName(symbol.Name);

        IEnumerable<IPropertySymbol> properties = symbol.GetMembers().OfType<IPropertySymbol>();
        List<(IPropertySymbol Property, AttributeData Attribute)> options = [];
        List<(IPropertySymbol Property, AttributeData Attribute)> arguments = [];

        foreach (IPropertySymbol property in properties)
        {
            AttributeData? optAttr = property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == OptionAttributeName);
            if (optAttr is not null)
            {
                options.Add((property, optAttr));
                continue;
            }

            AttributeData? argAttr = property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ArgumentAttributeName);
            if (argAttr is not null)
            {
                arguments.Add((property, argAttr));
            }
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.CommandLine;");
        sb.AppendLine("using System.CommandLine.Invocation;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Harvest.Common;");
        sb.AppendLine();

        if (!symbol.ContainingNamespace.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {symbol.Name} : ICommandProvider");
        sb.AppendLine("{");
        sb.AppendLine("    public Command GetCommand()");
        sb.AppendLine("    {");
        if (string.IsNullOrEmpty(commandDesc))
        {
            sb.AppendLine($"        Command command = new(\"{commandName}\");");
        }
        else
        {
            sb.AppendLine($"        Command command = new(\"{commandName}\", \"{EscapeQuotes(commandDesc!)}\");");
        }
        sb.AppendLine();

        foreach ((IPropertySymbol prop, AttributeData attr) in options)
        {
            string? desc = attr.ConstructorArguments[0].Value?.ToString();
            string name = attr.ConstructorArguments[1].Value?.ToString() ?? GetDefaultOptionName(prop.Name);

            ImmutableArray<TypedConstant> aliasesArg = attr.NamedArguments.FirstOrDefault(n => n.Key == "Aliases").Value.Values;
            IEnumerable<string> aliases = aliasesArg.Select(v => v.Value?.ToString()).Where(v => v is not null)!;

            object? required = attr.NamedArguments.FirstOrDefault(n => n.Key == "IsRequired").Value.Value;

            string propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string varName = $"opt_{prop.Name}";

            sb.Append($"        Option<{propType}> {varName} = new(\"{name}\"");

            if (aliases.Any())
            {
                sb.Append(", [");
                bool first = true;
                foreach (string alias in aliases)
                {
                    if (!first)
                    {
                        sb.Append(", ");
                    }
                    first = false;

                    sb.Append('"');
                    sb.Append(alias);
                    sb.Append('"');
                }
                sb.Append(']');
            }
            sb.AppendLine(");");

            if (!string.IsNullOrEmpty(desc))
            {
                sb.AppendLine($"        {varName}.Description = \"{EscapeQuotes(desc!)}\";");
            }

            if (required is bool isRequired && isRequired)
            {
                sb.AppendLine($"        {varName}.Required = true;");
            }
            else if (prop.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is PropertyDeclarationSyntax propDecl)
            {
                if (propDecl.Initializer is not null)
                {
                    sb.AppendLine($"        {varName}.DefaultValueFactory = _ => {propDecl.Initializer.Value};");
                }
            }

            sb.AppendLine($"        command.Options.Add({varName});");
            sb.AppendLine();
        }

        foreach ((IPropertySymbol prop, AttributeData attr) in arguments)
        {
            string? desc = attr.ConstructorArguments[0].Value?.ToString();
            string name = attr.ConstructorArguments[1].Value?.ToString() ?? GetDefaultArgumentName(prop.Name);
            string arity = GetArgumentArityFromEnum(prop, attr.NamedArguments.FirstOrDefault(n => n.Key == "Arity").Value);

            string propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string varName = $"arg_{prop.Name}";

            sb.Append($"        Argument<{propType}> {varName} = new(\"{name}\");");

            if (!string.IsNullOrEmpty(desc))
            {
                sb.AppendLine($"        {varName}.Description = \"{EscapeQuotes(desc!)}\";");
            }

            sb.AppendLine($"        {varName}.Arity = {arity.TrimStart('E')};");

            if (prop.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is PropertyDeclarationSyntax propDecl)
            {
                if (propDecl.Initializer is not null)
                {
                    sb.AppendLine($"        {varName}.DefaultValueFactory = _ => {propDecl.Initializer.Value};");
                }
            }

            sb.AppendLine($"        command.Arguments.Add({varName});");
            sb.AppendLine();
        }

        sb.AppendLine("        command.SetAction((ParseResult parseResult, CancellationToken ct) =>");
        sb.AppendLine("        {");

        // Bind Options
        foreach ((IPropertySymbol prop, AttributeData _) in options)
        {
            string propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string varName = $"opt_{prop.Name}";
            sb.AppendLine($"            if (parseResult.GetValue({varName}) is {propType} {varName}_value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                this.{prop.Name} = {varName}_value;");
            sb.AppendLine("            }");
        }

        // Bind Arguments
        foreach ((IPropertySymbol prop, AttributeData _) in arguments)
        {
            string propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string varName = $"arg_{prop.Name}";
            sb.AppendLine($"            if (parseResult.GetValue({varName}) is {propType} {varName}_value)");
            sb.AppendLine("            {");
            sb.AppendLine($"                this.{prop.Name} = {varName}_value;");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return this.ExecuteAsync(ct);");
        sb.AppendLine("        });");

        sb.AppendLine();
        sb.AppendLine("        return command;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{symbol.Name}_CommandProvider.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetArgumentArityFromEnum(IPropertySymbol prop, TypedConstant typedConstant)
    {
        if (typedConstant.Kind == TypedConstantKind.Enum && typedConstant.Value is not null)
        {
            object value = typedConstant.Value;
            if (typedConstant.Type is INamedTypeSymbol enumType)
            {
                IFieldSymbol? enumMember = enumType.GetMembers()
                    .OfType<IFieldSymbol>()
                    .FirstOrDefault(m => m.ConstantValue != null && m.ConstantValue.Equals(value));

                if (enumMember?.Name is string name)
                {
                    return $"ArgumentArity.{name}";
                }
            }
        }

        return GetDefaultArgumentArity(prop);
    }

    private static string GetDefaultArgumentArity(IPropertySymbol prop)
    {
        if (prop.Type.SpecialType == SpecialType.System_Array
            || prop.Type.AllInterfaces.Any(i => i.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>"))
        {
            return "ArgumentArity.ZeroOrMore";
        }

        return "ArgumentArity.ZeroOrOne";
    }

    private static string GetDefaultOptionName(string propName)
    {
        if (string.IsNullOrEmpty(propName))
        {
            return "";
        }

        ReadOnlySpan<char> name = TrimEnd(propName, "Option");

        StringBuilder sb = new();
        sb.Append("--");
        AppendAsKebabCase(sb, name);

        return sb.ToString();
    }

    private static string GetDefaultArgumentName(string propName)
    {
        if (string.IsNullOrEmpty(propName))
        {
            return "";
        }

        ReadOnlySpan<char> name = TrimEnd(propName, "Argument");
        name = TrimEnd(name, "Arg");

        StringBuilder sb = new();
        AppendAsKebabCase(sb, name);

        return sb.ToString();
    }

    private static string GetDefaultCommandName(string className)
    {
        if (string.IsNullOrEmpty(className))
        {
            return "";
        }

        ReadOnlySpan<char> name = TrimEnd(className, "Command");

        StringBuilder sb = new();
        AppendAsKebabCase(sb, name);

        return sb.ToString();
    }

    private static void AppendAsKebabCase(StringBuilder sb, ReadOnlySpan<char> input)
    {
        for (int i = 0; i < input.Length; ++i)
        {
            char c = input[i];

            // If uppercase and not the first char, add dash
            if (char.IsUpper(c) && i > 0)
            {
                sb.Append('-');
            }

            sb.Append(char.ToLower(c));
        }
    }

    private static string EscapeQuotes(string input)
    {
        return input.Replace("\"", "\\\"");
    }

    private static ReadOnlySpan<char> TrimEnd(ReadOnlySpan<char> span, ReadOnlySpan<char> value)
    {
        if (span.Length < value.Length)
        {
            return span;
        }

        ReadOnlySpan<char> end = span.Slice(span.Length - value.Length, value.Length);
        if (end.SequenceEqual(value))
        {
            return span[..^value.Length];
        }
        return span;
    }
}
