using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Harvest.SourceGenerators;

[Generator]
public class DependencyPropertyGenerator : IIncrementalGenerator
{
    private const string DependencyPropertyAttributeName = "Luna.Common.Attributes.DependencyPropertyAttribute";

    private static readonly DiagnosticDescriptor InvalidReferencePropertyError = new(
        id: "HE0001",
        title: "Invalid property declaration",
        messageFormat: "Property '{0}' is a reference type, but does not express nullability. All dependency properties of reference types will initialize to null.",
        category: "SourceGeneration",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<PropertyModel> propertyDeclarations = context.SyntaxProvider
        .CreateSyntaxProvider(
            predicate: static (s, _) => IsSyntaxTarget(s),
            transform: static (ctx, _) => GetSemanticTarget(ctx))
        .Where(static m => m is not null)!;

        var groupedProperties = propertyDeclarations.Collect().SelectMany((properties, _) =>
            properties.AsEnumerable().GroupBy(f => f.Symbol.ContainingType, SymbolEqualityComparer.Default));

        context.RegisterSourceOutput(groupedProperties, static (spc, group) =>
            GenerateSource(spc, group.Key as INamedTypeSymbol, group));
    }

    private static bool IsSyntaxTarget(SyntaxNode node)
    {
        return node is PropertyDeclarationSyntax f && f.AttributeLists.Count > 0;
    }

    private static IPropertySymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        if (context.Node is not PropertyDeclarationSyntax propertyDecl)
        {
            return null;
        }

        ISymbol? symbol = context.SemanticModel.GetDeclaredSymbol(propertyDecl);
        if (symbol is not IPropertySymbol propertySymbol)
        {
            return null;
        }

        foreach (AttributeData attribute in propertySymbol.GetAttributes())
        {
            string? attrName = attribute.AttributeClass?.ToDisplayString();
            if (attrName == DependencyPropertyAttributeName)
            {
                return propertySymbol;
            }
        }

        return null;
    }

    private static void GenerateSource(SourceProductionContext context, INamedTypeSymbol? symbol, IEnumerable<IPropertySymbol?> properties)
    {
        if (symbol is null)
        {
            return;
        }

        bool hasProperties = properties.Any(p => p is not null);
        if (!hasProperties)
        {
            return;
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.UI.Xaml;");
        sb.AppendLine("using Microsoft.UI.Xaml.Controls;");
        sb.AppendLine();

        if (!symbol.ContainingNamespace.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {symbol.Name}");
        sb.AppendLine("{");

        foreach (IPropertySymbol? property in properties)
        {
            if (property is null)
            {
                continue;
            }

            if (property.Type.IsReferenceType && property.Type.NullableAnnotation != NullableAnnotation.Annotated)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidReferencePropertyError,
                    property.Locations.FirstOrDefault(),
                    property.Name));
                continue;
            }

            string propName = NormalizePropertyName(property.Name);
            string dpName = $"{propName}Property";

            string defaultValue = propertyDecl.Initializer?.Value.ToString()
                ?? (propertySymbol.Type.IsReferenceType ? "null" : $"default({propertySymbol.Type.ToDisplayString()})");

            string? changeCallback = dpAttr.ConstructorArguments.FirstOrDefault()?.Value?.ToString();

            string propType = property.Type.ToDisplayString();

            string runtimePropType = property.Type.IsReferenceType
                ? property.Type.WithNullableAnnotation(NullableAnnotation.None).ToDisplayString()
                : property.Type.ToDisplayString();

            sb.AppendLine($"    public static readonly DependencyProperty {dpName} =");
            sb.AppendLine($"        DependencyProperty.Register(");
            sb.AppendLine($"            nameof({propName}),");
            sb.AppendLine($"            typeof({runtimePropType}),");
            sb.AppendLine($"            typeof({symbol.Name}),");
            if (string.IsNullOrEmpty(changeCallback))
            {
                sb.AppendLine($"            new PropertyMetadata({defaultValue}));");
            }
            else
            {
                sb.AppendLine($"            new PropertyMetadata({defaultValue}, {changeCallback}));");
            }
            sb.AppendLine();

            sb.AppendLine($"    public partial {propType} {propName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => ({propType})GetValue({dpName});");
            sb.AppendLine($"        set => SetValue({dpName}, value);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource($"{symbol.Name}_DependencyProperties.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string NormalizePropertyName(string propertyName)
    {
        string clean = propertyName.TrimStart('_');
        if (clean.Length == 0)
        {
            throw new ArgumentException("Property name must contain at least one character after underscores are removed.");
        }

        return char.ToUpper(clean[0]) + clean.Substring(1);
    }
}
