using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

[Generator]
public class DependencyInjectionGenerator : IIncrementalGenerator
{
    private const string CommonAttributesNamespace = "Harvest.Common.Attributes";

    private const string SingletonServiceAttributeName = "SingletonServiceAttribute";
    private const string TransientServiceAttributeName = "TransientServiceAttribute";
    private const string ScopedServiceAttributeName = "ScopedServiceAttribute";
    private const string CommandAttributeName = "CommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTarget(s),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null)!;

        var classes = classDeclarations.Collect();

        context.RegisterSourceOutput(classes, GenerateSource);
    }

    private static bool IsSyntaxTarget(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax c
            && c.AttributeLists.Count > 0;
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        ISymbol? symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
        if (symbol is not INamedTypeSymbol namedTypeSymbol || namedTypeSymbol.IsAbstract)
        {
            return null;
        }

        foreach (AttributeData attribute in namedTypeSymbol.GetAttributes())
        {
            string namespaceName = attribute.AttributeClass?.ContainingNamespace.ToDisplayString();
            if (namespaceName != CommonAttributesNamespace)
            {
                continue;
            }

            string attrName = attribute.AttributeClass?.Name ?? "";
            if (attrName == SingletonServiceAttributeName
                || attrName == TransientServiceAttributeName
                || attrName == ScopedServiceAttributeName
                || attrName == CommandAttributeName)
            {
                return namedTypeSymbol;
            }
        }

        return null;
    }

    private static void GenerateSource(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> classes)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        sb.AppendLine("namespace Harvest;");
        sb.AppendLine();

        sb.AppendLine("internal static class GeneratedServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddAutoDiscoveredServices(this IServiceCollection services)");
        sb.AppendLine("    {");

        // Sort by name to ensure deterministic build output (important for caching)
        foreach (INamedTypeSymbol symbol in classes.OrderBy(c => c.Name))
        {
            foreach (AttributeData attribute in symbol.GetAttributes())
            {
                string fullSymbolName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                string? attrName = attribute.AttributeClass?.Name;
                string? method = attrName switch
                {
                    SingletonServiceAttributeName => "AddSingleton",
                    TransientServiceAttributeName => "AddTransient",
                    ScopedServiceAttributeName => "AddScoped",
                    CommandAttributeName => "AddTransient",
                    _ => null,
                };

                if (string.IsNullOrEmpty(method))
                {
                    continue;
                }

                if (attrName == CommandAttributeName)
                {
                    sb.AppendLine($"        services.{method}<global::Harvest.Common.ICommandProvider, {fullSymbolName}>();");
                }
                else if (attribute.AttributeClass?.IsGenericType == true
                    && attribute.AttributeClass.TypeArguments.Length > 0)
                {
                    ITypeSymbol interfaceType = attribute.AttributeClass.TypeArguments[0];
                    string fullInterfaceName = interfaceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine($"        services.{method}<{fullInterfaceName}, {fullSymbolName}>();");
                }
                else
                {
                    sb.AppendLine($"        services.{method}<{fullSymbolName}>();");
                }
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Inject the created source code into the compilation
        context.AddSource("GeneratedServiceCollectionExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
