name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
        arch: [x64]
    steps:
    - name: Install Dependencies
      run: sudo apt install -y libx11-dev libxi-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Build
      run: cd build && PATH="/usr/lib/llvm-12/bin:$PATH" make -j$(nproc) config=${{ matrix.config }}_${{ matrix.arch }} all
    - name: Test
      run: ./build/bin/linux-${{ matrix.config }}_${{ matrix.arch }}/he_test_runner
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]
        arch: [x64, arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Bootstrap
      run: ./bootstrap.sh
      shell: bash
    - name: Build
      run: MSBuild.exe build/harvest-engine.sln /m /p:Configuration="${{ matrix.config }}" /p:Platform="${{ matrix.arch }}" /nodeReuse:false
    - name: Test
      if: ${{ matrix.arch != 'arm64' }}
      run: ./build/bin/windows-${{ matrix.config }}_${{ matrix.arch }}/he_test_runner.exe
